.gitignore
SETUP.md
palindrome-products/gulpfile.js
palindrome-products/package.json
palindrome-products/palindrome-products.js

This pull request includes Node.js dependencies file (`package.json`) and a Gulp file (`gulpfile.js`) that allows the user to run assignment tests with just one command (once all dependencies are installed):
```bash
$ gulp test
```
These files are included in the only existing assignment directory (palindrome-products). Each assignment should have the same files so that there is a common way to run tests for all assignments.
The pull request also includes content for the `SETUP.md` file explaining how to install dependencies and how to run tests. Finally, it modifies `.gitignore` to ignore transpiled JavaScript files (from ES6 to ES5) and tools installed for each assignment.

Make it easier for a user to run assignment's tests 

---

.travis.yml
Makefile
README.md

Configure Travis CI to run the `make test` command that will run
all tests. Jasmine skipped tests are enabled by replacing `xit`
methods by `it` ones.
And the `README.md` file shows correctly the icon about the
Travis build.

Configure Travis CI to run all tests

---

Makefile
bob/gulpfile.js
gulpfile.js
hello-world/gulpfile.js
package.json
palindrome-products/gulpfile.js

This PR includes the following improvements:
1. Replace deprecated dev dependency, `gulp-clean` with `del`
2. Decide whether input and output dirs come from command line arguments or harcoded values. Hardcoded values will be used in individual assignments.
3. `make` command creates copies of `gulpfile.js` in each assignment. This way, it is as if there were no `gulpfile.js` duplication. Any change in ./gulpfile.js will be copied to each `<assignment>/gulpfile.js` so that all `gulpfile.js`s will be synchronized.

Improve `gulpfile.js`

---

anagram/example.js

Previously, the ES2015 feature used was the spread operator `...` as `matches` method params. But it made the code use `words[0]` to do some checks, and it looked ugly.
Stop using the spread operator and use the new method [`Array.from()`][1] makes the code cleaner and easier to read.
[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

Make anagram example simple and more ES2015-ish

---

palindrome-products/example.js
palindrome-products/palindrome-products_test.spec.js

This first test for this exercise did not agree with the one in the JS track, omitting most of the factors for the first palindrome.  
There was also a small typo in the description for the second one.

first test omitted many sets of factors

---

gigasecond/gigasecond_test.spec.js

2 out of 3 tests were active. Now, only the first one is active.

Only one test should be active

---

hello-world/example.js
hello-world/hello-world_test.spec.js

The test is checking for lowercase `world` instead of the `World` that the README.md file calls for.

Fixes error in test

---

phone-number/phone-number.spec.js

Not a big deal. 
ECMAScript introduces `let` and `const` as an alternative to `var`. Some great developers (like [John Resig on twitter](https://twitter.com/jeresig/status/657262368150396928?s=09)) recommend using `const` whenever possible. If not, use `let`.

Use 'const' instead of 'var'

---

robot-name/robot-name.spec.js

Use the new collection added in ES2015 `Set` to check that all generated names are different.

Use ES2015 feature Set() to store unique robot names

---

grade-school/grade-school.spec.js

@rchavarria this is a test to ensure the ```roster``` object can't be modified from the outside.
Not sure if this is present in other tracks or if you want to merge, but here it is if you want it.

test to ensure roster object is private

---

grains/grains.spec.js

BigInt does not need to be imported to grains.spec.js

Remove bigint

---

food-chain/food-chain.spec.js

Same as #50, tests used `var` when `const` would be more appropriate.

Food chain exercise: use `const` instead of `var`

---

config.json

A test pattern can be defined in `config.json` to help exercism.io to identify files that contain tests.
That would avoid having small bugs as described on [exercism/exercism.io#2610](https://github.com/exercism/exercism.io/issues/2610).

Provide a pattern to identify a file as a test file based on its name

---

.travis.yml

This PR tries to fix Travis CI builds that fail in the new Travis CI platform.
Now, instead of configuring `bash` as the build language (in the `.travis.yaml` file), `node_js` is configured. The used version for NodeJS is 4.1.
I've tried in my fork of this project and it works in the old Travis CI platform. This PR will check if the new configuration works for this repository.

Use NodeJS language instead of bash

---

binary-search/binary-search.spec.js
binary-search/example.js
binary-search/gulpfile.js
binary-search/package.json
config.json

This PR adds a new exercise from the xjavascript track.

Add new exercise: Binary search

---

exercises/linked-list/example.js
exercises/linked-list/linked-list.spec.js

Add tests cases to ensure the linked list's state is properly reset when popping/shifting its last element.

Add tests for emptying list, then adding elements

---

exercises/linked-list/linked-list.spec.js

As observed by @cebial on the [JS track](https://github.com/exercism/xjavascript/pull/167), there is a test against an empty list that is specifically prohibited by the README for this exercise.
This PR removes that test.

Remove test which pops empty list

---

exercises/largest-series-product/largest-series-product.spec.js

The digits and slices functions are internal implementation details and
thus the test case for the largest-series-product problem should not be
concerned with testing them. The series tests could potentially be moved
to the series exercise (already implemented by this track).
Their presence may cause students to falsely think that their solution
has to use these two functions, instead of the alternative
implementation of only iterating through the digits once.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the digits and slices tests), then consider
including a hints file and/or directory in the largest-series-product
directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192
Relevant to #202: This will …

largest-series-product: Do not test digits/slices

---

exercises/sum-of-multiples/example.js
exercises/sum-of-multiples/sum-of-multiples.spec.js

Remove default list of multiples

---

exercises/word-count/example.js
exercises/word-count/word-count.spec.js

The test metadata for this exercise specifies that counts should be independent of the case of the input words.
This PR brings this exercise in to conformance with that requirement.

Update tests and example to be case-agnostic

---

exercises/binary/binary.spec.js

Addresses #213 and adds the missing test: alphabetic characters in the number makes it to be decimal 0.

Binary: add missing test

---

Makefile

I noticed that any spec with an `xdescribe` was not tested correctly with `make test`. This ensures that these `describe`s are enabled along with all `it`s.

Makefile: Replace xdescribe with describe in addition to replacing xit with it

---

exercises/circular-buffer/circular-buffer.spec.js

... such that if `buffer` is an object, `this` is set to the proper value when `read` is invoked.

Wrap the function to test

---

exercises/trinary/example.js
exercises/trinary/trinary.spec.js

Trinary numbers should contain only digits from `0` to `2`
Trinary numbers have a base of `3`, and they can only be
expressed with digits from `0` to `n < BASE`

Trinary misses an illegal case

---

docs/INSTALLATION.md

Update link to "Installing-Node.js-via-package-manager" instructions which are now hosted on nodejs.org.
Fix instructions for Windows/OS X and add link to download installer.

Update Node.js download/installation links

---

exercises/simple-cipher/simple-cipher.spec.js

It was pass string like '123ABCxyz'.

Simple cipher misses an illegal case.

---

exercises/grade-school/grade-school.spec.js

Grade School has a test to prevent modifications when calling the roster() method. However, there is no test to prevent modifications when calling the grade() method. This PR adds a test to address the grade() scenario.
My code in this submission passes the existing tests, but allows modifications through grade():
http://exercism.io/submissions/971cbf70d109466ba098fa6c0195eb00

Add test to Grade School

---

exercises/rna-transcription/example.js
exercises/rna-transcription/rna-transcription.spec.js

As per [x-common canonical data](https://github.com/exercism/x-common/blob/master/exercises/rna-transcription/canonical-data.json#L40-L54)
Fixes #248

Rna-Transcription: Handle invalid nucleotides in strand

---

exercises/phone-number/example.js
exercises/phone-number/phone-number.spec.js

Recently x-common got data for phone-numbers:
https://github.com/exercism/x-common/blob/master/exercises/phone-number/canonical-data.json
Make our tests consistent with that data.

Make phone-number specs consistent with x-common data

---

exercises/luhn/example.js
exercises/luhn/luhn.spec.js

Canonical specs for Luhn exercise were changed, and tracks implementing that exercise should synchronize wih them.
Closes #260

Synchronize Luhn exercise with canonical specs

---

exercises/hello-world/example.js
exercises/hello-world/hello-world.js
exercises/hello-world/hello-world.spec.js
exercises/leap/example.js
exercises/leap/leap.spec.js

* As per @rchavarria's comment https://github.com/exercism/xecmascript/issues/274#issuecomment-297439261, do not make users switch between classes and functions for solutions. Only `hello-world` and `leap` exercises were expecting functions, convert their specs to expect classes instead.
* Also took the opportunity to remove some specs from `leap` as per the `x-common`. Keep only what are absolute necessary.
Kept the commits separate since I think they do different things.

Maintain class consistency

---

exercises/perfect-numbers/example.js
exercises/perfect-numbers/perfect-numbers.spec.js

The [canonical-data](https://github.com/exercism/x-common/blob/master/exercises/perfect-numbers/canonical-data.json#L86-L106) says it should be an error. Raise an error instead of just returning
the string.

Throw error for invalid input of perfect-numbers

---

README.md

Just because it's cooler and looks more organized 😄
Preview here: https://github.com/joelwallis/exercism-xecmascript/tree/move-gitter-badge-to-header

Move the Gitter badge to the header

---

.travis.yml
Makefile

The Makefile was relying on global installation of jest to run the
tests. This failed for me since I did not have jest globally
installed. Also the README does not mention about installing globally
which is anyways not a good idea (might cause issues due to different versions).
Hence, change Makefile to use locally installed jest instead.

Use local jest instead of global in Makefile

---

.github/stale.yml

We want to keep these issues open indefinitely for first-timers.
Tell probot to ignore them so that they are never closed
automatically.
`pinned` and `security` are default. I added `good first patch` and
`first-timers only`.

Add first patch labels to probot exempt

---

Makefile

* Show filenames in error msg for test-package-files
* Ignore node_modules inside exercises
Fixes #301

Fix test package files task

---

config.json
exercises/list-ops/example.js
exercises/list-ops/list-ops.spec.js
exercises/list-ops/package.json

A few thoughts:
1. I let myself use `pop` and `push`, using arrays to store the data. No Array iterator methods, no `length` property.  I did cheat a little and use the array index for the `foldr` method.  If anyone has any better ideas for this, I'm open.
2. I intentionally didn't mutate the inputs.  If we were handling objects instead of primitives, we might want to copy the objects before adding them to the list.
3. I made `length()` a method rather than a property.  I could be persuaded to change that, but it does mean that the `length` property would have to be updated with every relevant operation, so, it seems nicer to calculate it when needed.
4. Where it made sense, I made the methods chainable.  Some of the tests expect this, but I think that's OK since we're trying to emulate …

Add exercise List-Ops

---

README.md

Travis CI batch was pointing to the previous repo URL `.../xecmascript...`

Fix link to the repo for the Travis CI batch

---

config.json
exercises/sublist/README.md
exercises/sublist/example.js
exercises/sublist/package.json
exercises/sublist/sublist.spec.js

@exercism/ecmascripts ?
@rchavarria @joelwallis I *did* solve this one.  This solution was built entirely using TDD, with a refactor at the end to use an object instead of `if` statements.  😜

Add exercise sublist

---

config.json

Based on the work on the `javascript` (https://github.com/exercism/javascript/pull/386) track...
1. 18 exercises, sorted by difficulty, has been selected as *core* ones: hello-world, leap, rna-transcription, simple-cipher, pangram, bob, gigasecond, space-age, binary, prime-factors, matrix, linked-list, pascals-triangle, secret-handshake, grade-school, robot-name, wordy and list-ops
2. 3 exercises are non-core ones and they are not unlocked by any exercise: roman-numerals, queen-attack and minesweeper
3. The rest of the exercises are non-core and they are unlocked by just one exercise
All this completes tasks in #324 
There are some differences between the two tracks about the exercises they implement, just in case we want to implement them easily:
- These exercises are present in …

Set core, non-core exercises and unlocking ones

---

config.json
exercises/proverb/README.md
exercises/proverb/example.js
exercises/proverb/package.json
exercises/proverb/proverb.spec.js

Creating a new pull request with the code changes for this exercise.  I closed the old one because the git commit history for the branch associated with previous pull request did not look clean after the merge with master:
commit accd83f0e63d522f6ee1876637ed86cf952575cc
Merge: 242942b d1d8a82
Author: sabbas <syed.k.abbas1988@gmail.com>
Date:   Tue Aug 15 06:20:46 2017 -0500
Merge branch 'master' into port-proverb-exercise-from-javascript
commit d1d8a82fcc0d3feec1734138778fb92a87230b4b
Author: Syed Abbas <syed.k.abbas1988@gmail.com>
Date:   Thu Aug 10 14:02:19 2017 -0500
Add exercise run-length-encoding (#335)
commit 242942b035fedde096a92d296cf5988ff0ec2c15
Author: sabbas <syed.k.abbas1988@gmail.com>
Date:   Thu Aug 10 07:09:53 2017 -0500
Port Proverb Exercise from JavaScript Track
This is …

port proverb exercise from javascript track

---

exercises/queen-attack/example.js
exercises/queen-attack/queen-attack.spec.js

I noticed that this test will pass as long as the `Queens` constructor is implemented, because the assertion is in the catch. Since it was a quick fix, I didn't make an issue.

Queen attack: force test failure when exception is not thrown

---

exercises/simple-cipher/simple-cipher.spec.js

The test case was changed in both tracks with unrelated changes. This commit merges the two logically:
#347 
https://github.com/exercism/javascript/pull/401
The according sync-PR in JavaScript track:
https://github.com/exercism/javascript/pull/403

Synchronizing EcmaScript <-> Javascript test for simple-cipher

---

README.md

Node LTS is currently 6.11 but stating a version number here will become outdated so I think recommending the latest LTS is safer

Fix link and remove incorrect version

---

docs/INSTALLATION.md

Per the suggestion in issue [#285](https://github.com/exercism/ecmascript/issues/285), updated the beginning section describing the different options to install Node.
Closes #285

Reword Node Installation Options

---

config.json
exercises/bowling/README.md
exercises/bowling/bowling.spec.js
exercises/bowling/example.js
exercises/bowling/package.json

I noticed there was a stale PR for porting this exercise and decided to give it a shot.
I think I covered everything mentioned in #332, but let me know if I missed anything or you have any suggestions for improvement! I tried to keep everything as close to the original JavaScript exercise as possible, just updating things to ES6 syntax where it seemed appropriate.
I also noticed that the description of the code in the Requirements section doesn't exactly match the interface expected by the specs, but I decided to leave it as-is for now.

port exercise bowling from JS track - fixes #332

---

config.json
exercises/protein-translation/README.md
exercises/protein-translation/example.js
exercises/protein-translation/package.json
exercises/protein-translation/protein-translation.spec.js

Same comment as for PR #364, I did some kind of manual rebase so that there shouldn't be any conflicts. Looking forward to having your comments.

Protein translation

---

config.json
exercises/transpose/README.md
exercises/transpose/example.js
exercises/transpose/package.json
exercises/transpose/transpose.spec.js

Thanks to @shybyte's solution.

Transpose Exercise Fixed

---

CONTRIBUTING.md
README.md

The contributing guidelines linked in the README were irrelevant. I removed the section and added the correct link to a more conventional CONTRIBUTING.md file. 
This will increase the community rating on the Insights page too.

Please review; Update contributing guide

---

Makefile
README.md
exercises/change/package.json
exercises/protein-translation/package.json
exercises/rectangles/package.json
exercises/rotational-cipher/package.json
exercises/spiral-matrix/package.json
exercises/transpose/package.json

Closes #303 
Updates Makefile for CI, so that all exercise `package.json` files are checked against the main `package.json` file.  If they are not identical, the build fails.
NB: since the `copy-assignment` task _already_ copies the main `package.json` to a given exercise, and the contributors are meant to run `make test`, all files _should_ be updated before submission, so I did not make a separate task just to copy the `package.json` files as was discussed in #303.
Bonus: Looks like we had many exercises that did not have matching `package.json` files.  This caused the build to fail at first, so I guess the script is working...

Update makefile to check package.json on CI

---

exercises/bob/.meta/description.md
exercises/bob/README.md

We need to be able to regenerate the exercise READMEs without
causing the README for 'bob' to drift.
A new rule has been added to the upstream problem specification,
and this hasn't yet been implemented in this track.
I only realized after submitting https://github.com/exercism/ecmascript/issues/391 that I needed to regenerate the exercise READMEs in order to move forward with https://github.com/exercism/meta/issues/94, which would cause 'bob' to get out of sync.
Since this is a purely janitorial change, I am going to go ahead and merge it when the build passes.
I'm adding a note to the ambiguity issue about deleting this file when the test suite gets updated.

bob: Lock problem description to match current implementation

---

exercises/simple-cipher/simple-cipher.spec.js

_NB: I've made this same PR in the JavaScript track (https://github.com/exercism/javascript/pull/538) and TypeScript track (https://github.com/exercism/typescript/pull/186) and I'm making the rounds. I'd love to see this consistent across all the JS tracks!_
The README for this exercise describes generating random keys consisting of 100+ lowercase letters, but the only constraint enforced by the tests is that it must contain only lowercase letters. One could pass this constraint by simply defaulting the key to a hard-coded string like `lolnotrandom`.
This PR adds tests to enforce that keys are randomly generated (at least a simple test that if you generate 2 keys back to back, they are not the same key), and that they are at least 100 characters long.

Simple Cipher: Add tests for random key generation, 100+ character length

---

.travis.yml

Looks like `npm-ci` is meant to be used in CI environments.
https://docs.npmjs.com/cli/ci
Also we don't need the `--no-save` flag with this.

Use npm-ci instead of npm-install

---

exercises/robot-simulator/example.js
exercises/robot-simulator/robot-simulator.spec.js

Solves #407:
The robot-simulator exercise includes a test that should fail if in case of an invalid argument
- no error message is thrown
- a wrong message is thrown
In fact, the test only fails in the latter case. So I fixed that. I didn't touch anything else but I really wonder why anybody would throw a String instead of an Error object.

robot-simulator: fix test that didn't fail if nothing was thrown

---

config.json
exercises/reverse-string/README.md
exercises/reverse-string/example.js
exercises/reverse-string/package.json
exercises/reverse-string/reverse-string.spec.js

A port of the JS 'reverse-string' challenge as requested in #417 
Things I did to port:
- Converted `it` to `test`
- Added exercise to config.json and change its UUID
- Updated tests and example to match new linter
- Copy ecmascript `setup`,`requirements` and `making the test suite pass` sections into exercise README.md

Port reverse-string from javascript track

---

exercises/word-search/word-search.spec.js

The problem is that the grid contents two `java` words but it should have just one.
The first one is: `{ start: [1, 1], end: [4, 4] }`
The second one is: `{ start: [11, 2], end: [11, 5] }`
```javascript
const grid = [
"jefblpepre",
"camdcimgtc",
"oivokprjsm",
"pbwasqroua",
"rixilelhrs",
"wolcqlirpc",
"screeaumgr",
"alxhpburyi",
"jalaycalmp",
"clojurermt",
"xjavamtzlp"
];
```
The test fails if your implement finds the first `java` first.

Fix word-search test

---

config.json

In favour of `all-your-base`. Ref: https://github.com/exercism/problem-specifications/issues/279
We did this in https://github.com/exercism/ecmascript/pull/250 and was later reformatted in https://github.com/exercism/ecmascript/pull/321/files. I guess later while adding topics, the deprecated key was removed.
I have also removed `unlocked-by: binary` for `all-your-base` - since `binary` is deprecated now.

Deprecate binary, trinary, octal and hexadecimal

---

config.json

Hi, I'm working my way through the ECMAScript track and just got done with the Space Age exercise, it looks like Prime Factors isn't being unlocked for me in the track. Looking at the `config.json`, it looks like the `binary` exercise before Prime Factors is marked as `"core": true` but also is `"deprecated": true`. This PR is to remove `binary` from core and update the others deprecated exercises to not be unlocked by binary (which `configlet lint .` will error on)

Remove core from deprecated exercise

---

exercises/rna-transcription/rna-transcription.spec.js

This PR adds a new spec for an empty rna sequence, which was just added to the `canonical-data.json` the other day.
https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json

Adds empty RNA sequence spec

---

exercises/armstrong-numbers/armstrong-numbers.spec.js
exercises/armstrong-numbers/example.js

- Change default import `ArmstrongNumbers` to named import `{ validate }`.
- Change calls to imported function from `ArmstrongNumbers.validate(input)` to the simpler `validate(input)`.
- Remove default export statement from example.js.
- Change export statement in example.js to a named export.

Fix unit tests for Armstrong Number exercise in accordance with issue #436:

---

exercises/collatz-conjecture/collatz-conjecture.spec.js
exercises/collatz-conjecture/example.js

- Change default import `steps` to named import `{ steps }`.
- Change export statement of example.js from `export default (n) => {` to `export const steps = (n) => {`.

Fix unit tests for Collatz Conjecture exercise in accordance with issue #436:

---

exercises/accumulate/accumulate.spec.js
exercises/accumulate/example.js

As per issue #436:
- Change default import `accumulate` to named import `{ accumulate }`.
- Change export statement of example.js from a default to a named export.

Fix unit tests for Accumulate exercise

---

exercises/alphametics/alphametics.spec.js
exercises/alphametics/example.js

As per issue #436:
- Change default import `solve` to named import `{ solve }`.
- Change export statement of example.js from a default to a named export.

Fix unit tests for Alphametics exercise

---

exercises/atbash-cipher/atbash-cipher.spec.js
exercises/atbash-cipher/example.js

As per issue #436:
- Change default import `atbash` to named import `{ encode }`.
- Change export statement of example.js from a default to a named export.

Fix unit tests for Atbash Cipher exercise

---

exercises/bracket-push/bracket-push.spec.js
exercises/bracket-push/example.js

As per issue #436:
- Change default import `bracket` to named import `{ bracketPush }`.
- Change all function calls in the test suite to `bracketPush`'
- Change export statement of example.js from a default to a named export.

Fix unit tests for Bracket-push exercise

---

exercises/leap/example.js
exercises/leap/leap.spec.js

Change the unit tests for the Leap exercise to accept a named function import instead of a default named import as per issues #274 and #436:
- Change default import `Year` to named import `{ isLeap }`.
- Remove unnecessary `const year = new Year(...` calls.
- Change `year.isLeap()` calls to `isLeap(XXXX)`.
- Rewrite example.js file to export a single named function.

Fix unit tests for Leap exercise

---

exercises/rna-transcription/example.js
exercises/rna-transcription/rna-transcription.spec.js

Change the unit tests for the RNA Transcription exercise to accept a named function export instead of a default class export as per issues #274 and #436:
- Change default class import `Transcriptor` to named function import `{ toRna }`.
- Remove unnecessary `const transcriptor = new Transcriptor();` line.
- Change `transcriptor.toRna(...` calls to `toRna(...`.
- Redesign example.js file to export a single named function.

Fix unit tests for RNA Transcription exercise

---

exercises/pangram/example.js
exercises/pangram/pangram.spec.js

Change the unit tests for the Pangram exercise to accept a named function export instead of a default class export as per issues #274 and #436:
- Change default class import `Pangram` to named function import `{ isPangram }`.
- Remove unnecessary `const pangram = new Pangram(...` lines.
- Change `pangram.isPangram(...` calls to `isPangram(...`.
- Redesign example.js file to export a single named function.

Fix unit tests and example for Pangram exercise

---

exercises/bob/bob.js
exercises/bob/bob.spec.js
exercises/bob/example.js

Change the unit tests for the Bob exercise to accept a named function export instead of a default class export as per issues #274 and #436:
- Change default class import `Bob` to named function import `{ hey }`.
- Remove unnecessary `const bob = new Bob();` line.
- Change `bob.hey(...` calls to `hey(...`.
- Redesign example.js and bob.js files to export a single named function.

Fix unit tests for Bob exercise

---

exercises/gigasecond/example.js
exercises/gigasecond/gigasecond.spec.js

Change the unit tests for the Gigasecond exercise to accept a named function export instead of a default class export as per issues #274 and #436:
- Change default class import `Gigasecond` to named function import `{ gigasecond }`.
- Change `new Gigasecond(...` calls to `gigasecond(...`.
- Change `gs.date()` calls to `gs` calls.
- Remove mutation test which is no longer relevant.
- Redesign example.js file to export a single named function.

Fix unit tests for Gigasecond exercise

---

exercises/simple-cipher/example.js
exercises/simple-cipher/simple-cipher.spec.js

Change the example for the Simple Cipher exercise to accept a named class export instead of a default class export as per issues #274 and #436, and expand unit tests as per issue #445:
- Refactor example.js to export a named class.
- Change default import `Cipher` to named import `{ Cipher }`.
- Add unit tests to include checks for non-alphabet characters.

Fix unit tests and example for Simple Cipher exercise

---

exercises/space-age/example.js
exercises/space-age/space-age.spec.js

Change the example for the Space Age exercise to accept a named class export instead of a default class export as per issue #436:
- Refactor example.js to export a named class.
- Change default import `SpaceAge` to named import `{ SpaceAge }`.

Fix unit tests and example for Space Age exercise

---

exercises/secret-handshake/example.js
exercises/secret-handshake/secret-handshake.spec.js

Change the unit tests for the Secret Handshake exercise to accept a named 
function export instead of a default class export as per issues #274 and #436:
- Change default class import `SecretHandshake` to named function import `{ secretHandshake }`.
- Remove unneeded `new SecretHandshake(` calls.
- Change `handshake.commands(` calls to `secretHandshake(` calls.
- Redesign example.js file to export a single named function.

Fix unit tests and example solution for Secret Handshake exercise

---

.eslintignore
exercises/accumulate/example.js
exercises/acronym/example.js
exercises/anagram/anagram.spec.js
exercises/anagram/example.js

Issue: https://github.com/exercism/javascript/issues/480
Addresses the linting errors in:
- `accumulate`
- `acronym`
- `anagram`
As requested, I kept it to 3 exercises, even though these are pretty small. (Alphabetically speaking, I skipped a couple where the fixes will be a little more involved.)
If everything here is acceptable, I am happy to submit more going forward--if not, I can update and re-submit.

Linting fixes for 3 exercises

---

.eslintignore
exercises/wordy/example.js

Wordy lint fix associated to #480.
I got into a little bit of a rabbit hole in fixing the linting errors here. 
There was an issue with using ++, in finding ways to eliminate the use of this, I found a bug, the solution was doing an extra loop over the arrays, I think it was implemented with the perception that arrays are 1-indexed not zero  (minor fix). 
- Also, deleted unwanted code: there was a prototype method defined on the String class that wasnt needed.
- Renamed variables.

fix: Eslint errors in wordy

---

exercises/word-search/example.js
exercises/word-search/word-search.spec.js

word search lint fix associated to #480.
All lint issues fixed for this exercise aside for the below error in the example.js: 
`52:3  error  iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations  no-restricted-syntax`
Switching out the for...in loop with a forEach loop makes the tests fail for some unknown reason.
Still investigating but was considering if I should just refactor this solution instead of trying to find the issue.

fix lint error for word search

---

exercises/two-fer/example.js
exercises/two-fer/two-fer.spec.js

closes #503:
Change default import `twoFer` to named import `{ twoFer }`.
Change export statement of `example.js` from a default to a named export.

Change two-fer exercise to use named exports

---

.eslintignore
exercises/bob/bob.js
exercises/bob/bob.spec.js
exercises/bob/example.js

Per #480, fix the following lint errors for the bob exercise:
```
/home/eric/code/javascript/exercises/bob/bob.js
7:20  error  Expected parentheses around arrow function argument having a body with curly braces  arrow-parens
11:2   error  Missing semicolon                                                                    semi
/home/eric/code/javascript/exercises/bob/bob.spec.js
3:23  error  Block must not be padded by blank lines  padded-blocks
46:24  error  Strings must use singlequote             quotes
/home/eric/code/javascript/exercises/bob/example.js
5:20  error  Expected parentheses around arrow function argument having a body with curly braces  arrow-parens
19:2   error  Missing semicolon                                                                    semi
```

Lint bob exercise

---

.eslintignore
exercises/hamming/example.js
exercises/hamming/hamming.spec.js

Per #480, fix the following lint errors for the hamming exercise:
```sh
/home/eric/code/javascript/exercises/hamming/example.js
1:15  error  Block must not be padded by blank lines               padded-blocks
3:10  error  Expected 'this' to be used by class method 'compute'  class-methods-use-this
13:12  error  Unary operator '++' used                              no-plusplus
15:9   error  Unary operator '++' used                              no-plusplus
22:1   error  Block must not be padded by blank lines               padded-blocks
```
Note:
1. The `while` loop is replaced with `for` to allow easier replacement from `++` to `+=`.
2. The error "Expected `this` to be used by class method `compute`" is addressed by exporting the standalone `compute` function instead of exporting an entire …

Fix eslint errors in hamming exercise

---

.eslintignore
exercises/simple-cipher/example.js
exercises/simple-cipher/simple-cipher.spec.js

Per #480, fix the following eslint errors in `simple-cipher` exercise: 
```
/home/ericode/javascript/exercises/simple-cipher/example.js
12:47  error  'mod' was used before it was defined          no-use-before-define
13:7   error  Assignment to function parameter 'outText'    no-param-reassign
13:24  error  'mod' was used before it was defined          no-use-before-define
18:26  error  Unexpected mix of '%' and '+'                 no-mixed-operators
18:30  error  Unexpected mix of '%' and '+'                 no-mixed-operators
20:21  error  Block must not be padded by blank lines       padded-blocks
22:14  error  Unexpected space before function parentheses  space-before-function-paren
/home/eric/code/javascript/exercises/simple-cipher/simple-cipher.spec.js
44:7   error    Do not use …
```

Lint simple-cipher exercise

---

exercises/secret-handshake/secret-handshake.spec.js

The spec file for `secret-handshake` passes hexadecimal values to the `secretHandshake()` constructor asked of the user.
Per the problem specification, passes decimal values which resolve to the binary values which [should] give the expected output.
Fixes #509

Update secret-handshake spec file with decimal test values

---

.eslintignore
exercises/isogram/example.js

As per #480
```sh
$ npm run lint
/exercises/isogram/example.js
1:30  error  Block must not be padded by blank lines  padded-blocks
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially fixable with the `--fix` option.
```

Resolve lint issue(s) in isogram solution

---

.eslintignore
exercises/crypto-square/example.js

Per #480, it fixes the following errors on the crypto-square exercise:
```
.../javascript/exercises/crypto-square/example.js
24:5   error  Split 'const' declarations into multiple statements  one-var
26:5   error  Split 'let' declarations into multiple statements    one-var
31:34  error  Unary operator '++' used                             no-plusplus
35:42  error  Unary operator '++' used                             no-plusplus
38:46  error  Unary operator '++' used                             no-plusplus
44:37  error  Unary operator '++' used                             no-plusplus
```

Lint crypto-square exercise

---

exercises/acronym/acronym.spec.js
exercises/acronym/example.js

per #436, modify acronym exercise:
1. Change default export to named export, along with some linting.
1. Change default import `Acronym` to named import `{ parse }`.
1. Change calls to imported function from `Acronym.parse(input)` to the simpler `parse(input)`.

Acronym: change default export to named export

---

.eslintignore
exercises/robot-simulator/example.js
exercises/robot-simulator/robot-simulator.spec.js

Per #480, this fixes the following errors on the robot-simulator exercise:
```
.../javascript/exercises/robot-simulator/example.js
64:15  error  Expected 'this' to be used by class method 'instructions'  class-methods-use-this
65:35  error  Expected to return a value at the end of arrow function    array-callback-return
65:35  error  Expected to return a value at the end of arrow function    consistent-return
68:14  error  Unnecessary 'else' after 'return'                          no-else-return
87:1   error  Block must not be padded by blank lines                    padded-blocks
91:1   error  Too many blank lines at the end of file. Max of 0 allowed  no-multiple-empty-lines
.../javascript/exercises/robot-simulator/robot-simulator.spec.js
1:19  error  './robot-simulator' imported …
```

Lint robot-simulator exercise

---

.eslintignore
exercises/circular-buffer/circular-buffer.spec.js
exercises/circular-buffer/example.js

For issue #480 
Fixes the following lint errors in the circular-buffer exercise:
```
javascript/exercises/circular-buffer/circular-buffer.spec.js
1:28  error  './circular-buffer' imported multiple times  import/no-duplicates
2:51  error  './circular-buffer' imported multiple times  import/no-duplicates
javascript/exercises/circular-buffer/example.js
1:1   error  Split 'let' declarations into multiple statements                      one-var
28:3   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions
38:15  error  Arrow function should not return assignment                            no-return-assign
```
Also removes the bowling and change exercises from `.eslintignore`, but they did not actually cause any lint errors.
Thanks for your time!

lint exercises: bowling, change, circular-buffer

---

config.json
exercises/high-scores/README.md
exercises/high-scores/example.js
exercises/high-scores/high-scores.spec.js
exercises/high-scores/package.json

New problem specification added in exercism/problem-specifications#1378

high-scores: Implement exercise

---

.eslintignore
exercises/complex-numbers/complex-numbers.spec.js
exercises/complex-numbers/example.js
exercises/etl/etl.spec.js
exercises/gigasecond/example.js

For issue #480 
Bundled up a few simple ESLint fixes in one convenient PR.
complex-numbers:
```
javascript/exercises/complex-numbers/complex-numbers.spec.js
45:1  error  Trailing spaces not allowed  no-trailing-spaces
javascript/exercises/complex-numbers/example.js
1:36  error  Block must not be padded by blank lines  padded-blocks
19:58  error  Expected newline before ')'              function-paren-newline
27:64  error  Expected newline before ')'              function-paren-newline
41:48  error  Expected newline before ')'              function-paren-newline
```
etl:
(I actually don't love these changes, but they make ESLint happy)
```
javascript/exercises/etl/etl.spec.js
13:22  error  Expected a line break after this opening brace   object-curly-newline
13:53  error  Expected a line …
```

Lint fixes for exercises: complex-numbers, etl, gigasecond

---

.eslintignore
exercises/run-length-encoding/example.js

Per #480, fix the following lint errors for the run-length-encoding exercise:
```
/home/eric/code/javascript/exercises/run-length-encoding/example.js
5:1  error  Expected indentation of 4 spaces but found 6  indent
```

lint run-length-encoding exercise

---

exercises/alphametics/example.js
exercises/difference-of-squares/difference-of-squares.spec.js
exercises/flatten-array/example.js
exercises/forth/example.js
exercises/minesweeper/example.js
exercises/proverb/proverb.spec.js
exercises/spiral-matrix/spiral-matrix.spec.js
exercises/sublist/example.js

Clean up indent errors as part of issue #480
- Fix 30 cases of ESLint issue `indent`.
As an added bonus, I've been able to remove the ISBN Identifier and Matrix exercises from .eslintignore.

Clean up indent errors

---

.eslintignore
exercises/hexadecimal/example.js
exercises/kindergarten-garden/example.js
exercises/luhn/example.js
exercises/rotational-cipher/example.js
exercises/transpose/example.js

Clean-up of small, one-line ESLint errors as part of issue #480:
- Hexadecimal: fix `no-plusplus` error.
- Kindergarten Garden: fix `no-shadow` error.
- Luhn: fix `no-param-reassign` error.
- Rotational Cipher: fix `operational-linebreak` error.
- Transpose: fix `implicit-arrow-linebreak` error.

Clean-up of ESLint errors

---

exercises/list-ops/example.js
exercises/list-ops/list-ops.spec.js

`List.concat` in the JavaScript track is just a duplicate of `List.append`.
This PR makes it more useful by expecting a list of lists as the argument instead, aligning it with, for example, the [test suite in the Python track](https://github.com/exercism/python/blob/master/exercises/list-ops/list_ops_test.py#L26).

`concat` should be applied to a list of lists.

---

exercises/all-your-base/all-your-base.spec.js
exercises/all-your-base/example.js

Per #436, change from default export to named export.  In the
all-your-base exercise, export just `convert`.  The corresponding tests
can consume like `convert(args)`.

Use named export for all-your-base exercise

---

exercises/simple-linked-list/example.js
exercises/simple-linked-list/simple-linked-list.spec.js

This exercise was implemented in a way that really deviated from the README in the problem-specifications repo.
The README is very simple in its requirements:
1. Implement List and Element classes.
2. Implement the List class so that it can:
a) be reversed
b) return an array of element values
c) accept an array as initial data
There's nothing about `pop`, `shift`, etc. The existing implementation is relatively complicated compared to these requirements, as is the test suite, which requires validation that isn't specified in the metadata.
This exercise is already a bit of a mind-bender without all the extra complications-- let's make it simpler by focusing on the core problem.  There are two other exercises that focus on list implementations, so I think we're pretty well covered here.

Update example and tests for simple-linked-list

---

exercises/darts/darts.spec.js
exercises/darts/example.js

In reference to #436, changes the default export in the Darts exercise to a named export.
In `darts/example.js`
- Change export from default to named
In `darts/darts.spec.js`
- In import, specify named export from `darts/example.js`

Modify Darts exercise to use named exports

---

exercises/reverse-string/example.js
exercises/reverse-string/reverse-string.spec.js

In reference to #436, changes the default export in the Reverse String exercise to a named export.
In `reverse-string/example.js`
- Change export from default to named
In `reverse-string/reverse-string.spec.js`
- In import, specify named export from `reverse-string/example.js`

Modify Reverse String exercise to use named exports

---

exercises/largest-series-product/example.js
exercises/largest-series-product/largest-series-product.spec.js

Per #436, convert default export to named export for largest series
product exercise. Change from class style `new
Series(numberString).largestProduct(size)`
to function `largestProduct(numberString, size)` since there is no need to
keep state.
The diffs look a little crazy due to the change in indentation and extraction of various methods from `Series`.  Details:
1. `Series.getDigits` is extracted into standalone function `getDigits`
1. `Series.slices(sliceSize)` is extracted into standalone function `slices(digits, sliceSize)`.  The additional `digits` argument replaces the use of `this.digits`.
1. `Series.largestProduct(size)` is extracted into standalone function `largestProduct(numberString, size)`.  The additional `numberString` argument replaces the use of `this.numberString`.  In …

Use named export for largest-series-product (after linting)

---

.eslintignore
exercises/flatten-array/example.js
exercises/flatten-array/flatten-array.spec.js

As per issue #480:
- Fix all `max-len` ESLint errors in flatten-array.spec.js file.
- Remove flatten-array from .eslintignore file.

Fix ESLint errors in Flatten Array test script

---

.eslintignore
exercises/minesweeper/example.js
exercises/minesweeper/minesweeper.spec.js

per #480, fix the following lint errors in minesweeper exercise:
```
/home/eric/code/javascript/exercises/minesweeper/example.js
15:11  error  Expected 'this' to be used by class method 'annotate'     class-methods-use-this
16:9   error  'noDataPresent' was used before it was defined            no-use-before-define
22:12  error  'stringify' was used before it was defined                no-use-before-define
23:1   error  Line 23 exceeds the maximum line length of 100            max-len
23:60  error  'cellToMineOrCount' was used before it was defined        no-use-before-define
31:4   error  Trailing spaces not allowed                               no-trailing-spaces
33:10  error  'countAdjacentMines' was used before it was defined       no-use-before-define
33:50  error  Strings must use …
```

lint minesweeper exercise

---

.eslintignore
exercises/ocr-numbers/example.js
exercises/ocr-numbers/ocr-numbers.spec.js

As per issue #480:
- Fix all ESLint errors in ocr-numbers.spec.js file.
I have NOT removed the OCR Numbers entry in .eslintconfig as the example,js file has other errors which require non-trivial fixes.

Fix ESLint errors in OCR Number test script

---

exercises/minesweeper/example.js
exercises/minesweeper/minesweeper.spec.js

per #436, change default export to named export.  The test code now
imports and consumes differently.  Also note the `class` structure was
unnecessary from the example solution, so just export the `annotate`
function directly instead.
```js
// before
import Minesweeper from './minesweeper'
Minesweeper.annotate(...) // example usage
// after
import { annotate } from './minesweeper'
annotate(...) // example usage
```

Minesweeper: change default export to named export

---

.eslintignore
exercises/meetup/example.js

per #480, lint meetup exercise, primarily addressing `no-use-before-define`,
`no-param-reassign` lint errors, along with others:
```sh
/home/eric/code/javascript/exercises/meetup/example.js
2:22  error  'getCandidates' was used before it was defined             no-use-before-define                                                                                                                                                                         
5:3   error  Assignment to function parameter 'which'                   no-param-reassign
8:11  error  'find' was used before it was defined                      no-use-before-define
12:5   error  Assignment to function parameter 'which'                   no-param-reassign
12:13  error  Missing radix parameter …
```

Lint meetup exercise

---

exercises/roman-numerals/example.js
exercises/roman-numerals/roman-numerals.spec.js

As someone new to Javascript, I have been modeling my exercise solutions after the stub for `hello-world`. When I encountered this exercise, this was the first exercise  I saw that did not use named imports (a concept I was unaware of at the time), so I was getting compile output that I could not make sense of.
I finally figured out my issue when I came here and saw #572, covering the same issue for `scrabble-score`.

roman-numerals: use named import

---

.eslintignore
exercises/scrabble-score/example.js
exercises/scrabble-score/scrabble-score.spec.js

per #436, change default export to named export for exercise `scrabble-score`.  Also, remove
exericse's entry in eslintignore (no lint errors).

scrabble-score: change default export to named export

---

exercises/matrix/example.js
exercises/matrix/matrix.spec.js

Per #436 , for `matrix` exercise, change from default to named export.

matrix: change from default to named export

---

exercises/raindrops/example.js
exercises/raindrops/raindrops.spec.js

Similar in nature to #567, but for the `raindrops` exercise. There is no stateful information used in this exercise, so a class-based implementation is not necessary.

raindrops: convert to function

---

package-lock.json

Update 8 transititve dependencies that all use merge.
Merge has the following CVE and NPM audit advisory attached. Although we are not particularly vulnerable (no random jest usage), and the students aren't either (no random / other-user provided jest usage), this should be patched regardless.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-16469
https://www.npmjs.com/advisories/722

Patch for CVE-2018-16469

---

exercises/space-age/example.js
exercises/space-age/space-age.spec.js

* Rather than having multiple methods for each planet, just take it as input - makes the solution a lot simpler.
* Also properly adheres to the [canonical tests](https://github.com/exercism/problem-specifications/blob/master/exercises/space-age/canonical-data.json).
* Removes the last extra test to check for reassigning of seconds - which is not in canonical data.

[Space-Age] - Change API to take planet as input

---

.gitattributes
bin/generate-config-tree
bin/print-config-tree
config.json

This PR is the result of work being done to structure the exercises in a track according to a predefined methodology (this work is not finished). This first step (of many rounds) attempts to remove *Math* and *DIY* exercises from the core track, and fix obvious problems with the sequence of the existing core exercises. The result is as follows:
(Taken the format from https://github.com/exercism/csharp/pull/740, thanks @ErikSchierboom!)
```` 
Core (matches config.json) of this track:
- hello-world (1)
- leap (1)
- gigasecond (1)
- rna-transcription (2)
- space-age (2)
- pangram (2)
- matrix (3)
- bob (4)
- pascals-triangle (4)
- linked-list (5)
- grade-school (5)
- list-ops (6)
- robot-name (6)
- simple-cipher (6)
- wordy (7)
- secret-handshake (6)
core
----
├─ hello-world
│  └─ two-fer …
```

Curriculum change: track sequence (round 1)

---

bin/check_student_submission.sh

This Bash script aims to assist mentors by automating the process of pulling student down and running unit tests on them.  It makes quite a few assumptions about the mentors set-up, so it's currently quite fragile, but with those caveats in mind it appears to be working quite well.

Add Bash script for running unit tests on student sibmissions

---

bin/lint_all.sh

As per a request on the #toolmakers channel from @SleeplessByte on the Exercism Slack group, I'm submitting a Bash script that hides .eslintignore, runs ESLint on the repo and then restores ESLint.  This is intended to be used by contributors working on issues #480.
This is lightly tested but seems to work well enough as-is.

Add Bash script to facilitate running ESLint

---

bin/run_example.sh

This is a Bash script for running tests on example.js files.
In a typical exercise directory, there is a spec file and and example file, which cannot be directly tested.  The spec file has most of the tests disabled while the example file has the wrong name.  To test it, you have to change all cases of `xtest` to `test` in the spec file and move/rename the example to <<exercise-name>>.js.  Once tested, you then need to restore the files to their original state.  This script aims to automate that process.
Please note that there are some edge cases that have not been addressed yet.  The script assumes that Node is install, that Jest is installed locally (not globally), and that you are in an exercise directory.  I've not fully tested the consequences of these assumptions being wrong.  From …

Add Bash automation script for running tests on example.js files

---

exercises/leap/leap.spec.js

I came across a leap solution which returned `"Leap Year"` string in place of true. This works with existing tests which check `truthy`/`falsy`. I think it is better to check for actual values rather than relying on weird coercion.

Use exact boolean values in leap tests rather than truthy and falsy

---

exercises/simple-cipher/simple-cipher.spec.js

I just come across a solution for the "Simple Cipher" exercise from a student, which could encode messages longer than the key but failed to _decode_ messages longer than the key, and yet, because we haven't a test to cover this, all tests would pass giving an illusion of correctness.
This pull request adds a test to also check that a message longer than the key can be decoded.
Correspondent problem specifications PR: exercism/problem-specifications#1460.

simple-cipher: add test to check that messages longer than the key can be decoded.

---

exercises/palindrome-products/example.js
exercises/palindrome-products/palindrome-products.spec.js

add named export to palindrome products

---

exercises/linked-list/example.js

This PR updates the `example.js` code to be more reasonable. The `head` of the 
list is now also the front, and the `tail` of the list is now also the back. 
This matches the explanation in [this article](https://hackernoon.com/the-little-guide-of-linked-list-in-javascript-9daf89b63b54) and the readme.md of this exercise.
Fixes #629

#629 Linked List fix head/tail semantics

---

exercises/hamming/example.js
exercises/hamming/hamming.spec.js

Updating hamming test cases to match [this commit (v2.2.0)](https://github.com/exercism/problem-specifications/commit/4c453c8b9c58a8b68828d7e44c95bfcfc754507e#diff-518015f3667d81da2d3e79292ed7ad5b) and [this commit (v2.3.0)](https://github.com/exercism/problem-specifications/commit/41196719e96c949377d1dc7b5b1cea51d4ad62a4#diff-518015f3667d81da2d3e79292ed7ad5b)

update hamming to v2.3.0

---

.travis.yml

Latest travis breaks for node v11.11 with jest: https://github.com/facebook/create-react-app/issues/6591

Use LTS instead of latest Node on Travis

---

exercises/palindrome-products/example.js
exercises/palindrome-products/palindrome-products.spec.js

palindrome-products: update tests to v1.2.0

---

exercises/robot-name/example.js
exercises/robot-name/robot-name.js
exercises/robot-name/robot-name.spec.js

According to the instructions, you may never generate a name that has already been used. Using random makes this improbable, but not impossible. This changes the final test so that a different approach is required to satisfy the entire exercise.
This is in line with the ruby tests (even though those have issues).

robot-name: change optional test to enforce better implementation

---

docs/ABOUT.md
docs/INSTALLATION.md
docs/SNIPPET.txt
docs/TESTS.md

- Add links to the green page of node and browsers
- Update babel text to use babel 7's preset env (#636)
- Limit to 80 character width: Normalize these line endings which were sometimes capped at 85, sometimes at 80 and somtimes not at all.
- Update snippet to work with hello-world test: The old class implementation no longer is relevant.

Documentation: cleanup, links to green pages and snippet update

---

exercises/rna-transcription/example.js
exercises/rna-transcription/rna-transcription.spec.js

Matching the data on [28 July 2018](https://github.com/exercism/problem-specifications/blob/294c831e290670d2932365754317e92f09baacbc/exercises/rna-transcription/canonical-data.json).

Sync rna-transcription to 1.3.0

---

config.json
exercises/resistor-color/.eslintrc
exercises/resistor-color/README.md
exercises/resistor-color/babel.config.js
exercises/resistor-color/example.js
exercises/resistor-color/package.json
exercises/resistor-color/resistor-color.spec.js

Problem spec PR: https://github.com/exercism/problem-specifications/pull/1457
Closes #640

Add exercise: resistor-color

---

config.json
exercises/two-fer/example.js
exercises/two-fer/two-fer.spec.js

And make sure we expect an optional argument, instead of passing in null, requiring boolean logic.
Fixes #639

Promote two-fer to core and sync to 1.2.0

---

config.json
exercises/resistor-colors/.eslintrc
exercises/resistor-colors/README.md
exercises/resistor-colors/babel.config.js
exercises/resistor-colors/example.js
exercises/resistor-colors/package.json
exercises/resistor-colors/resistor-colors.spec.js

Problem spec PR: https://github.com/exercism/problem-specifications/pull/1466
Closes #641

Implement resistor-colors exercise

---

Makefile

Based on https://github.com/exercism/javascript/pull/645

Add checksum for eslint config

---

exercises/grains/big-integer.spec.js

For the "Grains" exercise, the BigInt function was not being imported correctly, so the tests wouldn't run.
Also, one of the tests was testing for the .toString() function on BigInt by using coercion, but the test had "===" instead of "==".

Fix bigint tests

---

Makefile
exercises/grains/example.js

* Break Makefile tasks into smaller chunks for future modification (exercise versioning, etc).
* Fix import of `big-integer` in `grains` example solution file. Not same as #643

Refactor makefile

---

exercises/minesweeper/minesweeper.spec.js

During solving this task, I found that there is a duplicated spec in the spec file. See in the diff just one above deleted – they are the identical.
To reduce possible confusion we need to delete its copy.

Remove spec duplicate from minesweeper task specs

---

exercises/wordy/wordy.spec.js

Closes #674 
Per jest documentation, use class name as argument to test `ArgumentError` is thrown.
https://jest-bot.github.io/jest/docs/expect.html#tothrowerror

Wordy spec: Use class name as arg for `toThrow`

---

.travis.yml
package-lock.json
package.json
scripts/checksum
scripts/ci
scripts/helpers.js
scripts/lint
scripts/sync
scripts/test

Issue: https://github.com/exercism/javascript/issues/646
* No `make` dependency anymore!
* Uses [shelljs](https://github.com/shelljs/shelljs) for all shell commands. So everything is unix-like without depending on OS commands! `shelljs` gets removed while syncing to exercise dirs and while performing checksum.
* Travis job now uses these JS scripts instead.
* Next step is to streamline process, change all the docs, add contributing doc and delete Makefile.

Use JS scripts instead of Makefile

---

bin/tools/copy-package-json

Previously, the `copy-package-json` script doesn't preserve the EOL new line.

Add newline character to end of `package.json`

---

.travis.yml
package-lock.json
package.json
scripts/checksum
scripts/ci
scripts/helpers.js
scripts/lint
scripts/sync
scripts/test

Use [@babel/node](https://babeljs.io/docs/en/babel-node) to run them.
Also fix comments in scripts.

Convert scripts to ES6

---

exercises/hello-world/hello-world.spec.js
exercises/hello-world/package.json
package.json
scripts/checksum
scripts/helpers.js

* Skip package.json version when comparing checksums. This will allow us to implement versioning policy in https://github.com/exercism/javascript/issues/628.
* As a proof that this works - Sync `hello-world` exercise with canonical data `v1.1.0`.

Implement exercise versioning

---

exercises/rational-numbers/rational-numbers.spec.js

Due to float precision error. Use `toBeCloseTo` for comparing floats.
https://jestjs.io/docs/en/expect#tobeclosetonumber-numdigits
Failure on master:
```
FAIL tmp_exercises/rational-numbers.spec.js
● Exponentiation of a real number to a rational number › Raise a real number to a negative rational number
expect(received).toEqual(expected)
Expected: 0.3333333333333333
Received: 0.33333333333333337
157 |   test('Raise a real number to a negative rational number', () => {
158 |     const expected = 0.3333333333333333;
> 159 |     expect(new Rational(-1, 2).expreal(9)).toEqual(expected);
|                                            ^
160 |   });
161 |
162 |   test('Raise a real number to a zero rational number', () => {
at Object.toEqual (tmp_exercises/rational-numbers.spec.js:159:44)
```

Fix rational-numbers spec failing on some platforms

---

exercises/change/change.spec.js

As previously the tests would pass even though the error message didn't match.

Fix test cases which throw error messages.

---

exercises/simple-cipher/simple-cipher.js

As imported by the spec.js file, the class name should be `Cipher`, not `List`.

simple-cipher: Replace "List" by "Cipher" for the class name

---

exercises/simple-cipher/package.json
exercises/simple-cipher/simple-cipher.spec.js

EDIT: at first, this PR just fixed a typo. In the end we updated the test file to match the spec file mentioned in the next comment.

simple-cipher: Update tests according to the spec

---

exercises/linked-list/.meta/hints.md
exercises/linked-list/README.md
exercises/linked-list/linked-list.spec.js

The following implementation of `LinkedList.delete(value)` would pass existing tests, but is incorrect:
```Javascript
delete(value) {
let current = this.head;
while (current !== null) {
if (value === current.value) {
if (current.prev === null) {
this.head = current.next;
} else {
current.prev.setNext(current.next);
}
if (current.next === null) {
this.tail = current.prev;
} else {
current.next.setPrev(current.prev);
}
}
current = current.next;
}
}
```

linked-list: add test 'deletes only the first occurence'

---

exercises/linked-list/example.js

After https://github.com/exercism/javascript/pull/630 the notion of previous and next element was mixed up. This PR cleans this up and adapts the notation to the one in the mentoring notes (class Node, etc).

fix prev/next mix-up

---

exercises/linked-list/linked-list.spec.js

The following implementation of `delete` passes the existing test, but does not pass with the suggested changes:
```Javascript
delete(value) {
switch(value) {
case this.head.value: return this.shift();
case this.tail.value: return this.pop();
default: {
for (let current = this.head; current; current = current.next) {
if (value === current.value) {
this.remove(current);
// If this break statement were not commented out,
// this solution would pass the suggested AND
// the current forms of the test
// break;
}
}
}
}
remove(node) {
if (!node.prev) {
this.head = node.next;
} else {
node.prev.setNext(node.next);
}
if (!node.next) {
this.tail = node.prev;
} else {
node.next.setPrev(node.prev);
}
return node;
}
```

linked-list: improve test for deleting first occurence only

---

config.json

Kept "data_structures" since I find it sensible.
Needs to be added to https://github.com/exercism/problem-specifications

resolved issue #667

---

exercises/matrix/matrix.spec.js

The following wrong solution passes all previous tests but not the new one:
```
export class Matrix {
constructor(string) {
this._rows = string
.split('\n')
.map(row => row.split(' ').map(Number))
this._columns = this._rows
.map((_, i) => this._rows.map(row => row[i]))
}
get rows() {
return this._rows
}
get columns() {
return this._columns
}
}
```

Add testcase

---

exercises/matrix/matrix.spec.js

The PR  exercism/javascript/pull/718 does not reflect the latest change of exercism/problem-specifications/pull/1576 after the discussion.
Sorry for the extra work. I have to get used to the pull request workflow.

Matrix: sync with problem-specifications

---

exercises/resistor-color/package.json

This exercise is already synced with the latest canonical-data, but a version (#688) is missing.

Add resistor-color version

---

exercises/two-fer/package.json

This exercise is already synced with the latest canonical-data, but a version (#688) is missing.

Add two-fer version

---

exercises/hello-world/package.json

This exercise is already synced with the latest canonical-data, but a version (#688) is missing.

Add hello-world version

---

exercises/gigasecond/gigasecond.spec.js
exercises/gigasecond/package.json

Adds the missing test cases. Locks timezone at UTC (like before), but uses Date.parse for expected output to match problem-specifications. The comments above the test match the name of the test cases in the problem-specifications canonical data.

Sync gigasecond with 2.0.0

---

exercises/react/react.spec.js

I had a student misunderstand the callback system and **their callbacks would always run** but _only log values_ if the *callback* data had changed. The tests still pass since all the test callbacks mirror the cells data (ie, always changing when the cell changes).
A single test that had static data would have failed.
Can we fix this somehow?

Test that callbacks with static values still fire

---

config.json
exercises/resistor-color-trio/.eslintrc
exercises/resistor-color-trio/README.md
exercises/resistor-color-trio/babel.config.js
exercises/resistor-color-trio/example.js
exercises/resistor-color-trio/package.json
exercises/resistor-color-trio/resistor-color-trio.js
exercises/resistor-color-trio/resistor-color-trio.spec.js

This implements `resistor-color-duo`.

Add new exercise: resistor-color-trio

---

exercises/leap/leap.spec.js
exercises/leap/package.json

See [Leap exercise's canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/leap/canonical-data.json)
For Leap exercise:
- Sync test descriptions with canonical data
- Add missing tests
- Add version

Sync Leap exercise with v1.6.0

---

exercises/pangram/package.json
exercises/pangram/pangram.spec.js

- Sync Pangram test descriptions with [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json)
- Add version

Sync Pangram with v2.0.0

---

config.json
exercises/scale-generator/.eslintrc
exercises/scale-generator/README.md
exercises/scale-generator/babel.config.js
exercises/scale-generator/example.js
exercises/scale-generator/package.json
exercises/scale-generator/scale-generator.js
exercises/scale-generator/scale-generator.spec.js

Adding scale-generator exercise. Closes #751. 
One thing I'm not sure about is updating `config.json`. I just based it on the same entry in other tracks, not sure if there's other stuff I should consider.

add scale-generator exercise

---

scripts/lint

I noticed that the lint command `npx @babel/node scripts/test` wasn't working. I copied a fix from the test script, as helpers.js relies on the same variables for both lint and test.

fix lint file; lint command was broken

---

scripts/ci
scripts/helpers.js
scripts/stub-check

To be merged after we get all stubs.
Here's the list of exercises missing stubs:

Add CI check for stub files

---

exercises/flatten-array/example.js
exercises/flatten-array/flatten-array.js
exercises/flatten-array/flatten-array.spec.js

Use plain function instead of class on flatten-array exercise (closes https://github.com/exercism/javascript/issues/776)

use plain function for flatten-array exercise (#776)

---

exercises/sieve/example.js
exercises/sieve/package.json
exercises/sieve/sieve.spec.js

Added 2 more unit tests for the Sieve exercise (based on the problem specifications). Also updated the example so all the tests are passing for it.

Update 'Sieve' tests

---

exercises/word-count/example.js
exercises/word-count/package.json
exercises/word-count/word-count.js
exercises/word-count/word-count.spec.js

Updated tests, removed class structure and updated the example.
@tejasbubane I removed a test about handling properties of JavaScript Object’s prototype. Depending on the focus of the language track, having this test might be a good idea (however this test is not preset in the canonical data). What do you think about this, should we keep it?

sync word-count tests with canonical data version 1.4.0

---

exercises/resistor-color-duo/example.js
exercises/resistor-color-duo/resistor-color-duo.js
exercises/resistor-color-duo/resistor-color-duo.spec.js

function rename: improved descriptiveness of default exported function; created corresponding changes in test suite and examples

resistor-color-duo: rename export

---

exercises/isogram/example.js
exercises/isogram/isogram.spec.js
exercises/isogram/package.json

Added missing test: "hypothetical word with duplicated character following hyphen"

Sync Isogram tests with canonical data version 1.7.0

---

exercises/gigasecond/.meta/hints.md
exercises/gigasecond/README.md
exercises/gigasecond/gigasecond.spec.js

Adds a test to the **gigasecond** exercise make sure the input is not mutated, since there are some solutions which will pass the current test suite that will mutate the input, which is undesirable. I've now encountered at least twice while mentoring solutions that appear to be correct, but mutate the input, so it makes sense to include this case in the test suite.
Added directly here instead of the problem specifications repository, because unfortunately it's a test case that cannot be defined generically.

[gigasecond] Add a test to check that input is not mutated

---

config.json
exercises/grep/.eslintrc
exercises/grep/README.md
exercises/grep/babel.config.js
exercises/grep/data/iliad.txt
exercises/grep/data/midsummer-night.txt
exercises/grep/data/paradise-lost.txt
exercises/grep/example.js
exercises/grep/grep.js
exercises/grep/grep.spec.js
exercises/grep/package.json
scripts/helpers.js

Fixes #737 .
I was wondering about the fact that this exercise is a CLI.
Unless I missed something, it's not possible to test a file that just executes a set of instructions.
I was thinking about exporting a function that takes the pattern, the files and options as arguments like that :
```js
export default (pattern, files, options =  {}) => {}
```
Is the user supposed to use the filesystem or should I provide him the data in the files in some way ?

Add new exercise grep

---

exercises/scale-generator/package.json
exercises/yacht/package.json
package.json
scripts/helpers.js
scripts/sync

Keeps the version of the assignment when updating `package.json` files with the sync script.
Fixes a couple of exercises that were slightly inconsistent due to manual fixes.
Fixes #825.

Keep version when updating package json

---

bin/fetch-configlet

Travis builds are failing because of fetch-configlet failures, as
tracked in exercism/configlet#173. This
patch is a copy of exercism/cpp#344, and exercism/haskell#898 which
fixed the cpp and haskell track

Fix fetch-configlet script to get 'location' header

---

CONTRIBUTING.md

of CONTRIBUTING.md
Came up during https://github.com/exercism/javascript/pull/836

Add readme generation doc link in sync exercise section

---

exercises/raindrops/raindrops.spec.js

Updated raindrops tests to be in sync with canonical data.
Canonical data:
"description": "the sound for 27 is Pling as it has a factor 3",
"property": "convert",
"input": {
"number": 27
},
"expected": "Pling"
Test Spec:
test('the sound for 27 is Pling as it has a factor 3', () =>
expect(convert(35)).toEqual('PlangPlong'));
Expected:
test('the sound for 27 is Pling as it has a factor 3', () =>
expect(convert(27)).toEqual('Pling'));
Current canonical data is `1.1.0` so I did not update the `package.json`
Closes #835

Sync 'raindrops' with canonical data 1.1.0 #835

---

exercises/space-age/example.js

Across the site `Number` is generally recommended over `parse....` in mentor notes. It's mentioned in this exercise and in others, so I'm updating this example to use `Number`. If there's a specific reason to use it in this case please let me know. 
Perhaps there are more examples where this is the case.

Update space age - example.js

---

config.json

Student mentioned that this exercise had a class tag, which caused confusion. This exercise is no longer a class based exercise, therefore I've removed this tag.

Update config.json - remove class topic from space age

---

docs/INSTALLATION.md

According to Merriam-Webster:
"The apostrophe signals that something has been removed" (it is = it's).
And "its means 'of or relating to it or itself.'"

Add apostrophe to contraction it's

---

exercises/complex-numbers/complex-numbers.js
exercises/complex-numbers/complex-numbers.spec.js

Specs were failing because `abs`, `conj`, `exp` are defined as functions in the current exercise template, not getters.

Fix spec for complex-numbers exercise

---

config.json
exercises/affine-cipher/.eslintrc
exercises/affine-cipher/.npmrc
exercises/affine-cipher/README.md
exercises/affine-cipher/affine-cipher.js
exercises/affine-cipher/affine-cipher.spec.js
exercises/affine-cipher/babel.config.js
exercises/affine-cipher/example.js
exercises/affine-cipher/package.json

:sparkles: Add new exercise : Affine Cipher

---

.github/workflows/pr.ci.js.yml
exercises/grains/.meta/tests.toml
scripts/helpers.js
scripts/lint
scripts/sync

Last week, we sent a PR in which tests.toml file were added for all exercises that have canonical data. Due to an issue, the grains exercise's tests.toml file was not included. This PR adds the tests.toml file for the grains exercise.

Add tests.toml file for grains exercise

---

exercises/zipper/zipper.spec.js

improve zipper tests

---

exercises/two-bucket/two-bucket.spec.js

This PR addresses part of the problem tracked in [Issue #901](https://github.com/exercism/javascript/issues/901). A couple of test cases were added that were expected to throw yet were invoked immediately in the spec file. This PR wraps those invocations in an anonymous function.
The example solution provided does not pass the test cases as it stands and will need to be addressed in a separate PR. This is an immediate fix so the tests are working for students.

Two Bucket: fix errant tests

---

exercises/forth/.meta/tests.toml
exercises/forth/example.js
exercises/forth/forth.spec.js

This PR addresses the issue captured in [Issue 896](https://github.com/exercism/javascript/issues/896).
Since the example implementation relies on lazy evaluation when a new command is defined, the two new tests were failing because they expected the command to be evaluated immediately at the time that it's defined. To solve this, I simply try to evaluate the newly defined command but revert to lazy evaluation if it fails.

(896) forth: implement two new tests

---

exercises/queen-attack/queen-attack.js

This implementation ensures that the `blackRow` `blackColumn` `whiteRow` `whiteColumn` are defined and that the original TypeError does not happen upon testing. #938

Update queen-attack.js as per Issue #938

---

exercises/concept/elyses-transformative-enchantments/.meta/config.json
exercises/concept/elyses-transformative-enchantments/enchantments.js
exercises/concept/elyses-transformative-enchantments/enchantments.spec.js
exercises/concept/elyses-transformative-enchantments/exemplar.js

Add solution and spec files for elyses-transformative-enchantments

---

.github/dependabot.yml

This _should_ take care of dependabot PRs coming in for exercises. We don't care about that because everything is synced with the main `package.json`.

Configure dependabot for npm in the root

---

exercises/practice/circular-buffer/circular-buffer.js

The test spec file `circular-buffer.spec.js` tests the `forceWrite` method of `CircularBuffer` class.
However, the skeleton file `circular-buffer.js` provides an empty method with the name of `overwrite`.
I have renamed this method for the sake of consistency.

Fix stub for circular-buffer to match test spec

---

exercises/practice/forth/.meta/tests.toml
exercises/practice/forth/forth.spec.js

The original version of the test only checks for positive numbers.
`
if(/^\d*$/.test(functionName)) throw new Error("Invalid definition");
`
An implementation like above will work for positive numbers, but not for negative numbers.

Improve Forth test

---

config.json

This adresses the issue #982 
What's left :

Add prerequisites for practice exercises

---

concepts/arrays/.meta/config.json
concepts/arrays/about.md
concepts/arrays/introduction.md
concepts/arrays/links.json
exercises/concept/elyses-enchantments/.docs/hints.md
exercises/concept/elyses-enchantments/.docs/instructions.md
exercises/concept/elyses-enchantments/.docs/introduction.md
exercises/concept/elyses-enchantments/.meta/config.json
exercises/concept/elyses-enchantments/.meta/design.md
exercises/concept/elyses-enchantments/.meta/exemplar.js
exercises/concept/elyses-enchantments/enchantments.js
exercises/concept/elyses-enchantments/enchantments.spec.js
exercises/concept/elyses-enchantments/package.json

Related #1017 
- Add blurb for exercise name to exercise `config.json`
- Add blurb for `strings` to concept `config.json`
- Add stub design document
- Add `about.md`
- Completely rework the tests for the test-runner

[V3] Elyses Enchantments: fix everything around this exercise

---

exercises/concept/annalyns-infiltration/.docs/instructions.md
exercises/concept/errors/.docs/instructions.md
exercises/concept/freelancer-rates/.docs/instructions.md
exercises/concept/lucky-numbers/.docs/instructions.md
exercises/concept/poetry-club-door-policy/.docs/instructions.md

The `## Tasks` heading should not be in `instructions.md` files.

Remove Tasks heading from instructions.md

---

config/maintainers.json

Dear maintainers,
As we near launching V3 for Beta I'm updating the `maintainers` list. If you're tagged in this message, I've flipped your `alumnus` value to `true`, as you've been inactive for the past months. If I don't hear anything in the next seven days it will remain so.
- If you'd like to not show up on the website, please let me know
- If you'd like to stay on as a maintainer, please let me know
Naturally, if you choose to come back in the future, we always have a place for you, but I need to know who I can count on as we hurdle towards the big update and all the support required thereafter. 
A few of you have already indicated privately that you're otherwise occupied and cannot help out at the moment (which is _perfectly fine_ of course); and you can ignore this entire message. …

Mark inactive maintainers as alumnus

---

exercises/practice/clock/.docs/instructions.append.md

Came across a solution where student used `Date` class to implement `clock` exercise.

Add instructions to not use `Date` for `clock` exercise

---

docs/ABOUT.md

This breaks when parsing the markdown.

Fix invalid link

---

.github/workflows/ci.js.yml
.github/workflows/pr.ci.js.yml

Because dependabot updates actions SHA but leaves versions outdated

Remove versions for actions from workflow files

---

concepts/closures/links.json
exercises/concept/closures/.docs/hints.md
exercises/concept/closures/.docs/instructions.md

The resources in general hints wouldn't show up because nested lists are not allowed. I can't access https://whatthefork.is/closure at all. I assume it's not going back because "whatthefork" doesn't even show up as a website in my search engine, so it must have been dead for a while.

Concept exrecise review: `closures`

---

config.json
exercises/concept/fruit-picker/.meta/design.md

Includes the following fixes:
* The long name of the `increment-decrement` operator was messing up the concept tree view. "Switch" did not fit next to "While" anymore. Used a shorter name.
* Order of 2 concepts in concept list and in prerequisites was switched to see whether that improves the order in tree.
* There was a wrong slug used for `array-transformations` in some places.
* Some exercises (concept and practice) had too many or missing prerequisites or some that did not match the current target concept tree anymore. E.g. there is no "default-value" concept, it is part of the `functions` concept.

Fix some concept tree and prerequisite issues

---

exercises/practice/scale-generator/.docs/instructions.md

All scale names are rendered on the same line. The comma may not make sense in the markdown file but improves readability on the rendered page.

Add missing commas between major and minor scale names

---

concepts/errors/.meta/config.json
concepts/errors/links.json
config.json
exercises/concept/errors/.docs/instructions.md
exercises/concept/errors/.meta/config.json
exercises/concept/errors/.meta/design.md
exercises/concept/errors/.meta/exemplar.js
exercises/concept/errors/errors.js
exercises/concept/errors/errors.spec.js

This PR is to make the errors concept exercise fit the latest spec and sets it to "beta" status.
(see https://github.com/exercism/javascript/issues/1017)
It does not update the current content.

Fix Concept Exercise: Errors

---

docs/ABOUT.md

This PR just fixes some Markdown issues that I saw while I was browsing through the About section of JavaScript track. Also the link to expo is fixed as it is `expo.dev` now.

Fixed markdown issues & the link to `expo` in ABOUT.md

---

bin/check_corejs_version.sh

I thought of an easier version to check the core.js version with pure regex :)
Follow-up to https://github.com/exercism/javascript/pull/1313.

fix: Simpler core.js version check

---

exercises/practice/pythagorean-triplet/.meta/proof.ci.js
exercises/practice/pythagorean-triplet/pythagorean-triplet.spec.js

In the previous implementation the triplets function had a time complexity of O(n^3). This commit reduces it to O(n^2). I believe the current best known optimal solution for this type of problem is [O(n^2(log log n)/log ^2n)](https://en.wikipedia.org/wiki/3SUM) but in order to achieve that result we would need to make changes to this solution which would negatively impact readability/understandability. The final test still takes a long time (~16s) but I don't think that can be significantly improved for an input of that size.

reduced pythagorean-triplet's time complexity from cubic to quadratic 

---

exercises/concept/coordinate-transformation/coordinate-transformation.spec.js

The current specs allow a solution, where the memoization only
works once, i.e. for the first pair of arguments.
This CL adds specs to test if memoization respects the arguments.
Example:
```javascript
function memoizeTransform(f) {
let res;
return function (x, y) {
res = res ?? f(x, y);
return res;
}
}
```
The additional test case covers this and fails with the above
solution.

Improve concept exercise Coordinate Transformation

---

config.json
exercises/practice/promises/.meta/config.json
exercises/practice/promises/promises.spec.js

Fix #1331 
I've tested @joshgoebel  implementation of `promisify` and the specs for this function now fail correctly.
TODO :

:bug: Fix 'promises' exercise specs

---

exercises/concept/translation-service/.meta/exemplar.js

By using `.catch()` and by wrapping `this.api.request()` as a promise some of the logic can be simplified.
Also suggest removing the `.bind(this)` as complex at this stage of the learning.

Possible simplification of Translation Service exemplar

---

exercises/concept/coordinate-transformation/coordinate-transformation.spec.js

I added a test that makes sure the student's code isn't remembering all the results and only the last one. It calls the student's function with some input, different input, and then the first input again. This should require the underlying function to be called 3 times if the student's code is implemented to only remember the last result.
Fixes #1373.

Add a test to check that only the last result is remembered

---

exercises/practice/two-bucket/.meta/proof.ci.js
exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/two-bucket.spec.js

Hi, I have fixed the two-bucket solution and reverted all the `test.skip` to `xtest` in the spec.js file. Please check and let me know further issues, thanks!
Fixes #901

Fixed two-bucket solution & errant tests (#905)

---

concepts/promises/about.md
concepts/promises/introduction.md
concepts/promises/links.json
exercises/concept/translation-service/.docs/introduction.md

Added Promises content in introduction & about

---

exercises/practice/promises/.meta/proof.ci.js
exercises/practice/promises/promises.spec.js

Without these tests it's possible, easy even, to write promises that never resolve or reject when passed an empty array or no array.
fixes #1400

Tests for empty promise array and no arguments.

---

exercises/practice/palindrome-products/.meta/proof.ci.js
exercises/practice/palindrome-products/palindrome-products.spec.js

Hi, this pull request is relate to [#1398](https://github.com/exercism/javascript/pull/1398). I optimised more code based on dicussion with @joshgoebel. Thanks!

Further optimised palindrome-products solution (exercism#898)

---

exercises/concept/lasagna-master/lasagna-master.spec.js

This adds a check that, for a number of people not equal to 2, the original object is deeply equal to a clone of itself made earlier. This I think is more accurate than simply checking that the original recipe and the resulting object are not equal by reference since it is possible to modify the original without returning it at the end. This check also allows them to mess with the original object but end up with the same values at the end which is functionally equivalent to leaving it unmodified.
Closes #1496

Lasagna Master: Check that original recipe is not modified

---

exercises/concept/high-score-board/high-score-board.js

The name of the function is `updateScore` rather than `addToScore` - this update changes the thrown error to match the function name.

Fix minor inconsistency with default Error

---

exercises/concept/freelancer-rates/freelancer-rates.spec.js

Fixes mistyped .3547 for 25.47% in exercise

---

exercises/concept/translation-service/.docs/instructions.md

While doing the translation service exercise I was really confused because it seemed that the first few instructions about the api interface were reading as steps:
As this is already a concept that can be hard to grasp, I thought if we removed them as headers and kept them as part of the instructions (as I assume they are?) it will be easier to do this exercise. 
Maybe there is another way to make this happen that is semantically more correct? But right now it appears that a h3 or h2 will turn into a step?

Translation Service: remove instructions as steps

---

config.json

I have added the prerequisites for the anagram practice exercise. I am opening this pull request only for this exercise and as per how it goes I will decide on how many exercises I should add per pull request from next time. 
References #984

add prequisities for anagram practice exercise

---

docs/ROADMAP.md
docs/config.json

Bethany pointed out that by adding the roadmap to the docs folder and setting the right config, we can make it available on the website in the track-specific contribution guideline section. https://exercism.org/docs/tracks/javascript
This PR also includes some minor updates for the concept list to reflect the issues that have been created.

Make roadmap available on the website

---

CONTRIBUTING.md
config/exercise-readme-insert.md
docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md
reference/keywords/export.md
reference/keywords/import.md

Use names as presented on their respective sites. ie. copy the capitalisation and punctuation.
Being consistent when referring to these projects will avoid confusion and reduce the burden on the reader.

Fix project/product names

---

.github/workflows/action-format.yml

According to this https://github.com/npm/npm/issues/17761 `--no-save` prevents the edit of the lock file.
Fixes https://github.com/exercism/javascript/pull/1579#discussion_r776326023
cc @JaPatGitHub

Prevent changes to the lock file by the format action

---

exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js
exercises/concept/elyses-transformative-enchantments/enchantments.js

Tests and hints use array with even amount of cards, yet `sandwichTrick` function phpdoc says _deck with 10 cards_ . Probably a copypaste typo

Elyses Transformative Enchantments exercise typos

---

config.json

Adds prerequisites to the following exercises:
```
proverb
twelve-days
yacht
beer-song
resistor-color-trio
```
related to #985

#985 - Add Prerequisite to Exercises - Part 1

---

concepts/type-conversion/introduction.md

line 105: - the operands of the logical AND `&&` and OR `||` operators (the result <<<is>>> of the expression is one of the operands, not necessarily a boolean)

minor grammar fix

---

exercises/practice/two-bucket/.docs/instructions.append.md
exercises/practice/two-bucket/.docs/instructions.md
exercises/practice/two-bucket/.meta/proof.ci.js
exercises/practice/two-bucket/two-bucket.js
exercises/practice/two-bucket/two-bucket.spec.js

The moves() function now returns an object with keys: moves, goalBucket, otherBucket.
This removes the need for goalBucket and otherBucket properties.
I also fixed the "bug" where moves() can return after the 2nd move if the second bucket is the same size as the goal (fixes #1551).

Update the two-bucket proof and tests.

---

exercises/concept/poetry-club-door-policy/.docs/hints.md

Reference link for `mdn-slice` was using "." instead of "-".

Fix incorrect reference link

---

exercises/practice/bank-account/bank-account.spec.js
exercises/practice/crypto-square/crypto-square.spec.js
exercises/practice/dominoes/dominoes.spec.js
exercises/practice/go-counting/go-counting.spec.js
exercises/practice/rail-fence-cipher/rail-fence-cipher.spec.js
exercises/practice/rest-api/rest-api.spec.js
exercises/practice/robot-simulator/robot-simulator.spec.js
exercises/practice/satellite/satellite.spec.js
exercises/practice/series/series.spec.js
exercises/practice/tournament/tournament.spec.js
exercises/practice/zebra-puzzle/zebra-puzzle.spec.js

In the test files of the practice exercises, our rule is that the test cases should be marked as skipped and only the first one should be active (un-skipped).
The test files are all the <exercise-slug>.spec.js files in the folder exercises/practice/<exercise-slug>.

Fix up test case checks

---

exercises/concept/translation-service/api.js

With this change, a faulty implementation when calling the API results in the respective test failing with the following message:
```text
Error: Expected callback function when calling fetch(text, callback), actual undefined.
at new BadRequest (<solution>\api.js:122:5)
at ExternalApi.request (<solution>\api.js:76:13)
at TranslationService.request (<solution>\service.js:61:21)",
```
Without this change, the entire test run blows up and returns:
```json
{
"status": "error",
"message": "Expected to run at least one test, but none were found. This can happen if the test file(s) (.spec.js) are missing or empty. These files are normally not empty. Revert any changes or report an issue if the problem persists.",
"tests": [],
"version": 3
}
```
Because under the hood it shows:
```text
Determining …
```

Make translation service more resilient against bad implementations

---

exercises/concept/elyses-enchantments/enchantments.spec.js

I've updated the tests errors in Elyses Enchantments so that:
- tests no longer check equality between `expect => to be strictly equal to expected` but instead check `result stack => to be strictly equal to expected`
- tests that call one function multiple times to remove multiple cards now set equality on stack variable each time they run so that mutation is not required in order to pass strict equality test

fixes #1685

---

exercises/concept/translation-service/service.spec.js

The first call to `premium` already requested and resolved the translation. Therefore the quality check after requesting was never tested.
This caused code snippets like this to pass the tests, when it shouldn't
```javascript
async premium(text, minimumQuality) {
try {
const translation = await this.api.fetch(text);
if (translation.quality >= minimumQuality) {
return translation.translation;
}
throw new QualityThresholdNotMet(text);
} catch (error) {
if (error instanceof NotAvailable) {
await this.request(text);
const { translation } = await this.api.fetch(text);
return translation;
}
throw error;
}
}
```
(Credits for this snippet to dominguezcelada as part of the mentoring discussion)
The snippet above does not check the quality after requesting it and still passed the test. \
The …

Fix wrong test case in Translation Service

---

concepts/conditionals/about.md

add inner brackets in conditionals concept that were removed by the auto-formatting.
add prettier-ignore to prevent prettier from removing them

add missing inner brackets in conditionals concept

---

concepts/classes/about.md
concepts/classes/introduction.md

The correct spelling of the word is 'mileage' rather than 'milage'

Correct 'milage' to 'mileage'

---

exercises/practice/simple-linked-list/simple-linked-list.spec.js

The same test case 'can convert to an array' is duplicated on lines 104 and 112. This commit removes the unnecessary duplicate.

Remove duplicate test case in Simple Linked List

---

concepts/callbacks/about.md
concepts/callbacks/introduction.md

In the example code, `squareArea` was defined but never used, and `areaOfSquare` was used but not defined, so I made them both `areaOfSquare`.

Fix typo in callbacks concept

---

config.json
exercises/concept/elyses-analytic-enchantments/.docs/introduction.md

Move arrow functions concept to different exercise

---

exercises/concept/freelancer-rates/.docs/instructions.md

Removing gender from instructions; I feel it would be more inclusive to everyone and less stereotypical for the freelancer to be male

Gender neutral pronouns for freelancers

---

exercises/concept/coordinate-transformation/coordinate-transformation.spec.js

In the previous test description we state that the "correct" order is `g(f(x))`. Since the order should be the opposite in the description being fixed, it should be `f(g(x))`
```
test('should compose in the correct order: g(f(x))', () => {
const composed = composeTransform(scaler, translator);
expect(composed(0, 0)).toEqual([-6, 10]);
});
test('should compose in the opposite order: f(g(x))', () => {
const composed = composeTransform(translator, scaler);
expect(composed(0, 0)).toEqual([-18, 20]);
});
```

Fix test description in coordinate-transformation

---

reference/implementing-a-concept-exercise.md

`<slug.cs>` -> `<slug.js>` in implementing-a-concept-exercise.md
Fix #1920.

typo: <slug.cs> -> <slug.js>

---

config.json

As discussed [here](https://github.com/exercism/javascript/pull/1924#discussion_r985086844). The exercise encourages the use of regex, which is far from trivial IMO
An hacktoberfest label would be awesome :pray:

Increase difficulty of the word-count exercise

---

docs/REPRESENTER_NORMALIZATIONS.md
exercises/shared/.docs/representations.md

This normalizes (ha pun intended) the representer guide documentation by adding a new doc with the examples, simplifying the snippet doc shown in the mentoring automation guide.

Add representer normalizations document

---

concepts/null-undefined/introduction.md

I realized that the examples were missing while going over the list of different contexts in which the **undefined** appears. This PR adds these examples to the list items.

Add examples to undefined

---

exercises/concept/coordinate-transformation/coordinate-transformation.spec.js

Context
-------
Coming from other programming languages, the [scope](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures#scoping_with_let_and_const) of the cached values may be surprising in JavaScript. When looking at community solutions, I was certainly surprised that other folks were not testing whether `f` had changed between invocations of the closure returned from `memoizeTransform()`.
Change
------
Add a new test case asserting that different values of `f` have different caches.

Ensure recalculation when a new function is passed in

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest-series-product.spec.js

The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …

Sync largest-series-product docs with problem-specifications

---

exercises/practice/transpose/.meta/tests.toml
exercises/practice/transpose/transpose.spec.js

Follow-up from this topic: https://forum.exercism.org/t/transpose-ensure-all-lines-are-right-trimmed/5165
- `mixed line length` was already in the `exercises/practice/transpose/.meta/tests.toml` file
- `jagged triangle` was missing too so I went ahead and synced it too
@SleeplessByte

:sparkles: Sync `transpose` with problem-specifications

---

exercises/concept/elyses-destructured-enchantments/enchantments.js

JSDoc requires curly brackets for type declarations.  Solves issue where insertFaceCards function return was being highlighted as incorrect type when FACE_CARDS were spread into returned array.

Added curly brackets to JSDoc type declaration.

---

exercises/concept/freelancer-rates/.meta/exemplar.js

As per the discussion pertaining to the topic in the forums at the following link:
[Thread](https://forum.exercism.org/t/about-the-exemplar-solution-in-the-freelancer-rates-exercise-in-the-js-track/6540)

Replaced the magic number 22 with a constant named billableDaysPerMonth

---

exercises/concept/coordinate-transformation/coordinate-transformation.spec.js

Previously, when `translate2d` or `scale2d` were still lacking an implementation, the tests would crash instead of fail properly. This patch removes the need for the testees to be implemented, so that all missing implementations result in proper test failures only.
This issue was [discussed on the forum](https://forum.exercism.org/t/bug-on-coordinate-transformation-fixed/6678).

Make tests robust against missing implementations of testees

---

exercises/concept/fruit-picker/.docs/hints.md

Hello, this related to #1833. Updated hints.md and tried to be more exact. Please let me know if you dislike anything, I really like your project and want to help more. 
PS. I have been taught that it is a good idea to first merge main into whatever my branch is and THEN do the pull request at the end. Do you like doing that as well?

updated hints.md for fruit picker exercise

---

exercises/concept/coordinate-transformation/.docs/instructions.md

The function composeTransformation does not exist in the supplied javascript template for this exercise.
Instead use composeTransform to match the exercise function name supplied.

Update instructions.md function name to match provided template

---

exercises/concept/poetry-club-door-policy/.meta/exemplar.js

--
🤝 https://forum.exercism.org/t/poetry-club-door-policy-template-string-delimiters/7175

Use non-interpolating string delimiters

---

exercises/practice/grains/.approaches/bit-shifting/content.md
exercises/practice/grains/.approaches/bit-shifting/snippet.txt
exercises/practice/grains/.approaches/introduction.md

fixed to `throw new Error` instead of just `throw`, which apparently does not throw an error.

Grains approach fix

---

concepts/array-transformations/about.md
concepts/classes/about.md
concepts/classes/introduction.md
concepts/dates/about.md
concepts/dates/introduction.md
exercises/concept/bird-watcher/.docs/instructions.md
exercises/concept/elyses-enchantments/.docs/instructions.md
exercises/concept/translation-service/.docs/instructions.md
exercises/concept/windowing-system/.docs/introduction.md
exercises/practice/bob/.approaches/answer-array/content.md
exercises/practice/bob/.approaches/if-statements/content.md
exercises/practice/bob/.approaches/switch-statement/content.md
exercises/practice/etl/.docs/instructions.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/grains/.approaches/bit-shifting/content.md
exercises/practice/grains/.approaches/exponentiation/content.md
exercises/practice/isogram/.approaches/bitfield/content.md
exercises/practice/leap/.approaches/new-date-getmonth/content.md
exercises/practice/linked-list/.docs/instructions.md
exercises/practice/pangram/.approaches/bitfield/content.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/simple-linked-list/.docs/instructions.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

.github/workflows/action-format.yml
.github/workflows/action-sync.yml
.github/workflows/ci.js.yml
.github/workflows/codeql.yml
.github/workflows/pr.ci.js.yml
.github/workflows/verify-code-formatting.yml

This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.

CI: pin GitHub Actions runners

---

docs/FUNCTIONS.md

Some minimal information that we want[ed] to share about Functions in JavaScript

Add initial functions document

---

config.json
exercises/practice/leap/.docs/introduction.md
exercises/practice/pop-count/.docs/instructions.md
exercises/practice/pop-count/.docs/introduction.md
exercises/practice/pop-count/.eslintrc
exercises/practice/pop-count/.gitignore
exercises/practice/pop-count/.meta/config.json
exercises/practice/pop-count/.meta/proof.ci.js
exercises/practice/pop-count/.meta/tests.toml
exercises/practice/pop-count/.npmrc
exercises/practice/pop-count/LICENSE
exercises/practice/pop-count/babel.config.js
exercises/practice/pop-count/package.json
exercises/practice/pop-count/pop-count.js
exercises/practice/pop-count/pop-count.spec.js

Adding pop-count exercise to the js track

[New practice exercise] Pop count

---

.prettierignore
config.json

The configlet CI is currently failing because `configlet fmt` is showing the track config to be unformatted. This is a recently added check for configlet.

Format track config with `configlet fmt`

---

CONTRIBUTING.md
README.md
config.json
docs/FUNCTIONS.md
docs/INSTALLATION.md
reference/implementing-a-concept-exercise.md
reference/info/concurrency.md
reference/info/event_loop.md
reference/info/falsy.md

With Alerts being supported on GitHub [recently](https://github.com/orgs/community/discussions/16925), this PR adds the updated markdown support to indicate the importance of the text.
Example:
> [!IMPORTANT]  
> We 💙 our community but **this repository does not accept community contributions at this time**.<br>
> There are no active maintainers to review PRs.<br>
> Please read this [community blog post][freeing-maintainers] for details.
Reference: https://github.com/orgs/community/discussions/16925

Adds Alerts Markdown support

---

exercises/practice/robot-name/robot-name.spec.js

Without the IIFE, `expect()` fails to detect the failure; see https://forum.exercism.org/t/8300

Fix 'name cannot be modified' test

---

exercises/concept/lasagna/lasagna.spec.js

Using distinct values from the first test to make them harder to confuse
Related to https://forum.exercism.org/t/typescript-test-runner-expected-vs-received/9842

concept/lasagna: change last totalTimeInMinutes test to use distinct values.

---

.prettierignore

Fixes current CI failure on main branch: https://github.com/exercism/javascript/actions/runs/8275983609/job/22643776556

Ignore org-wide files from prettier check

---

concepts/regular-expressions/about.md

Small fixes to the regular expression about readme

docs: Update regular expression about readme

---

exercises/practice/yacht/.meta/tests.toml
exercises/practice/yacht/yacht.spec.js

Adds missing positive test for the fives category in the Yacht exercise.

Add missing positive fives category test.

---

exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js

https://forum.exercism.org/t/js-elyses-destructured-enchantments-exemplar-inconsistent/12084

destructure parameters

---

exercises/concept/high-score-board/.docs/introduction.md

This is related to https://forum.exercism.org/t/high-score-board-exercise-update-mdn-link-to-point-to-general-oop-page-vs-page-on-js-classes/12727.

[High Score Board Exercise] Update MDN link to point to general OOP page vs. page on JS classes.

---

exercises/concept/factory-sensors/.meta/config.json
exercises/concept/factory-sensors/factory-sensors.spec.js

This exercise should reject solutions with `!temperature`.
1) In the story `null` is a special signal that the sensor is broken. That means in-universe the sensor will needlessly be replaced if it happens to encounter temperatures of 0 degrees.
2) In our world, the assignment requires that students make distinction between nulls and numbers. 0 is a valid number. There is no reason to have it _intentionally_ be handled differently than -1 or 1 and lumped with `null`.
This is supported by the existing exemplar solution; it uses `if (temperature === null)`

[factory-sensors] Add test for temperature of 0 degrees

---

exercises/concept/translation-service/.meta/config.json
exercises/concept/translation-service/api.js
exercises/concept/translation-service/errors.js
exercises/concept/translation-service/service.spec.js

Will open a forum thread in a minute.
[Edit] [Forum post](https://forum.exercism.org/t/translation-service-pr-to-make-changes-to-api-mock/13018)

[Translation service] Constrain service api

---

exercises/concept/lasagna-master/.docs/introduction.md

Add a paragraph and example about storing a function's return value in a variable.
As discussed and approved in the following thread: [http://forum.exercism.org/t/lasagna-master-add-an-explanation-for-the-purpose-of-the-return-statement/12277/4](http://forum.exercism.org/t/lasagna-master-add-an-explanation-for-the-purpose-of-the-return-statement/12277/4)

Update Lasagna Master Introduction

---

exercises/practice/knapsack/knapsack.spec.js

Added xtest to the knapsack exercise at it was missing. Now all the current exercises are consistent

fix: Added missing xtest

---

exercises/practice/lens-person/.meta/config.json
exercises/practice/lens-person/lens.js

The methods were unused. [Discussion here](http://forum.exercism.org/t/possible-issue-in-unit-test-on-lens-person-exercise/12102/9)

[lens-person] Remove `get` and `set` methods

---

exercises/practice/affine-cipher/.docs/instructions.md
exercises/practice/alphametics/.meta/config.json
exercises/practice/atbash-cipher/.docs/instructions.md
exercises/practice/atbash-cipher/.meta/config.json
exercises/practice/change/.docs/instructions.md
exercises/practice/change/.docs/introduction.md
exercises/practice/collatz-conjecture/.docs/instructions.md
exercises/practice/collatz-conjecture/.docs/introduction.md
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/complex-numbers/.docs/instructions.md
exercises/practice/darts/.meta/config.json
exercises/practice/dominoes/.docs/instructions.md
exercises/practice/dominoes/.docs/introduction.md
exercises/practice/eliuds-eggs/.docs/introduction.md
exercises/practice/eliuds-eggs/.meta/config.json
exercises/practice/grade-school/.docs/instructions.md
exercises/practice/hamming/.docs/instructions.md
exercises/practice/hamming/.docs/introduction.md
exercises/practice/hamming/.meta/config.json
exercises/practice/knapsack/.docs/instructions.md
exercises/practice/knapsack/.docs/introduction.md
exercises/practice/phone-number/.docs/introduction.md
exercises/practice/protein-translation/.docs/instructions.md
exercises/practice/pythagorean-triplet/.docs/instructions.md
exercises/practice/pythagorean-triplet/.docs/introduction.md
exercises/practice/pythagorean-triplet/.meta/config.json
exercises/practice/raindrops/.meta/config.json
exercises/practice/strain/.meta/config.json
exercises/practice/yacht/.meta/config.json

```
.\bin\configlet.exe sync -u --docs --filepaths --metadata
PS C:\Programming\Exercism\javascript> .\bin\configlet.exe sync -u --docs --filepaths --metadata
Updating cached 'problem-specifications' data...
Checking exercises...
Every exercise has up-to-date docs!
Every exercise has up-to-date filepaths!
Every exercise has up-to-date metadata!
```
This PR syncs all the `filepaths`, `docs` and `metadata` for all the un-synced exercises!

Updating docs, filepaths and metadata for all un-synced exercises

---

exercises/concept/fruit-picker/.meta/exemplar.js
exercises/practice/allergies/.meta/config.json
exercises/practice/allergies/.meta/tests.toml
exercises/practice/allergies/allergies.spec.js

This PR syncs `tests.toml` with the `problem-specifications` repository and incorporates the new tests into the test file. These updates follow the approval in [PR #2567](https://github.com/exercism/javascript/pull/2567).
npx cross-env ASSIGNMENT=practice/allergies babel-node scripts/test 
PS C:\Programming\Exercism\javascript> npx cross-env ASSIGNMENT=practice/allergies babel-node scripts/test 
```
Running tests for practice/allergies...
PASS tmp_exercises/practice/allergies/allergies.spec.js
Allergies
testing for eggs allergy
√ not allergic to anything (3 ms)
√ allergic only to eggs (1 ms)
√ allergic to eggs and something else
√ allergic to something, but not eggs
√ allergic to everything
testing for peanuts allergy
√ not allergic to anything
√ allergic only to peanuts
√ allergic to …
```

Updating tests for Allergies

---

exercises/practice/change/.meta/config.json
exercises/practice/change/.meta/tests.toml
exercises/practice/change/change.spec.js

Updating tests for change

---

exercises/practice/dominoes/.meta/config.json
exercises/practice/dominoes/.meta/tests.toml
exercises/practice/dominoes/dominoes.spec.js

This pull request updates the test suite for the **Dominoes** exercise, aligning it with the latest problem specification.

Updating tests for dominoes

---

exercises/practice/palindrome-products/.meta/config.json
exercises/practice/palindrome-products/.meta/proof.ci.js
exercises/practice/palindrome-products/.meta/tests.toml
exercises/practice/palindrome-products/palindrome-products.spec.js

This pull request updates the test suite for the **Palindrome-Products** exercise to align it with the latest problem specification.  
- The test suite now incorporates the updated cases from the latest specification.  
- The old proof solution has been replaced with the one published by @Cool-Katt, as the previous solution assumed the smallest product was always derived from the smallest factor—a scenario specifically addressed by the new test cases.  
- @Cool-Katt has been added to the contributors' list in acknowledgement of their solution contribution.  
Please review the changes and let me know if further adjustments are needed.

Updating tests and proof solution for palindrome-products

---

exercises/practice/armstrong-numbers/.docs/instructions.append.md
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/armstrong-numbers/.meta/proof.ci.js
exercises/practice/armstrong-numbers/.meta/tests.toml
exercises/practice/armstrong-numbers/armstrong-numbers.spec.js

This PR adds two new test cases to the Armstrong-Numbers exercise to align it with the `problem-specifications` repository. However, both numbers in these new tests are extremely large and will cause the `test-runner` to fail. Please let me know how you'd like me to proceed with this!

Updating tests for armstrong-numbers

---

config.json
exercises/practice/game-of-life/.docs/instructions.md
exercises/practice/game-of-life/.docs/introduction.md
exercises/practice/game-of-life/.gitignore
exercises/practice/game-of-life/.meta/config.json
exercises/practice/game-of-life/.meta/proof.ci.js
exercises/practice/game-of-life/.meta/tests.toml
exercises/practice/game-of-life/.npmrc
exercises/practice/game-of-life/LICENSE
exercises/practice/game-of-life/babel.config.js
exercises/practice/game-of-life/eslint.config.mjs
exercises/practice/game-of-life/game-of-life.js
exercises/practice/game-of-life/game-of-life.spec.js
exercises/practice/game-of-life/jest.config.js
exercises/practice/game-of-life/package.json
exercises/practice/game-of-life/pnpm-lock.yaml

https://forum.exercism.org/t/add-conways-game-of-life/16708/2

Add `game-of-life`

---

exercises/concept/freelancer-rates/.docs/instructions.md

Added note to clarify "ratePerHour" and "dayRate" meaning.
https://forum.exercism.org/t/javascript-freelancer-rates-confused-spelling/16054

Update instructions.md with a note

---

config.json

We currently don't "support" `practices` in the JavaScript track (as I don't think the UI is clear / helps). Will have to think this through before having it in "some" places.

Remove practices & format config.json

---

concepts/array-destructuring/about.md
concepts/object-destructuring/.meta/config.json
concepts/object-destructuring/about.md
concepts/object-destructuring/introduction.md
concepts/object-destructuring/links.json
config.json
exercises/concept/elyses-destructured-enchantments/.docs/hints.md
exercises/concept/elyses-destructured-enchantments/.docs/instructions.md
exercises/concept/elyses-destructured-enchantments/.docs/introduction.md
exercises/concept/elyses-destructured-enchantments/.meta/design.md
exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js
exercises/concept/elyses-destructured-enchantments/enchantments.js
exercises/concept/elyses-destructured-enchantments/enchantments.spec.js

Concept: object destructuring

---

exercises/concept/appointment-time/appointment-time.spec.js

Prevent solutions that don't pass values to `new Date()`.

Appointment Times: Add more tests to discourage bad implementations

---

exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js
exercises/concept/elyses-destructured-enchantments/enchantments.js
exercises/concept/elyses-destructured-enchantments/enchantments.spec.js

You now *must* use destructuring or the tests fail.

Elyses Destructured Enchantments: Prevent not following the instructions

---

exercises/concept/train-driver/.meta/exemplar.js
exercises/concept/train-driver/train-driver.js
exercises/concept/train-driver/train-driver.spec.js

Blocks writing all the examples below:
```javascript
export function fixListOfWagons(ids) {
const firstTwo = ids.slice(0,2)
const rest = ids.slice(2)
return [...rest, ...firstTwo]
}
export function correctListOfWagons(ids, missingWagons) {
const firstOne = ids.slice(0,1)
const rest = ids.slice(1)
return [...firstOne,...missingWagons,...rest]
}
export function correctListOfWagons(ids, missingWagons) {
return [ids[0], ...missingWagons, ...ids.splice(1)];
}
```
- `slice` will not be a function on the list
- `[0]` will return undefined
- `console.log(missingWagons)` will print `List of (1,2,3)` in node (and later also in web)

Train Driver: Prevent not following the instructions

---

exercises/practice/pythagorean-triplet/.docs/instructions.append.md

This comes after the discussion in #2648 to update `instructions.append.md` to address the skipped test in the test runner!

Updating `instructions.append.md` to address the skipped test

---

exercises/concept/train-driver/train-driver.spec.js

This prevents:
```javascript
export function separateTimeOfArrival(information) {
let arrivalTime = information.timeOfArrival;
delete information.timeOfArrival;
return [arrivalTime, information] 
}
```
This is important because we want the teaching goal of
```javascript
const { timeOfArrival, ...rest } = information
```

Train Driver: Prevent deleting object property

---

exercises/practice/reverse-string/.meta/config.json

continues #2648 
Changes the state of `flag.tests.includes-optional` to fix the optional tests issue found out by @devcyjung

Fixing optional test issue

---

exercises/concept/freelancer-rates/freelancer-rates.spec.js

Fix issue where task based outputs do not work due to nested `describe()` calls. See [Discord discussion](https://discord.com/channels/854117591135027261/1385322924428230816).

Remove nested describes to unbreak task-based testing

---

config.json

We have strings in this exercise, and it uses a function call on an object.
Moving it below functions works.

Fix prerequisites for captains-log

---

exercises/practice/high-scores/.meta/config.json
exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/high-scores.spec.js

This PR syncs `tests.toml` with the `problem-specifications` repository and updates the test file.

Update tests high scores

---

exercises/practice/list-ops/.meta/config.json
exercises/practice/list-ops/.meta/tests.toml
exercises/practice/list-ops/list-ops.spec.js

This PR syncs `tests.toml` with the `problem-specifications` repository and updates the test file.

Update tests list ops

---

config.json
exercises/practice/flower-field/.docs/instructions.md
exercises/practice/flower-field/.docs/introduction.md
exercises/practice/flower-field/.gitignore
exercises/practice/flower-field/.meta/config.json
exercises/practice/flower-field/.meta/proof.ci.js
exercises/practice/flower-field/.meta/tests.toml
exercises/practice/flower-field/.npmrc
exercises/practice/flower-field/LICENSE
exercises/practice/flower-field/babel.config.js
exercises/practice/flower-field/eslint.config.mjs
exercises/practice/flower-field/flower-field.js
exercises/practice/flower-field/flower-field.spec.js
exercises/practice/flower-field/jest.config.js
exercises/practice/flower-field/package.json

This PR adds Flower Field, deprecating Minesweeper. See https://forum.exercism.org/t/suggestion-deprecate-minesweeper-for-flower-field/17967

Add `flower-field`, deprecating `minesweeper`

---

exercises/concept/recycling-robot/.docs/hints.md
exercises/concept/recycling-robot/.docs/instructions.md
exercises/concept/recycling-robot/.meta/exemplar.js
exercises/concept/recycling-robot/assembly-line.js
exercises/concept/recycling-robot/assembly-line.spec.js
exercises/concept/recycling-robot/lib.js

Changes:
- Whilst everyone is using `typeof` correctly, the newer tests prevent you from coercing incorrectly. 
- It also tests numeric strings correctly (to prevent incorrect regex solutions), adds negative numbers, and numbers that fit in `BigInt` but not `Number` (to force `isFinite`). 
- I also added tests to prevent people from comparing `object.prototype` (to force `instanceof`), by adding branded check to `ElectronicDevice`.
- Added some fake arrays to prevent `instanceof Array`.
- Finally, increased the tests for the final few tasks, particularly checking `type: null` so people cannot do `!object.type`.

Improve test names and prevent some solutions

---

exercises/practice/parallel-letter-frequency/.docs/instructions.append.md

As requested in this [forum thread](https://forum.exercism.org/t/add-mention-to-the-use-of-web-worker-api-on-web-test-runner-to-parallel-letter-frequency-text/18571), a quick note to make students aware of the current situation.
And fixes some minor formatting, spelling and casing issues.

Note on parallelism

---

.prettierignore
exercises/concept/appointment-time/.docs/hints.md
exercises/concept/appointment-time/.meta/config.json
exercises/concept/appointment-time/.meta/exemplar.js
exercises/concept/appointment-time/appointment-time.spec.js

Fixes #2733
See https://forum.exercism.org/t/tests-and-suggested-implementation-for-appointment-time-are-wrong/.

Fix faulty tests for `createAppointment`

---

concepts/template-strings/introduction.md
exercises/concept/custom-signs/.docs/instructions.md

@SleeplessByte : Forum post here: https://forum.exercism.org/t/clarity-on-template-strings/19454/2

Enhance template string lesson with newline escape sequence demonstration
