exercism/javascript

bob/bob.js, bob/bob_test.spec.js, bob/example.js, bob/gulpfile.js, bob/package.json, config.json
This exercise has been copied from the JavaScript track of exercism.io
It has been refactored to use some ES6 features
=> Add new exercise: Bob

config.json, word-count/example.js, word-count/gulpfile.js, word-count/package.json, word-count/word-count_test.spec.js
Not too much to comment here, just a new assignment.
Import/export modules ECMAScript 6 feature is used and it works without extra work, so other assignments will use it too.
=> Add new assignment: Word Count

bob/bob.js, bob/bob_test.spec.js, bob/example.js, hello-world/example.js, hello-world/hello-world.js, hello-world/hello-world_test.spec.js, palindrome-products/example.js, palindrome-products/palindrome-products.js, palindrome-products/palindrome-products_test.spec.js
Import/export modules were used successfully in PR #19. This PR use that feature for existing assignments, making existing code more ES6-ish.
=> Use import/export modules ES6 feature

config.json, hamming/example.js, hamming/gulpfile.js, hamming/hamming_test.spec.js, hamming/package.json
=> Add new exercise: Hamming

anagram/anagram_test.spec.js, anagram/example.js, anagram/gulpfile.js, anagram/package.json, config.json
=> Add new exercise: Anagram

config.json, food-chain/example.js, food-chain/food-chain_test.spec.js, food-chain/gulpfile.js, food-chain/package.json
=> Add new exercise: food-chain

config.json, leap/example.js, leap/gulpfile.js, leap/leap_test.spec.js
=> Add new exercise: Leap

beer-song/beer-song_test.spec.js, beer-song/example.js, beer-song/gulpfile.js, config.json
**Beer song** exercise based on the same exercise from the [JavaScript](https://github.com/exercism/xjavascript) track.
=> Add new exercise: Beer song

config.json, rna-transcription/example.js, rna-transcription/gulpfile.js, rna-transcription/rna-transcription_test.spec.js
=> Add new exercise: RNA Transcription

config.json, gigasecond/example.js, gigasecond/gigasecond_test.spec.js, gigasecond/gulpfile.js
Usually, I don't change the spec's descriptions, but this time I've thought they could be more descriptive.
If you find them appropriate, I could update this exercise on the xjavascript track.
=> Add new exercise: Gigasecond

config.json, phone-number/example.js, phone-number/gulpfile.js, phone-number/phone-number_test.spec.js
Here is another exercise for the track.
I've also reorganized `config.json` problems property to mirror it from the javascript track.
=> Add new exercise: Phone number

config.json, grade-school/example.js, grade-school/grade-school_test.spec.js, grade-school/gulpfile.js
Just a new exercise: Grade school
=> Add new exercise: Grade school

config.json
I hope  this change is enough to activate the track.
=> Activate language track

config.json, robot-name/example.js, robot-name/gulpfile.js, robot-name/package.json, robot-name/robot-name_test.spec.js
We're going to need lots of them :smile_cat:
=> Add new exercise: Robot name

config.json, etl/etl_test.spec.js, etl/example.js, etl/gulpfile.js, etl/package.json
=> New exercise: ETL

config.json, space-age/example.js, space-age/gulpfile.js, space-age/package.json, space-age/space-age_test.spec.js
Here is the Space age exercise again!
=> New exercise: Space age

Makefile, config.json, grains/big-integer.js, grains/big-integer.spec.js, grains/example.js, grains/grains.spec.js, grains/gulpfile.js, grains/package.json
=> New exercise: Grains

beer-song/beer-song.spec.js, bob/bob.spec.js, etl/etl.spec.js, hello-world/hello-world.spec.js, palindrome-products/palindrome-products.spec.js, phone-number/example.js, robot-name/example.js, space-age/example.js, word-count/word-count.spec.js
PR #53 does not replace all uses of `var`. This PR completes that work. In case of merging, it should be done after merging #53.
=> Replace all uses of `var` with `const`

robot-name/robot-name.spec.js
While practising this exercise, I miss a intermediate test from having just one robot with a name to thousands of robots with different names.
This new test tries to guide the user with smaller steps. One can first hardcode the first name. Then, the user needs to generate a different name, but only one more. After that, the next test ask the user to generate 10k different names.
=> Add test to help implement Robot with smaller steps

gigasecond/gigasecond.spec.js
Added a test like https://github.com/exercism/xjavascript/pull/125 for this track.
=> Immutable gigasecond test

binary/binary.spec.js, binary/example.js, binary/gulpfile.js, binary/package.json, circular-buffer/circular-buffer.spec.js, circular-buffer/example.js, circular-buffer/gulpfile.js, circular-buffer/package.json, config.json, prime-factors/example.js, prime-factors/gulpfile.js, prime-factors/package.json, prime-factors/prime-factors.spec.js
@rchavarria here you go!  ~~I also updated the gulpfile a bit to use arrow functions.~~ The gulpfile does not like arrow functions in Travis.  Reverted.
=> new exercise circular-buffer

config.json, roman-numerals/example.js, roman-numerals/gulpfile.js, roman-numerals/package.json, roman-numerals/roman-numerals.spec.js
Here's the classic Roman numerals exercise.
=> Add new exercise: Roman numerals

config.json, raindrops/example.js, raindrops/gulpfile.js, raindrops/package.json, raindrops/raindrops.spec.js
Ported from JS track.  @rchavarria ?
=> Add new exercise raindrops

allergies/allergies.spec.js, allergies/example.js, allergies/gulpfile.js, allergies/package.json, config.json
Just adds a new exercise taken from xjavascript as requested in #85.
=> Add new exercise: Allergies

docs/INSTALLATION.md, docs/LEARNING.md, docs/TESTS.md
=> Updated track docs to reference Babel instead of Traceur

config.json, simple-cipher/example.js, simple-cipher/gulpfile.js, simple-cipher/package.json, simple-cipher/simple-cipher.spec.js
=> Add new exercise simple-cipher

config.json, crypto-square/crypto-square.spec.js, crypto-square/example.js, crypto-square/gulpfile.js, crypto-square/package.json
=> Add new exercise crypto-square

atbash-cipher/atbash-cipher.spec.js, atbash-cipher/example.js, atbash-cipher/gulpfile.js, atbash-cipher/package.json, config.json
=> Add new exercise atbash-cipher

accumulate/accumulate.spec.js, accumulate/example.js, accumulate/gulpfile.js, accumulate/package.json, config.json
=> Add new exercise accumulate

config.json, trinary/example.js, trinary/gulpfile.js, trinary/package.json, trinary/trinary.spec.js
=> Add new exercise trinary

config.json
=> Reorder config.json to match JS track

config.json, luhn/example.js, luhn/gulpfile.js, luhn/luhn.spec.js, luhn/package.json
Port exercise from JS track.  A very classy solution in honor of @rchavarria
=> Add new exercise luhn

config.json, pig-latin/example.js, pig-latin/gulpfile.js, pig-latin/package.json, pig-latin/pig-latin.spec.js
My small contribution, a new exercise, as described at #110
=> Add new exercise: Pig latin

config.json, pythagorean-triplet/example.js, pythagorean-triplet/gulpfile.js, pythagorean-triplet/package.json, pythagorean-triplet/pythagorean-triplet.spec.js
Ported from JS Track.  @rchavarria, this `example.js` has _two_ classes 😄
=> Add new exercise pythagorean-triplet

hello-world/example.js, hello-world/hello-world.js, hello-world/hello-world.spec.js
=> Change first test to pass undefined name

docs/ABOUT.md
As mentioned in #43 @rchavarria would something like this work for the ABOUT.md?
=> Add ABOUT.md to docs

config.json, series/example.js, series/gulpfile.js, series/package.json, series/series.spec.js
As described in #116 .  This PR also syncs the exercise order with the JS track.  @rchavarria, how does this look to you?
=> Add new exercise series

config.json, difference-of-squares/difference-of-squares.spec.js, difference-of-squares/example.js, difference-of-squares/gulpfile.js, difference-of-squares/package.json
=> Add new exercise difference-of-squares

config.json, secret-handshake/example.js, secret-handshake/gulpfile.js, secret-handshake/package.json, secret-handshake/secret-handshake.spec.js
=> Add new exercise secret-handshake

config.json, kindergarten-garden/example.js, kindergarten-garden/gulpfile.js, kindergarten-garden/kindergarten-garden.spec.js, kindergarten-garden/package.json
A new exercise ported form xjavascript
=> Add new exercise: Kindergarten garden

secret-handshake/secret-handshake.spec.js
Use hexadecimal numbers to relate test descriptions and test implementations.
=> Improve test descriptions on Secret handshake

config.json, linked-list/example.js, linked-list/gulpfile.js, linked-list/linked-list.spec.js, linked-list/package.json
=> Add new exercise linked-list

config.json, wordy/example.js, wordy/gulpfile.js, wordy/package.json, wordy/wordy.spec.js
=> Add new exercise wordy

config.json, largest-series-product/example.js, largest-series-product/gulpfile.js, largest-series-product/largest-series-product.spec.js, largest-series-product/package.json
=> Add new exercise largest-series-product

binary-search-tree/binary-search-tree.spec.js, binary-search-tree/example.js, binary-search-tree/gulpfile.js, binary-search-tree/package.json, config.json
=> Add new exercise: Binary search tree

config.json, hexadecimal/example.js, hexadecimal/gulpfile.js, hexadecimal/hexadecimal.spec.js, hexadecimal/package.json
=> Add new exercise hexadecimal

config.json, matrix/example.js, matrix/gulpfile.js, matrix/matrix.spec.js, matrix/package.json
=> Add new exercise: Matrix

robot-name/example.js, robot-name/robot-name.spec.js
As described in #140.  This also required changing the solution, which returned the actual variable containing the internal state.
=> Add new test to robot name to prevent modification of internal state

config.json, robot-simulator/example.js, robot-simulator/gulpfile.js, robot-simulator/package.json, robot-simulator/robot-simulator.spec.js
=> Add new exercise: Robot simulator

config.json, nth-prime/example.js, nth-prime/gulpfile.js, nth-prime/nth-prime.spec.js, nth-prime/package.json
=> Add new exercise: Nth prime

config.json, pascals-triangle/example.js, pascals-triangle/gulpfile.js, pascals-triangle/package.json, pascals-triangle/pascals-triangle.spec.js
=> Add new exercise: Pascal's triangle

config.json, sum-of-multiples/example.js, sum-of-multiples/gulpfile.js, sum-of-multiples/package.json, sum-of-multiples/sum-of-multiples.spec.js
=> Add new exercise sum-of-multiples

config.json, queen-attack/example.js, queen-attack/gulpfile.js, queen-attack/package.json, queen-attack/queen-attack.spec.js
=> Add new exercise queen-attack

config.json, saddle-points/example.js, saddle-points/gulpfile.js, saddle-points/package.json, saddle-points/saddle-points.spec.js
=> Add new exercise saddle-points

config.json, ocr-numbers/example.js, ocr-numbers/gulpfile.js, ocr-numbers/ocr-numbers.spec.js, ocr-numbers/package.json
=> Add new exercise ocr-numbers

config.json, say/example.js, say/gulpfile.js, say/package.json, say/say.spec.js
=> Add new exercise say

config.json, meetup/example.js, meetup/gulpfile.js, meetup/meetup.spec.js, meetup/package.json
=> Add new exercise meetup

config.json, custom-set/custom-set.spec.js, custom-set/example.js, custom-set/gulpfile.js, custom-set/package.json
=> Add new exercise custom-set

bracket-push/bracket-push.spec.js, bracket-push/example.js, bracket-push/gulpfile.js, bracket-push/package.json, config.json
=> Add new exercise bracket-push

config.json, two-bucket/example.js, two-bucket/gulpfile.js, two-bucket/package.json, two-bucket/two-bucket.spec.js
Here it is, the last exercise from xjavascript.
Sincerely, I don't understand it really well (I didn't read the `README` file). I think there are few tests for too much code. But, eventually, here it is.
@matthewmorgan, it's all yours.
=> Add new exercise: Two bucket

beer-song/beer-song.spec.js
=> Add test for whole song

beer-song/beer-song.spec.js
@rchavarria perhaps this is what you were looking for in #172
=> Change test to match all expected verses

robot-name/robot-name.spec.js
=> Add new test to catch sequential names

beer-song/beer-song.spec.js
The test is not as complete as the existing one. It doesn't test the complete verses. But it relies on previous tests.
It just tests two things:
1. There are almost 100 verses starting with `XX bottles of beer on the wall`
2. The song consist of `3 * 100` lines, 3 lines each verse, 100 verses
@matthewmorgan Feel free to discuss this implementation. It's simpler than the existing one, but you may prefer a more complete version than mine. That's ok.
=> Make it simple how to test the whole song

acronym/acronym.spec.js, acronym/example.js, acronym/gulpfile.js, acronym/package.json, config.json
=> Add new exercise acronym

meetup/example.js, meetup/meetup.spec.js
=> Remove underscores from meetup test and example code

acronym/acronym.spec.js
@rchavarria this separates tests like we discussed.  Please let me know if this looks good.
=> Separate tests to aid TDD

largest-series-product/largest-series-product.spec.js
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.
=> largest-series-product corner cases

exercises/triangle/triangle.spec.js
As authored by @mgmatola for the JavaScript track.
=> Add test to catch non-numeric sorting of sides

docs/ABOUT.md
=> Format quotations properly

exercises/acronym/acronym.spec.js
Disable all tests except the first one to help users to implement the solution bit by bit.
=> Acronym: disable all tests but not the first one

docs/ABOUT.md
This PR adds the notice message discussed in #196.
=> Write a message trying to make it clear the intention of this track

exercises/triangle/triangle.spec.js
Per the [discussion](https://github.com/exercism/xerlang/issues/85) on the Erlang track.
=> Remove test that allows degenerate triangles

.travis.yml
=> Update node version in travis

exercises/scrabble-score/scrabble-score.spec.js
=> Replace "multibillionaire" with "oxyphenbutazone"

exercises/pangram/pangram.spec.js
Addresses [x-common #222](https://github.com/exercism/x-common/issues/222)
=> Add tests to Pangram

exercises/word-count/word-count.spec.js
=> (fix for #224) Fix/enhance word-count test.

config.json, exercises/diamond/diamond.spec.js, exercises/diamond/example.js, exercises/diamond/gulpfile.js, exercises/diamond/package.json
Added relevant tests and added details in problems and exercises keys in config.json
=> Add diamond problem to exercises

config.json, exercises/perfect-numbers/example.js, exercises/perfect-numbers/gulpfile.js, exercises/perfect-numbers/package.json, exercises/perfect-numbers/perfect-numbers.spec.js
Hi, 
I would like to contribute with the perfect-numbers exercise implementation.
=> Add exercise perfect-numbers

exercises/perfect-numbers/perfect-numbers.spec.js
I noticed while solving this exercise that the tests were not skipped.
=> Skip tests in perfect-numbers

README.md
Update instructions for installing dependencies and running tests.
Closes #284
=> [ci skip] Fix instructions in README

config.json, exercises/minesweeper/example.js, exercises/minesweeper/minesweeper.spec.js, exercises/minesweeper/package.json
I ported this from the JS exercise, and tried to refactor to make it a bit easier to follow.
@exercism/ecmascripts Feedback on the code is appreciated, and also on the difficulty, order, and topics.  Thanks!
=> Add exercise minesweeper

config.json, exercises/twelve-days/README.md, exercises/twelve-days/example.js, exercises/twelve-days/package.json, exercises/twelve-days/twelve-days.spec.js
Started implementation.... Will try to deliver ASAP
=> Added exercise Twelve Days!!

README.md
=> Changed the Contributing Guide meaning in the README.md file

config.json
See exercism/problem-specifications#884
=> config: Add dash between "control flow" topics

exercises/simple-cipher/simple-cipher.spec.js
Add test to ensure that simple cipher solution correctly wraps characters while decoding.
=> Add test for simple-cipher wrap on decode

exercises/custom-set/custom-set.spec.js, exercises/custom-set/example.js
Hi there! It didn't seem like anyone was working on it so I took care of https://github.com/exercism/ecmascript/issues/229
I've added all the canonical tests + a few of the tests that were in the JavaScript version that seemed useful. There were some bugs in the existing example so I also fixed those up and re-structured slightly. Let me know if anything needs to be adjusted!
=> Updated tests & example for the Custom Set problem

config.json, exercises/simple-linked-list/README.md, exercises/simple-linked-list/example.js, exercises/simple-linked-list/package.json, exercises/simple-linked-list/simple-linked-list.spec.js
This is a pretty straightforward port, adjusted for ES. Let me know if any changes are needed. Thanks! 
https://github.com/exercism/ecmascript/issues/333
=> Add simple-linked-list exercise, ported from JS

config.json, exercises/collatz-conjecture/README.md, exercises/collatz-conjecture/collatz-conjecture.spec.js, exercises/collatz-conjecture/example.js, exercises/collatz-conjecture/package.json
I think it's ready, please review:)
=> Implement exercise collatz-conjecture

config/maintainers.json
I'm not very proud of adding myself as a maintainer, but somebody needs to do the job 😉 
Come on @exercism/ecmascripts, let's prepare for Nextercism.
=> Add rchavarria as maintainer

docs/TESTS.md
=> Add document skipping of tests

.travis.yml
Per https://github.com/exercism/javascript/issues/462
Issue #377
=> Update node spec to latest stable release

config.json, exercises/react/README.md, exercises/react/example.js, exercises/react/package.json, exercises/react/react.spec.js
I'm sure there are other ways to do this, but what do people think?  I believe I have covered all the canonical cases.
NB Just realized I needed to `xtest` and remove some debugging code...should be set now.
=> Add exercise React

docs/ABOUT.md
Sorry it took me so long to get around to this!
This is a first pass at fixing issue #339.
All I did was move each sentence to its own line and remove unsupported markdown (the long quotation looks kind of weird without the blockquote markup, but oh well).
The content itself could probably use some updates as well (ES2015 is no longer the most recent revision, for example), but I didn't want to overstep the bounds of the issue without checking with the maintainers.
Thanks and let me know if you have any feedback or would like me to make additional changes!
=> update formatting in docs/ABOUT.md for Nextercism (fixes #339)

exercises/bob/README.md, exercises/bob/bob.spec.js, exercises/bob/example.js
Closes #391.
@exercism/ecmascripts I thought the change discussed here was reasonable.  Let me know if you have any objections, or any issues with the code changes.
Thanks!
=> Update bob spec and example for shouted questions

config.json, exercises/armstrong-numbers/README.md, exercises/armstrong-numbers/armstrong-numbers.spec.js, exercises/armstrong-numbers/example.js, exercises/armstrong-numbers/package.json
[Problem specification and test data](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers)
Ported from exercism/javascript#522
=> Add armstrong-numbers exercise

config.json
Resolves #401 
Followed the same steps as exercism/javascript#530
=> change unlocked_by of tracks which were unlocked by non core exercises

config.json, exercises/rational-numbers/README.md, exercises/rational-numbers/example.js, exercises/rational-numbers/package.json, exercises/rational-numbers/rational-numbers.spec.js
Ports `rational-numbers` from the JavaScript track.
=> Add exercise rational-numbers

config.json, exercises/forth/README.md, exercises/forth/example.js, exercises/forth/forth.spec.js, exercises/forth/package.json
=> Add exercise forth

config.json, exercises/point-mutations/README.md, exercises/point-mutations/example.js, exercises/point-mutations/package.json, exercises/point-mutations/point-mutations.spec.js
=> Port exercise point-mutations

config.json, exercises/variable-length-quantity/README.md, exercises/variable-length-quantity/example.js, exercises/variable-length-quantity/package.json, exercises/variable-length-quantity/variable-length-quantity.spec.js
=> Port exercise variable-length-quantity

config.json, exercises/zipper/README.md, exercises/zipper/example.js, exercises/zipper/package.json, exercises/zipper/zipper.spec.js
=> Port exercise Zipper

exercises/pangram/pangram.spec.js
Hi, this is an update to the Pangram exercise to match the problem-specifications canonical-data.json, https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json
=> Update pangram exercise spec

exercises/isogram/isogram.spec.js
Hi, this is an update to the Isogram exercise to match the problem-specifications canonical-data.json, 
https://github.com/exercism/problem-specifications/blob/master/exercises/isogram/canonical-data.json
=> Update isogram exercise spec

exercises/anagram/anagram.spec.js
Hi, this is an update to the anagram exercise to match the problem-specifications canonical-data.json,
https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/canonical-data.json
=> Update anagram exercise spec

exercises/bob/bob.spec.js, exercises/bob/example.js
Hi, this is an update to the bob exercise to match the problem-specifications canonical-data.json, also updated `example.js` to fix a failing test for `ending with whitespace` as part of the update to the problem-specifications.
https://github.com/exercism/problem-specifications/blob/master/exercises/bob/canonical-data.json
=> Update bob exercie

exercises/scrabble-score/scrabble-score.spec.js
Hi, this is an update to the scrabble-score exercise to match the problem-specifications canonical-data.json,
https://github.com/exercism/problem-specifications/blob/master/exercises/scrabble-score/canonical-data.json
=> Update scrabble-score exercise spec

exercises/matrix/matrix.spec.js
Hi, this is an update to the matrix exercise to match the problem-specifications canonical-data.json,
https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json
=> Update matrix exercise

README.md, config.json, docs/ABOUT.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/TESTS.md
This updates the config, along with the user-facing documentation.
This doesn't update the exercise README template.
That should be updated by the maintainers, so that regenerating the exercise
READMEs can be carefully checked by those who know what the outcome should be.
/FYI @exercism/ecmascript @exercism/javascript
=> Rename track to JavaScript

exercises/hamming/example.js, exercises/hamming/hamming.spec.js
https://github.com/exercism/problem-specifications/blob/602c6102bcb0feb90308d63326f7d7ca6d63ad00/exercises/hamming/canonical-data.json
=> Update hamming tests with canonical data

exercises/armstrong-numbers/README.md, exercises/bracket-push/README.md, exercises/complex-numbers/README.md, exercises/crypto-square/README.md, exercises/forth/README.md, exercises/hamming/README.md, exercises/nucleotide-count/README.md, exercises/pig-latin/README.md, exercises/point-mutations/README.md, exercises/rational-numbers/README.md, exercises/reverse-string/README.md, exercises/saddle-points/README.md, exercises/say/README.md, exercises/series/README.md, exercises/sieve/README.md, exercises/two-bucket/README.md, exercises/zipper/README.md
The main purpose of this PR is to point out that there are 18 exercises who's READMEs are out of date.  
Please pay special attention to Bob as he is using a local (.meta) copy of description.md that is not current with exercism/problem-specifications.  The .meta version of description.md supersedes the version in problem-specifications.
`configlet generate` was used to create these updates.
my curiosity was triggered by exercism/exercism#4292
I am just attempting to be helpful and don't want to interfere.
=> updates to exercise READMEs

exercises/difference-of-squares/difference-of-squares.spec.js, exercises/difference-of-squares/example.js
In exercise "difference-of-squares", renamed `squareOfSums` to `squareOfSum`, and all other occurences of sums to sum.
=> difference-of-squares: renamed squareOfSums to squareOfSum

exercises/zipper/zipper.spec.js
=> Fixes https://github.com/exercism/javascript/issues/471

exercises/twelve-days/README.md, exercises/twelve-days/example.js, exercises/twelve-days/twelve-days.spec.js
=> Update twelve days to match specification

.eslintignore, exercises/zipper/example.js, exercises/zipper/zipper.spec.js
Fix ESLint errors for the Zipper exercise #480
=> Fix ESlint errors for Zipper exercise

.eslintignore, exercises/two-bucket/example.js, exercises/two-bucket/two-bucket.spec.js
#480 
Fix ESLint errors for the Two-Bucket exercise.
=> Fix Linting: Two-Bucket

exercises/queen-attack/queen-attack.spec.js
Hey @matthewmorgan I have been working with your spec file, and I noticed you were the last one who touched it and seemed the most active! If you'd take a look at this, I would appreciate it.
Issues:
Fixes #499
Problem:
Solutions which current pass all tests would fail in an edge case.
Analysis:
Added a test in queen-attack.spec.js which tests for this edge case.
Tests:
Ran tests with npm against example solution mentioned in issue #499 to confirm that this example solution fails for new edge case test, and that test only.
I was working with @AloeareV to uncover this, thank you!!
=> queen-attack.spec.js file does not test "edge" case

exercises/bowling/bowling.spec.js, exercises/bowling/example.js
=> correct the spec file and example to match the canonical tests

.eslintignore, exercises/react/example.js, exercises/react/react.spec.js
As per #480
```sh
$ npm run lint
./exercises/react/example.js
39:9   error  'value' is never reassigned. Use 'const' instead  prefer-const
101:8   error  A space is required after '{'                     object-curly-spacing
101:45  error  A space is required before '}'                    object-curly-spacing
101:46  error  Missing semicolon                                 semi
./exercises/react/react.spec.js
1:8   error  A space is required after '{'                                  object-curly-spacing
1:45  error  A space is required before '}'                                 object-curly-spacing
3:32  error  Block must not be padded by blank lines                        padded-blocks
26:23  error  Missing trailing comma                                         comma-dangle
31:55  error …
```
=> Resolve lint issues in react exercise

exercises/leap/leap.spec.js
New test case added as specified in exercism/problem-specifications#1359
=> Update Leap tests to match canonical data in v1.4.0

.eslintignore, exercises/bracket-push/example.js
Fixed ESLint errors for the bracket-push exercise (for issue #480)
=> Fixed eslint issue with bracket-push exercise

.eslintignore, exercises/atbash-cipher/atbash-cipher.spec.js, exercises/atbash-cipher/example.js
Fix ESLint errors for the atbash-cipher exercise (for issue #480)
=> Solved eslint errors for atbash-cipher

.eslintignore, exercises/binary/example.js
Fixed ESLint errors for the binary exercise (for issue #480)
=> fixed eslint errors for binary exercise

.eslintignore, exercises/binary-search-tree/example.js
Fixed ESLint errors for the binarysearchtree exercise (for issue #480)
=> Fixed eslint issue with BinarySearchTree exercise

exercises/isogram/isogram.spec.js
New test cases added in exercism/problem-specifications#1307 and exercism/problem-specifications#1308
I have confirmed that the example solution passes these tests (at least on my machine anyway 😛)
=> Update Isogram tests to match canonical data in v1.6.0

.eslintignore, exercises/binary-search/binary-search.spec.js, exercises/binary-search/example.js
Fix ESLint errors for the binary-search exercise (for issue #480)
=> Fixed eslint errors for binary-search

.eslintignore, exercises/beer-song/example.js
Fixed ESLint errors for the beer-song exercise (for issue #480)
=> Solved eslint errors for beer-song

exercises/change/example.js
=> Fixed ESLint errors in Change exercise (part of issue #480)

.eslintignore, exercises/octal/example.js, exercises/triangle/example.js
lint triangle and octal exercises (associated to #480 )
=> triangle and octal example lint

.eslintignore, exercises/perfect-numbers/example.js, exercises/perfect-numbers/perfect-numbers.spec.js
closes #544.   Thanks for the detailed suggestions on how to improve the exercise.  The commits largely correspond to each suggestion.
In addition, I included a bit of linting at 08e7135 (more related to #480).  If it's preferred, I can spilt them as separate PRs.  Thanks.
=> Improve code quality of perfect numbers exercise

.eslintignore, exercises/series/example.js
per #480 lint series exercise.
=> lint series exercise

.eslintignore, exercises/say/example.js
Lint Say example (associated to #480 )
=> lint say example

.eslintignore, exercises/trinary/example.js
lint Trinary example associated to #480
=> lint Trinary example 

.eslintignore, exercises/proverb/proverb.spec.js
per #480, lint proverb exercise.
=> lint proverb exercise

exercises/bob/README.md
CLOSE #555
The specification for this exercise includes this scenario but it is not within the readme. This PR makes the readme align with the test suite.
=> Update Bob JavaScript exercise readme

exercises/meetup/example.js, exercises/meetup/meetup.spec.js
per #436, for meetup exercise, change default export to named export.
=> Meetup: change default export to named export

exercises/pig-latin/example.js, exercises/pig-latin/pig-latin.spec.js
per #574 , add test cases for rule 4 in pig-latin exercise.
=> add test cases for pig latin (#574)

config/maintainers.json
It's been a great 4 years everybody!  
Don't be a stranger...
=> Move matthewmorgan to 'alumnus' status

config/maintainers.json
Yep. It's sad, but my priorities changed some time ago and I even didn't mention here.
It's been a pleasure to contribute to this project. Life changes, who knowns, we'll meet in the future, for sure.
Thanks a lot for all the things I learnt from you @exercism/javascript
=> Make rchavarria contributor as alumni

config/maintainers.json
=> Add SleeplessByte to maintainers

exercises/ocr-numbers/example.js, exercises/ocr-numbers/ocr-numbers.spec.js
As discussed in issue #563, this is s full rewrite of the OCR exercise, ditching the class design of the original.
=> OCR convert to function

exercises/linked-list/example.js, exercises/linked-list/linked-list.spec.js
Issue: https://github.com/exercism/javascript/issues/436
=> linked-list: change from default export to named export

exercises/grade-school/example.js, exercises/grade-school/grade-school.spec.js
Issue: https://github.com/exercism/javascript/issues/436
=> grade-school: use named export

exercises/pascals-triangle/example.js, exercises/pascals-triangle/pascals-triangle.spec.js
Issue: https://github.com/exercism/javascript/issues/436
=> pascals-triangle: change to named export

.eslintignore, exercises/difference-of-squares/example.js, exercises/forth/forth.spec.js, exercises/grains/big-integer.spec.js
=> Minor formatting fixes as identified by ESLint

exercises/acronym/acronym.spec.js, exercises/acronym/example.js
Bring test suite up-to-date with [canonical-data.json v1.7.0](https://github.com/exercism/problem-specifications/blob/cacf1f13cc1fd3bb18dee65fee99fd078dd8a541/exercises/acronym/canonical-data.json)
=> acronym: update test suite

exercises/high-scores/example.js, exercises/high-scores/high-scores.spec.js
[Canonical data](https://github.com/exercism/problem-specifications/blob/ad1f9c4b6808b8e7e444d7063789aab2e4567300/exercises/high-scores/canonical-data.json)
=> high-scores: update test suite to v4.0.0

exercises/variable-length-quantity/example.js, exercises/variable-length-quantity/variable-length-quantity.spec.js
=> add named export to variable length quantity problem

exercises/luhn/example.js, exercises/luhn/luhn.spec.js
closes #578
**Changes:**
1. Updated test cases on **luhn.spec.js** according to [Problem Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/luhn)
2. Updated **example.js** to pass all tests
3. Minor improvements to **example.js**
=> sync luhn test cases (closes #578)

exercises/strain/example.js, exercises/strain/strain.spec.js
=> add named export to strain

exercises/sieve/example.js, exercises/sieve/sieve.spec.js
See issue #600 
(sorry for the previous pull request, I forgot the rebase and when I noticed I ended up with duplicated commit)
=> add named export to sieve

exercises/hexadecimal/example.js, exercises/hexadecimal/hexadecimal.spec.js
=> add named export to hexadecimal

exercises/sum-of-multiples/example.js, exercises/sum-of-multiples/sum-of-multiples.spec.js
see issue #600 
(I'm not 100% sure about the const name)
=> add named export to sum of multiples

exercises/queen-attack/example.js, exercises/queen-attack/queen-attack.spec.js
=> Add named export queen attack

exercises/palindrome-products/palindrome-products.spec.js
The first test case was not actually checking the returned factors.
=> palindrome-products: check correct value

exercises/list-ops/example.js
Syncs the `example.js` of `list-ops` with the reasonable solution of https://github.com/exercism/website-copy/pull/818.
=> list-ops: match mentor notes reasonable solution

exercises/complex-numbers/complex-numbers.spec.js
Test for `Exponential of a number with real and imaginary part` was missing.
=> complex-numbers: update tests to v1.3.0

exercises/anagram/anagram.spec.js
sync anagram to v1.4.0
See v1.4.0 commit [here](https://github.com/exercism/problem-specifications/commit/baaf0927a8f840aa633bd360c77ee02eaf2ec065#diff-455d887764697eedf47c8297997dc4ff)
=> sync anagram to v1.4.0

Makefile
=> Add checksum for babel config files

exercises/two-fer/README.md
I've been reviewing some solutions to the exercise and have noticed a lot of users simply writing a solution that checks if the name is Alice.
It appears they are not running the tests or not unskipping the other tests.
=> Tweaks to `two-fer` instructions

Makefile
These changes make sure the paths are escaped properly when on Windows.
(waiting on Travis to see if this builds on linux as I don't have that laptop with me today).
**Edit:** It's failing somewhere but I don't know where XD
=> Cross-platform make 

exercises/bob/README.md
I noticed the following test in `bob.spec.js`:
```javascript
xtest('forceful question', () => {
const result = hey('WHAT THE HELL WERE YOU THINKING?');
expect(result).toEqual('Calm down, I know what I\'m doing!');
});
```
...but that wasn't described in `README.md`. 
This adds that description.
=> bob: describe the 'calm down' condition

exercises/list-ops/.meta/HINTS.md
Maybe too wordy for now. We could remove the bullet points and just keep the first blurb.
see exercism/typescript/pull/257
=> Add hints to list-ops

.travis.yml
Test on multiple node versions to ensure nothing breaks for end-users.
=> Configure travis CI matrix

docs/INSTALLATION.md
As discussed in https://github.com/exercism/javascript/pull/690
=> Recommend using LTS in the installation docs

exercises/space-age/README.md
Sorry, this was driving me nuts.
=> [Space Age] Make list consistent, put Earth in proper order

exercises/alphametics/alphametics.js, exercises/atbash-cipher/atbash-cipher.js, exercises/binary-search/binary-search.js, exercises/bowling/bowling.js
* alphametics
* atbash-cipher
* binary-search
* bowling
Part of https://github.com/exercism/javascript/issues/705
=> Add stubs for all exercises - part 1

exercises/meetup/meetup.js
Refactored and renamed function to align with import naming per guidance from tejasbubane.
=> Add meetup stub

exercises/bob/bob.js, exercises/hello-world/hello-world.js
=> Add stub for bob and hello-world exercises

exercises/crypto-square/crypto-square.js
Part of #705 - Add stub for the 'crypto-square' exercise.
=> Add stub for the 'crypto-square' exercise

exercises/react/react.js
=> Add stub file for 'react' excercise

exercises/connect/connect.js
Part of #705 - Add stub for the 'connect' exercise.
=> Add stub for the 'connect' exercise

exercises/circular-buffer/circular-buffer.js
Part of #705 - Add stub for the 'circular-buffer' exercise.
The spec for this one was a bit different from the others, I was not sure what to implement as Skeleton for the Errors.
=> Add stub for the 'circular-buffer' exercise

exercises/word-search/word-search.js, exercises/wordy/wordy.js, exercises/zipper/zipper.js
I've added stubs for **zipper**, **wordy** and **word-search** listed at  #705
=> Add stubs for some exercises #735

exercises/forth/forth.js
This PR is part of #705 and adds a stub file for the "Forth" exercise.
=> Add stub file for "Forth" exercise

exercises/kindergarten-garden/kindergarten-garden.js
This PR is part of #705 and adds a stub file for the "Kindergarten Garden" exercise.
=> Add stub file for "kindergarten garden" exercise

exercises/minesweeper/minesweeper.js
This PR is part of #705 and adds a stub file for the "minesweeper" exercise.
=> Add stub file for "minesweeper" exercise

exercises/change/change.js
Part of #705 
Can you confirm that I'm on the right tracks ? I'll add some more stubs
=> Add stubs for some exercises

exercises/queen-attack/queen-attack.js
This PR is part of #705 and adds a stub file for the "Queen Attack" exercise.
=> Added stub for "Queen Attack" exercise

exercises/saddle-points/example.js, exercises/saddle-points/package.json, exercises/saddle-points/saddle-points.js, exercises/saddle-points/saddle-points.spec.js
=> Update 'Saddle Points' tests and structure of the skeleton file.

exercises/reverse-string/package.json, exercises/reverse-string/reverse-string.spec.js
Added missing test. Synced version number with canonical-data version.
=> Update 'Reverse String' tests

exercises/clock/clock.spec.js, exercises/clock/package.json
Synced tests with canonical data (added two missing tests, regrouped tests).
=> Update 'Clock' tests

exercises/raindrops/package.json, exercises/raindrops/raindrops.spec.js
Synced tests with canonical data.
=> Updated 'Raindrops' tests

exercises/allergies/allergies.spec.js, exercises/allergies/package.json
Synced tests with the canonical data
=> update 'Allergies' tests

exercises/luhn/example.js, exercises/luhn/luhn.js, exercises/luhn/luhn.spec.js, exercises/luhn/package.json
Updated tests, removed class structure and updated the example.
=> Sync Luhn tests with  canonical data version 1.6.1

exercises/armstrong-numbers/armstrong-numbers.js, exercises/armstrong-numbers/armstrong-numbers.spec.js, exercises/armstrong-numbers/example.js, exercises/armstrong-numbers/package.json
Changed function name and added one missing test.
=> Sync Armstrong Numbers tests with canoincal data 1.1.0

exercises/anagram/anagram.js, exercises/anagram/anagram.spec.js, exercises/anagram/example.js, exercises/anagram/package.json
Changed structure and added 2 missing tests.
=> Sync Anagram tests with canonical data version 1.5.0

exercises/protein-translation/protein-translation.spec.js
=> Add test to detect invalid rna sequence.

exercises/sum-of-multiples/example.js, exercises/sum-of-multiples/package.json, exercises/sum-of-multiples/sum-of-multiples.js, exercises/sum-of-multiples/sum-of-multiples.spec.js
Also updated example so all tests are passing for it
=> Sync 'Sum Of Multiples' with canonical data 1.5.0

exercises/isbn-verifier/example.js, exercises/isbn-verifier/isbn-verifier.js, exercises/isbn-verifier/isbn-verifier.spec.js, exercises/isbn-verifier/package.json
=> Sync 'ISBN Verifier' tests with canonical data 2.7.0

exercises/grains/example.js, exercises/grains/grains.js, exercises/grains/grains.spec.js, exercises/grains/package.json
Updated structure, added missing tests, updated example.
=> Sync Grains tests with canonical data 1.2.0

exercises/high-scores/high-scores.spec.js
This fixes a small typo in a test case from high-scores.
=> fix(exercises): Typo in high-scores

exercises/matching-brackets/example.js, exercises/matching-brackets/matching-brackets.js, exercises/matching-brackets/matching-brackets.spec.js, exercises/matching-brackets/package.json
=> Sync 'Matching Brackets' with canonical data 2.0.0

exercises/phone-number/example.js, exercises/phone-number/package.json, exercises/phone-number/phone-number.js, exercises/phone-number/phone-number.spec.js
=> Sync 'Phone Number' tests with canonical-data 1.7.0

config.json, exercises/yacht/.eslintrc, exercises/yacht/README.md, exercises/yacht/babel.config.js, exercises/yacht/example.js, exercises/yacht/package.json, exercises/yacht/yacht.js, exercises/yacht/yacht.spec.js
=> Port Yacht exercise

config/maintainers.json
=> Add Pedro Romano to maintainers.

config/maintainers.json
Adding myself as a new maintainer
=> Add Adam Morris as a new maintainer

config/maintainers.json
Hi there! I'm Ayato from Japan. I'm a new maintainer of JavaScript track.
I'm happy to be part of this community.
Thanks to Exercism I learned a lot about JavaScript, so I want to give back to.
👋
=> Add Ayato Hayashi to maintainers

config/maintainers.json
Unfortunately, for most of the rest of this year, I'm not able to dedicate the minimum weekly time to help with the v3 drive and maintaining the track, so I'm removing myself as maintainer. Please revoke my GitHub privileges also.
=> Remove `paparomeo` from maintainers

exercises/resistor-color/README.md
Ref: https://github.com/exercism/problem-specifications/pull/1645
=> Clarify resistor-color exercise tasks

docs/INSTALLATION.md
Closes https://github.com/exercism/javascript/issues/842
=> Add CLI setup link to installation doc

exercises/meetup/.meta/hints.md, exercises/meetup/README.md, exercises/meetup/example.js, exercises/meetup/meetup.js, exercises/meetup/meetup.spec.js, exercises/meetup/package.json
=> Sync 'Meetup' tests with canonical-data 1.1.0

exercises/armstrong-numbers/armstrong-numbers.js, exercises/bob/bob.js, exercises/difference-of-squares/difference-of-squares.js, exercises/dnd-character/dnd-character.js, exercises/etl/etl.js, exercises/high-scores/high-scores.js, exercises/list-ops/list-ops.js, exercises/nth-prime/nth-prime.js, exercises/nucleotide-count/nucleotide-count.js, exercises/resistor-color-trio/resistor-color-trio.js, exercises/sum-of-multiples/sum-of-multiples.js, exercises/variable-length-quantity/variable-length-quantity.js
=> Update stub files

exercises/beer-song/beer-song.spec.js, exercises/diamond/diamond.spec.js, exercises/difference-of-squares/difference-of-squares.spec.js, exercises/dnd-character/dnd-character.spec.js, exercises/simple-cipher/simple-cipher.spec.js
=> Update test files

config.json, exercises/dominoes/.eslintrc, exercises/dominoes/.npmrc, exercises/dominoes/README.md, exercises/dominoes/babel.config.js, exercises/dominoes/dominoes.js, exercises/dominoes/dominoes.spec.js, exercises/dominoes/example.js, exercises/dominoes/package.json
=> add exercise dominoes

exercises/resistor-color/.meta/hints.md, exercises/resistor-color/README.md
=> resistor-color: Improve instructions

.github/stale.yml
stale-bot is no longer used, and frankly, I don't think issues should be
ignored ever in the first place. Let's do this manually for now.
=> Remove stale.yml

config.json, exercises/bank-account/.eslintrc, exercises/bank-account/.npmrc, exercises/bank-account/README.md, exercises/bank-account/babel.config.js, exercises/bank-account/bank-account.js, exercises/bank-account/bank-account.spec.js, exercises/bank-account/example.js, exercises/bank-account/package.json
To finish https://github.com/exercism/javascript/pull/768
=> New exercise : bank account

exercises/grade-school/.meta/tests.toml
Upstream: https://github.com/exercism/problem-specifications/pull/1760
Ping @SleeplessByte.
=> grade-school: Change a UUID to be version 4

config.json, exercises/square-root/.eslintrc, exercises/square-root/.meta/hints.md, exercises/square-root/.meta/tests.toml, exercises/square-root/.npmrc, exercises/square-root/README.md, exercises/square-root/babel.config.js, exercises/square-root/example.js, exercises/square-root/package.json, exercises/square-root/square-root.js, exercises/square-root/square-root.spec.js
=> Adding square-root exercise

exercises/alphametics/alphametics.spec.js, exercises/alphametics/example.js
This PR addresses [Issue 897](https://github.com/exercism/javascript/issues/897).
I refactored the example solution using [my solution](https://github.com/slaymance/exercism/blob/master/javascript/alphametics/alphametics.js) to alphametics as a guideline. The example implementation struggled a bit with the last test because we would replace each letter with a number every time we wanted to test a permutation. I refactored it so that we sum up the places of each letter and then multiply that sum by a number for each permutation, which is much faster than replacing each letter individually. For example:
```javascript
// If we have the string 'MOM':
{
'M': 10 ** 2 + 10 ** 0, // === 101
'O': 10 ** 1 // === 10
}
// and if we want to test M = 9 and O = 2:
{
'M': 909, // === 101 * 9
'O': 20 // …
```
=> alphametics: optimise implementation for last test

config.json
=> [v3] Update status of track

config.json
Used https://github.com/exercism/javascript/issues/951#issuecomment-778834953 to update the status for most of the concept exercises.
Fixes #965
=> Update status based on perceived state

config.json
Fixes #958 
@TomPradat can you see what you think?
=> [V3] Add key features

.github/workflows/action-format.yml, .github/workflows/action-sync.yml
Allows to use `/sync` to sync all exercises.
=> Add sync workflow

exercises/concept/annalyns-infiltration/.meta/config.json, exercises/concept/array-loops/.meta/config.json, exercises/concept/closures/.meta/config.json, exercises/concept/elyses-analytic-enchantments/.meta/config.json, exercises/concept/elyses-destructured-enchantments/.meta/config.json, exercises/concept/elyses-enchantments/.meta/config.json, exercises/concept/elyses-transformative-enchantments/.meta/config.json, exercises/concept/freelancer-rates/.meta/config.json, exercises/concept/fruit-picker/.meta/config.json, exercises/concept/lasagna/.meta/config.json, exercises/concept/lucky-numbers/.meta/config.json, exercises/concept/nullability/.meta/config.json, exercises/concept/promises/.meta/config.json, exercises/concept/recursion/.meta/config.json, exercises/concept/strings/.meta/config.json, exercises/concept/vehicle-purchase/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
=> 🤖 Flatten authors and contributors in .meta/config.json files

exercises/practice/forth/.meta/config.json
=> forth: added contributor

config.json
Fixes the configlet linter errors that occured in the latest version.
=> Add missing exercise names

exercises/practice/binary-search-tree/binary-search-tree.js, exercises/practice/pythagorean-triplet/pythagorean-triplet.js, exercises/practice/rectangles/.meta/proof.ci.js, exercises/practice/rectangles/rectangles.js, exercises/practice/rectangles/rectangles.spec.js, scripts/ci, scripts/lint, scripts/pr
See the commit titles for the minor fixes
=> Various minor fixes

config.json
- Removed 2 prerequisites that don't exist. I expect these to be added back when we add the exercises.
- Ordered the concept exercises in perceived difficulty and expected order of completion IF it was a list of exercises
=> Re-order concept exercises

scripts/name-check, scripts/name-uniq
This will correctly set the exit code and show failures on the name checks
=> Fix name check workflows

config.json
=> Add sets to the list of concepts

concepts/array-loops/.meta/config.json, concepts/errors/.meta/config.json, concepts/rest-elements/.meta/config.json, concepts/spread-elements/.meta/config.json, concepts/spread-operator/.meta/config.json, concepts/string-formatting/.meta/config.json, concepts/type-conversion/.meta/config.json, concepts/variable-parameters/.meta/config.json
=> Add missing authors and contributors

config.json
I'd suggest adding a `spread-operator` concept, what do you think ?
=> Add prerequisites for kindergarten-garden

exercises/practice/hello-world/hello-world.js
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

exercises/concept/annalyns-infiltration/.docs/hints.md
Two small problems:
- Hints for step 2 didn't show up because of a heading mismatch with the instructions.
- There were no hints for step 4. I don't know if you want any. I came up with one new hint that doesn't show up in the other steps that might make sense.
=> Concept exercise review: annalyns-infiltration

CONTRIBUTING.md, TAGS.md, concepts/callbacks/links.json, concepts/errors/introduction.md, concepts/numbers/about.md, concepts/strings/introduction.md, exercises/concept/errors/.docs/instructions.md, exercises/concept/errors/.docs/introduction.md, exercises/concept/freelancer-rates/.docs/hints.md, exercises/concept/mixed-juices/.meta/design.md, exercises/concept/translation-service/.meta/exemplar.alternative.js, exercises/concept/translation-service/.meta/exemplar.js, exercises/concept/translation-service/service.js, exercises/practice/anagram/.meta/proof.ci.js, exercises/practice/bowling/bowling.spec.js, exercises/practice/change/.meta/proof.ci.js, exercises/practice/linked-list/.docs/instructions.append.md, exercises/practice/linked-list/linked-list.spec.js, exercises/practice/proverb/proverb.spec.js, reference/exercise-concepts/beer-song.md, reference/implementing-a-concept-exercise.md, reference/keywords/export.md, reference/keywords/import.md, scripts/pr-check
Just a whole bunch of random typos. I used my IDE's typo-finding features.
=> Fix a whole bunch of typos

exercises/concept/poetry-club-door-policy/.docs/instructions.md, exercises/concept/poetry-club-door-policy/door-policy.spec.js
Hello! I solved this exercise for the first time just now and I would like to propose some tiny fixes.
I also opened an issue for a problem that I didn't feel comfortable fixing myself (https://github.com/exercism/javascript/issues/1224)
=> Concept exercise review: poetry-club-door-policy

CONTRIBUTING.md, scripts/ci-check, scripts/directory-check, scripts/pr-check
- Added script `scripts/directory-check` to check if `directory` field in the package.json for each exercise is correct.
- Added documentation in CONTRIBUTING.md for `directory-check` script
- Run `directory-check` script from `ci-check` and `pr-check` scripts in the integrity check step.
Ref Issue: #1013
=> Issue1013:  CI should check if repository value of package.json is sane

exercises/concept/poetry-club-door-policy/door-policy.spec.js
=> Add `trim()` test for `poetry-club-door-policy`

exercises/concept/elyses-destructured-enchantments/.meta/config.json, exercises/concept/elyses-looping-enchantments/.meta/config.json
Re-use the icon from `elyses-enchantments` as otherwise the icon will be missing for these exercises.
=> Use the `elyses-enchantments` icon for new exercises

exercises/concept/bird-watcher/bird-watcher.spec.js, exercises/concept/lasagna/lasagna.spec.js, exercises/concept/poetry-club-door-policy/door-policy.spec.js, exercises/concept/vehicle-purchase/vehicle-purchase.spec.js
```sh
cd exercises/concept
sed -i 's/xit/it/g' ./**/*.spec.js
sed -i 's/xtest/test/g' ./**/*.spec.js
sed -i 's/xdescribe/describe/g' ./**/*.spec.js
```
Closes https://github.com/exercism/javascript/issues/1299
=> Unskip all tests for Concept Exercises

docs/ABOUT.md, docs/LEARNING.md
Closes https://github.com/exercism/javascript/issues/1272
=> Minor changes to docs

exercises/concept/bird-watcher/bird-watcher.js, exercises/concept/lasagna/lasagna.js, exercises/concept/ozans-playlist/ozans-playlist.js, exercises/concept/vehicle-purchase/vehicle-purchase.js
Changes methods to function in concept exercise in bird-watcher, lasagna, ozans-playlist, vehicle-purchase files.
Fixes #1298
=> Fix: method -> function in concept exercise

config.json
This fixes the new configlet error. I will leave a note about this change in the concept tree issue so we know what to add back in later.
=> Fix Prerequisites

.github/workflows/action-format.yml, .github/workflows/verify-code-formatting.yml, CONTRIBUTING.md, bin/check-formatting.sh, bin/format.sh, package-lock.json, scripts/pr-check
Issue #1196
Include check in the PR pre check to validate if ENV EXERCISM_PRETTIER_VERSION matches prettier in package.json, if not, set version in package.json to ENV.
=> Add check if EXERCISM_PRETTIER_VERSION matches prettier in package.json #1196

.github/workflows/pr.ci.js.yml, babel.config.js, bin/check_corejs_version.sh
This closes https://github.com/exercism/javascript/issues/1182.
=> feat: Check corejs version in babel configuration versus package.json

exercises/concept/amusement-park/.meta/exemplar.js, exercises/concept/coordinate-transformation/.meta/exemplar.js, exercises/concept/elyses-analytic-enchantments/.meta/exemplar.js, exercises/concept/elyses-destructured-enchantments/.meta/exemplar.js, exercises/concept/elyses-destructured-enchantments/enchantments.js, exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js, exercises/concept/elyses-transformative-enchantments/enchantments.js, exercises/concept/elyses-transformative-enchantments/enchantments.spec.js, exercises/concept/factory-sensors/.meta/exemplar.js, exercises/concept/fruit-picker/.meta/env.d.ts, exercises/concept/fruit-picker/.meta/exemplar.js, exercises/concept/high-score-board/.meta/exemplar.js, exercises/concept/lasagna-master/.meta/exemplar.js, exercises/concept/mixed-juices/.meta/exemplar.js, exercises/concept/pizza-order/.meta/env.d.ts, exercises/concept/pizza-order/.meta/exemplar.js, exercises/concept/translation-service/.meta/env.d.ts, exercises/concept/translation-service/.meta/exemplar.alternative.js, exercises/concept/translation-service/.meta/exemplar.js, exercises/concept/translation-service/service.js
I found out my editor did not show me the ts-check issues at all. I fixed the editor setting and then fixed all the typing issues.
This PR contains
* removing env.d.ts files as they are not needed anymore
* fix typing issues
* fix typing import paths in exemplar.js files
=> Fix all ts-check issues in concept exercises

concepts/array-analysis/.meta/config.json, concepts/callbacks/.meta/config.json, concepts/promises/.meta/config.json
This PR contains
- blurb for callbacks
- blurb for promises
- blurb for array-analysis
=> Added blurbs for callbacks, promises, and array-analysis

concepts/basics/.meta/config.json, concepts/basics/about.md, concepts/basics/introduction.md, exercises/concept/lasagna/.docs/instructions.md, exercises/concept/lasagna/.docs/introduction.md, exercises/concept/lasagna/.meta/config.json, exercises/concept/lasagna/.meta/design.md, exercises/concept/lasagna/.meta/exemplar.js, exercises/concept/lasagna/lasagna.js, exercises/concept/lasagna/lasagna.spec.js
* Remove some contradictory text on variable naming in the concept
* Move content to the correct headers in the concept
* Add mention of Lucian to the instructions (as he is mentioned in the name of the exercise)
* Fix some typos
* Fix test names and structure
* Remove long comment from exemplar as we use exemplar as "mentor notes"
* Credit the actual reference implementation (C#) in "forked_from"
=> Minor fixes for the Lasagna (basics) exercise and concept

exercises/concept/vehicle-purchase/vehicle-purchase.spec.js
The second test of 'calculateResellPrice' tests was faulty.
=> fixing a test of 'calculateResellPrice' on vehicle-purchase.spec.js

exercises/concept/elyses-analytic-enchantments/.meta/exemplar.js, exercises/concept/elyses-analytic-enchantments/enchantments.js
Enhancing the JsDoc description of the return value so that it matches what is described on the exercise description on the README.md file.
=> Updating Elyses Analytic Enchantment JSDoc

exercises/concept/translation-service/.meta/config.json, exercises/concept/translation-service/service.spec.js
Reference [Jest](https://jestjs.io/docs/asynchronous)
Related to issue https://github.com/exercism/javascript/issues/1358
=> fix: :white_check_mark: fix test cases to consider promises

exercises/practice/zipper/.meta/tests.toml, exercises/practice/zipper/zipper.spec.js
=> Add test case for practice/zipper. Fix #902

exercises/practice/word-search/.meta/tests.toml, exercises/practice/word-search/word-search.spec.js
=> Sync word search exercise #903

config.json, exercises/practice/promises/.docs/instructions.md, exercises/practice/promises/.docs/introduction.md
=> Clarify the 'promises' exercise instructions

exercises/concept/elyses-enchantments/.docs/instructions.md, exercises/concept/elyses-enchantments/.meta/config.json, exercises/concept/elyses-enchantments/.meta/exemplar.js
=> Improve Concept Exercise Elyses Enchantments - Array

concepts/arrays/.meta/config.json, concepts/arrays/about.md, concepts/arrays/introduction.md, exercises/concept/elyses-enchantments/.docs/introduction.md
=> Introduction for Elyses Enhancements - Concept arrays

exercises/concept/poetry-club-door-policy/.meta/exemplar.js, exercises/concept/poetry-club-door-policy/door-policy.spec.js
Suggest removing some of the logic in the tests to make them more easily readable by the learners at this stage in the exercises.
=> Simplify tests for Poetry Club Door Policy

exercises/practice/hamming/.meta/proof.ci.js, exercises/practice/hamming/.meta/tests.toml, exercises/practice/hamming/hamming.spec.js
=> Update hamming exercise to the latest specs

exercises/concept/custom-signs/.meta/exemplar.js, exercises/concept/custom-signs/custom-signs.spec.js
=> Customs Signs fix "!"

exercises/concept/lasagna/lasagna.js
Instead of amount of minutes, number of minutes.
=> amount >> number

exercises/practice/nucleotide-count/.meta/proof.ci.js, exercises/practice/nucleotide-count/nucleotide-count.js, exercises/practice/nucleotide-count/nucleotide-count.spec.js
=> fix: removed unnecessary class from nucleotide count

exercises/practice/nucleotide-count/.docs/instructions.append.md
This PR is related to issue #1474
=> Add return instruction to nucleotide-count

exercises/concept/high-score-board/.docs/instructions.md
Step 4: Adding 73 to player score should update to 12771081 instead of 12771091
=> fix math error

concepts/arithmetic-operators/about.md, concepts/arithmetic-operators/introduction.md, exercises/concept/freelancer-rates/.docs/introduction.md
Fixed some wrong result in the docs.
=> Fixed example exponentiation operator result.

config.json, exercises/practice/zebra-puzzle/.docs/instructions.append.md, exercises/practice/zebra-puzzle/.docs/instructions.md, exercises/practice/zebra-puzzle/.eslintrc, exercises/practice/zebra-puzzle/.meta/config.json, exercises/practice/zebra-puzzle/.meta/proof.ci.js, exercises/practice/zebra-puzzle/.meta/tests.toml, exercises/practice/zebra-puzzle/.npmrc, exercises/practice/zebra-puzzle/LICENSE, exercises/practice/zebra-puzzle/babel.config.js, exercises/practice/zebra-puzzle/package.json, exercises/practice/zebra-puzzle/zebra-puzzle.js, exercises/practice/zebra-puzzle/zebra-puzzle.spec.js
=> Added new exercise: zebra-puzzle

config.json
Accumulate: Deprecate Exercise 
closes #1509
=> Accumulate: Deprecate Exercise

exercises/practice/rotational-cipher/.meta/proof.ci.js, exercises/practice/rotational-cipher/rotational-cipher.js, exercises/practice/rotational-cipher/rotational-cipher.spec.js
=> fix: remove unnessary class in rotational-cipher

exercises/concept/custom-signs/.docs/hints.md, exercises/concept/custom-signs/.docs/instructions.md
Hi! Small PR to fix broken numeration in the docs for custom-signs exercise.
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
=> [custom-signs] Fix wrong numeration in the docs

exercises/concept/custom-signs/.docs/instructions.md, exercises/concept/custom-signs/.meta/exemplar.js, exercises/concept/custom-signs/custom-signs.spec.js
Hello!
This PR is to address the issue I raised in [Issue #1524 ](https://github.com/exercism/javascript/issues/1524).
As per June's advice, I changed "old" to "mature" so as to be friendly to non-native speakers of English.
Cheers!
=> Correct grammar as per Issue #1524

config.json, exercises/practice/tournament/.docs/instructions.md, exercises/practice/tournament/.eslintrc, exercises/practice/tournament/.meta/config.json, exercises/practice/tournament/.meta/proof.ci.js, exercises/practice/tournament/.meta/tests.toml, exercises/practice/tournament/.npmrc, exercises/practice/tournament/LICENSE, exercises/practice/tournament/babel.config.js, exercises/practice/tournament/package.json, exercises/practice/tournament/tournament.js, exercises/practice/tournament/tournament.spec.js
=> Added new exercise: tournament

.gitignore, exercises/concept/coordinate-transformation/.docs/instructions.md, exercises/concept/coordinate-transformation/.meta/exemplar.js, exercises/concept/coordinate-transformation/coordinate-transformation.js
=> feat: minor text fixes

exercises/practice/bank-account/bank-account.spec.js
=> Add new test case to 'bank-account' exercise

exercises/concept/elyses-looping-enchantments/.docs/introduction.md
I just saw these two tiny typo's. So here is a fix.
=> Fix two small typos for elyses looping enchantments

config.json, exercises/practice/rest-api/.docs/instructions.append.md, exercises/practice/rest-api/.docs/instructions.md, exercises/practice/rest-api/.eslintrc, exercises/practice/rest-api/.meta/config.json, exercises/practice/rest-api/.meta/proof.ci.js, exercises/practice/rest-api/.meta/tests.toml, exercises/practice/rest-api/.npmrc, exercises/practice/rest-api/LICENSE, exercises/practice/rest-api/babel.config.js, exercises/practice/rest-api/package.json, exercises/practice/rest-api/rest-api.js, exercises/practice/rest-api/rest-api.spec.js
=> Added new exercise: rest-api

exercises/practice/gigasecond/.docs/instructions.append.md
Add a note in the instructions.append.md file that the input and output of the gigasecond function is of type Date.
closes #1564
=> Add note in the instructions.append.md

config.json
I have added the prerequisites for the phone number exercise
references #984
=> add prerequisities for phone number exercise

config.json
I have added the prerequisites for the high scores exercise.
references #984
=> add prerequisities for high scores exercise

config.json, exercises/practice/knapsack/.docs/instructions.md, exercises/practice/knapsack/.eslintrc, exercises/practice/knapsack/.meta/config.json, exercises/practice/knapsack/.meta/proof.ci.js, exercises/practice/knapsack/.meta/tests.toml, exercises/practice/knapsack/.npmrc, exercises/practice/knapsack/LICENSE, exercises/practice/knapsack/babel.config.js, exercises/practice/knapsack/knapsack.js, exercises/practice/knapsack/knapsack.spec.js, exercises/practice/knapsack/package.json
=> Added new exercise: Knapsack

exercises/concept/elyses-enchantments/.docs/hints.md, exercises/concept/elyses-enchantments/.docs/instructions.md, exercises/concept/elyses-enchantments/.meta/config.json
The exercise "Elyses Enchantments" had instructions that did not match the order in which they appeared in the online editor.
I switched the position of the instructions based on the order they had in the code. I also reordered the hints for each task so that they matched the new order.
=> Reordered task instructions in Elyses Enchantments exercise

README.md, docs/ABOUT.md, docs/INSTALLATION.md, docs/ROADMAP.md, docs/TESTS.md, reference/keywords/async.md, reference/keywords/const.md, reference/keywords/export.md, reference/keywords/import.md
Some minor changes to improve the grammar in the documentation.
=> Fix typos and grammar in documentation

concepts/array-transformations/about.md, concepts/array-transformations/introduction.md, config.json, exercises/concept/elyses-transformative-enchantments/.docs/hints.md, exercises/concept/elyses-transformative-enchantments/.docs/instructions.md, exercises/concept/elyses-transformative-enchantments/.docs/introduction.md, exercises/concept/elyses-transformative-enchantments/.meta/config.json, exercises/concept/elyses-transformative-enchantments/.meta/design.md, exercises/concept/elyses-transformative-enchantments/.meta/exemplar.js, exercises/concept/elyses-transformative-enchantments/enchantments.js, exercises/concept/elyses-transformative-enchantments/enchantments.spec.js, exercises/concept/elyses-transformative-enchantments/package.json
Resolves #1326 (the remaining todos)
Note that the exercise might have some ambiguities currently to whether the original array can be modified or not. For some cases, like when we expect the student to use `map`, I added a test case to clarify the expected behavior. For other cases it is left up to the student for now. Let's see how this is received first. If a lot of students are confused, we can still add more clarification later.
=> Improve Elyses Transformative Enchantments

concepts/array-transformations/about.md, concepts/array-transformations/introduction.md, exercises/concept/elyses-transformative-enchantments/.docs/introduction.md
arr.slice(1, 2) should be [2] instead of [1]
=> Fix error in slice example

concepts/array-transformations/about.md, concepts/array-transformations/introduction.md
A couple files that are updated based on the PR from @ngl4 earlier - https://github.com/exercism/javascript/pull/1601
=> Additional update to Array Transformations

exercises/concept/bird-watcher/.docs/instructions.md
=> Improve instructions for task 3

exercises/concept/bird-watcher/.docs/instructions.md
Besides some people just hating for loops, it also seems a lot of students are not aware that for loops are the concept "under practice" here. For example because they skip over the introduction or in general because people don't have a good understanding of what learning exercises are, some just seem to treat them as "oh, a new practice exercise in the JS track".
I realized that the instructions currently don't mention that a for loop should be used at all. Since the tasks itself don't really force that either, I added a sentence to the instructions to clarify this. Maybe this will help.
=> Bird Watcher: Add clarification that for loop should be used

.github/workflows/action-format.yml, .github/workflows/action-sync.yml
github actions script gets updated frequently and this version is outdated.
=> Remove actions versions

config.json, exercises/practice/satellite/.docs/instructions.append.md, exercises/practice/satellite/.docs/instructions.md, exercises/practice/satellite/.eslintrc, exercises/practice/satellite/.meta/config.json, exercises/practice/satellite/.meta/proof.ci.js, exercises/practice/satellite/.meta/tests.toml, exercises/practice/satellite/.npmrc, exercises/practice/satellite/LICENSE, exercises/practice/satellite/babel.config.js, exercises/practice/satellite/package.json, exercises/practice/satellite/satellite.js, exercises/practice/satellite/satellite.spec.js
=> Added new exercise: Satellite

config.json
Add `prerequisites` for the following:
```
dominoes
say
diamond
rational-numbers
sublist
```
relates to #985
=> #985 - Add Prerequisite to Exercises - Part 2

exercises/practice/say/.meta/config.json, exercises/practice/say/.meta/proof.ci.js, exercises/practice/say/say.js, exercises/practice/say/say.spec.js
Fixes https://github.com/exercism/javascript/issues/1624
=> Remove unnessary class

exercises/concept/lucky-numbers/.docs/introduction.md
=> minor grammar fix #2

config.json
```
binary-search-tree
custom-set
binary-search
circular-buffer
simple-linked-list
```
relates to #985
=> #985 - Add Prerequisites for Exercises - Part 3

exercises/concept/amusement-park/.docs/instructions.md
The function name on question no.4 example should be simpleTicketStatus instead of ticketStatus.
=> Docfix(amusement-park): Fix ticketStatus function wording

concepts/null-undefined/introduction.md
The footnote on line 27 wasn't clickable
=> Fix broken footnote link

exercises/practice/anagram/.docs/instructions.md, exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/anagram.spec.js
I synced the anagram exercise with problem spec. I did this as to test the new configlet release and learn about the commands. 
(I plan to create issues for syncing exercises at some point in the future.)
=> Update anagram to latest problem spec version

concepts/promises/introduction.md
Line 13 using Math.ceil() in that manner never generates 0, so that the value '2' which is sampleData[0] remains unreffered.
This is a confusing randomization result.
One of the possible solutions (not quiet sure if suitable) is:
let randomNumber = Math.floor(Math.random() * (sampleData.length + 1));
The problem appears in Translation Service exerсise as well.
=> unreachable [0] index in the 1st example

concepts/callbacks/introduction.md, exercises/concept/fruit-picker/.docs/introduction.md
I was struggling with understanding callbacks so tried the first example in the introduction in a code playground only to find that `applyToSquare(areaOfSquare);` actually returns `undefined` rather than the expected `25`. Added the missing return keyword so it works as expected (unless I am misunderstanding something?)
=> [ exercises/concept/fruit-picker ] Add missing return keyword in applyToSquare function

config.json, exercises/practice/poker/.docs/instructions.md, exercises/practice/poker/.eslintrc, exercises/practice/poker/.meta/config.json, exercises/practice/poker/.meta/proof.ci.js, exercises/practice/poker/.meta/tests.toml, exercises/practice/poker/.npmrc, exercises/practice/poker/LICENSE, exercises/practice/poker/babel.config.js, exercises/practice/poker/package.json, exercises/practice/poker/poker.js, exercises/practice/poker/poker.spec.js
=> Added new exercise: Poker

exercises/concept/annalyns-infiltration/annalyns-infiltration.js, exercises/concept/freelancer-rates/freelancer-rates.js, exercises/concept/lasagna/lasagna.js, exercises/concept/poetry-club-door-policy/door-policy.js
Closes #1682
Updated error messages in `basics` exercises
=> Ask students to remove throw statements

exercises/concept/translation-service/.docs/instructions.md
"out of space" => "outer space"
=> Fixes a typo

exercises/concept/translation-service/.docs/instructions.md
In this tutorial, I often couldn't tell if a problem was due to a misunderstanding of promises or due to my misunderstanding of the API .  To help with this:
* I've edited the instructions to give more detailed description of the API and remove ambiguity (so users can put their focus on learning promises).
* I've also added a bit of clean up, fixed some typos and restructured to help the flow and uniformity (It looks like there were two different authors with different writing styles and emphasis).
I hope you guys find this an improvement.
=> [tracks/javascript/exercises/translation-service] Update instructions.md 

concepts/template-strings/about.md, concepts/template-strings/introduction.md, exercises/concept/custom-signs/.docs/introduction.md
I found a slightly outdated reference while going through the concept exercises.
=> Update exercism.io into exercism.org in Template Strings concept

.github/workflows/ci.js.yml, .github/workflows/pr.ci.js.yml
https://nodejs.org/en/blog/announcements/v18-release-announce/
=> Add node 18 to CI

concepts/arrays/about.md, concepts/arrays/introduction.md, exercises/concept/elyses-enchantments/.docs/introduction.md
hello, found a missing return value
=> Add splice return value

concepts/functions/about.md, concepts/functions/introduction.md, exercises/concept/lasagna-master/.docs/introduction.md
This applies the review comments that should have been provided for https://github.com/exercism/javascript/pull/1693.
* Adding some important sentences back in that were deleted.
* Parentheses vs. brackets vs. braces is very hard for non-native speakers so we stick with the easier version.
* Introduction of concept and exercise should only have minimal info.
* Moving a sentence about argument order to the section about invocation.
* Removing one long example that added little value.
No new content was added, I just reverted some parts to what they were before.
=> Function concept fixes

exercises/concept/lasagna-master/.docs/instructions.md
While reading through some of the instructions in this exercise's tasks there were a couple of places that seemed to have typos or small mistakes that didn't quite flow right. This PR attempts to adjust those slightly so they read more naturally.
Hope this helps and thanks for all the great work on this project!
=> Lasagna Master Exercise: Adjust wording for instructions to flow better

concepts/array-loops/about.md, concepts/array-loops/introduction.md, exercises/concept/elyses-looping-enchantments/.docs/introduction.md
Replaced "for .. of" with "for...of"
=> Fixed Typo

exercises/concept/coordinate-transformation/.docs/instructions.md
Discussed in [Clarification of memoization in exercise coordinate-transformation](https://github.com/exercism/javascript/issues/1782)
Clarify the concept of memoization raised in exercise `coordinate-transformation`.
- Improve wording about the relationship between memoization and dynamic programming
- Emphasize that the exercise only want the last result to be remembered, so the learner would less likely get confused and try to remember all results
=> Clarify memoization

.github/org-wide-files-config.toml, exercises/concept/fruit-picker/.meta/config.json, exercises/practice/poker/.meta/config.json
Ref: https://github.com/exercism/fsharp/pull/1066/files
Also ran `bin/configlet fmt --update --yes` with latest configlet
=> Enable configlet fmt in CI

.prettierignore
This is needed so we can then merge https://github.com/exercism/javascript/pull/1823
=> Exclude more org wide files from formatting

exercises/concept/bird-watcher/.docs/instructions.md
Add missing "to".
> To practice, use a for loop **to** solve each of the tasks below.
=> Fix typo in bird-watcher/.docs/instructions.md

exercises/concept/poetry-club-door-policy/.docs/instructions.md, exercises/concept/poetry-club-door-policy/door-policy.spec.js
=> Add test case for poetry door club policy

exercises/concept/elyses-analytic-enchantments/.meta/exemplar.js, exercises/concept/elyses-analytic-enchantments/enchantments.js
An correct solution does not follow type checking as stack.find() could return undefined.
=> Fix typecheck error on function getFirstOddCard

exercises/concept/lucky-numbers/.meta/exemplar.js, exercises/concept/lucky-numbers/lucky-numbers.js
=> Fix jsdoc typos in lucky-numbers

exercises/concept/freelancer-rates/.docs/instructions.md
I livestreamed the Freelancer Rates exercise today and was overjoyed by the recent update to use more inclusive language! However, a couple of pronouns remained which are corrected here.
=> fix pronoun inconsistencies

exercises/practice/grains/.approaches/bit-shifting/content.md, exercises/practice/grains/.approaches/bit-shifting/snippet.txt, exercises/practice/grains/.approaches/config.json, exercises/practice/grains/.approaches/exponentiation/content.md, exercises/practice/grains/.approaches/exponentiation/snippet.txt, exercises/practice/grains/.approaches/introduction.md, exercises/practice/leap/.approaches/boolean-chain/content.md, exercises/practice/leap/.approaches/boolean-chain/snippet.txt, exercises/practice/leap/.approaches/config.json, exercises/practice/leap/.approaches/introduction.md, exercises/practice/leap/.approaches/new-date-getmonth/content.md, exercises/practice/leap/.approaches/new-date-getmonth/snippet.txt, exercises/practice/leap/.approaches/switch-statement/content.md, exercises/practice/leap/.approaches/switch-statement/snippet.txt, exercises/practice/leap/.approaches/ternary-operator/content.md, exercises/practice/leap/.approaches/ternary-operator/snippet.txt
Should be pretty much there, except for formatting.
=> Grains approaches

exercises/concept/regular-chatbot/.docs/instructions.md, exercises/concept/regular-chatbot/.docs/introduction.md
This pull request fixes one error in the explanations for `match()`.
The other changes update the instructions to match what the spec file requires.
=> Fix minor inconsistencies in regular-chatbot instructions.

exercises/concept/regular-chatbot/.docs/instructions.md
I had a hard time making it produce the output the instructions suggested. :)
=> Fix typo in example output

exercises/concept/regular-chatbot/regular-chatbot.js
Aligned the comments to follow the same format. Also fixed a small typo and reworded the description of the last function.
=> Improve comments to be more in line and fix one typo

exercises/concept/elyses-enchantments/.docs/instructions.md
As some people are getting stuck/confused by the fact that the functions should both mutate and return, let's be super-specific about it.
=> [elyses-enchantments] Be super explicit about mutation+return

exercises/practice/simple-cipher/.docs/instructions.md
As per problem-specifications: https://github.com/exercism/problem-specifications/pull/2183
=> Minor update in simple-cipher wording

concepts/objects/introduction.md
=> Fix a typo

exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/saddle-points/.meta/config.json
https://github.com/exercism/problem-specifications/pull/2272
=> saddle-points: Fix row values in instructions

concepts/array-transformations/about.md, concepts/array-transformations/introduction.md
Fix error in definition of `slice()` method
=> Array transformations doc update

.github/workflows/action-format.yml, .github/workflows/ci.js.yml, .github/workflows/pr.ci.js.yml, .github/workflows/verify-code-formatting.yml
=> Bump node LTS to v18 and add v20 to CI

exercises/concept/pizza-order/.docs/hints.md, exercises/concept/pizza-order/.docs/instructions.md, exercises/concept/pizza-order/.docs/introduction.md, exercises/concept/pizza-order/.meta/config.json
This is the PR in response to #945. I've added `hints.md`, `instructions.md`, and `introduction.md`.
For `.docs/about.md`, I couldn't find any file like that in other JS exercises - could you explain further what I'm supposed to write in that file? Or do you maybe mean `concepts/recursion/about.md`? I also couldn't find `languages/javascript/exercises/concept/README.md`. In this repo, I'm guessing we should fill out `concepts/recursion/introduction.md` - but what should I put in that file vs. `.docs/introduction.md`? I looked around in other concept exercises but couldn't understand still.
Let me know what I should change or add here.
=> Add basic files for Pizza Order exercise

.github/workflows/action-format.yml, .github/workflows/action-sync.yml
(as title)
Same as https://github.com/exercism/typescript/pull/1346
=> Fix broken Github Actions

exercises/concept/poetry-club-door-policy/door-policy.spec.js
[Forum thread](https://forum.exercism.org/t/poetry-club-door-policy-add-test/6299).
=> [Poetry Club Door Policy] Change tests 

exercises/practice/scale-generator/.docs/instructions.md, exercises/practice/scale-generator/.meta/proof.ci.js, exercises/practice/scale-generator/scale-generator.spec.js
This PR will hopefully resolve this issue: https://github.com/exercism/javascript/issues/1906
=> Improve Scale Generator tests and description

exercises/concept/factory-sensors/factory-sensors.spec.js
Perhaps should read "equal to" but decided to make it match the following test.
=> [typo] Change "equals to" => of

exercises/concept/lucky-numbers/.docs/instructions.md
See: https://forum.exercism.org/t/ad-link-in-lucky-numbers-exercise/8204/2
=> fix: change story website to non-existant destination

config.json, exercises/practice/pop-count/package.json, exercises/practice/pop-count/pop-count.js
@ErikSchierboom I updated some things on `pop-count` and fixed a mistake I'd made. 
Also, sorry for tagging unnecessary.
=> Adding some credits and prerequisites

config.json, exercises/practice/parallel-letter-frequency/.docs/instructions.append.md, exercises/practice/parallel-letter-frequency/.docs/instructions.md, exercises/practice/parallel-letter-frequency/.eslintrc, exercises/practice/parallel-letter-frequency/.gitignore, exercises/practice/parallel-letter-frequency/.meta/config.json, exercises/practice/parallel-letter-frequency/.meta/proof.ci.js, exercises/practice/parallel-letter-frequency/.meta/tests.toml, exercises/practice/parallel-letter-frequency/.npmrc, exercises/practice/parallel-letter-frequency/LICENSE, exercises/practice/parallel-letter-frequency/babel.config.js, exercises/practice/parallel-letter-frequency/package.json, exercises/practice/parallel-letter-frequency/parallel-letter-frequency.js, exercises/practice/parallel-letter-frequency/parallel-letter-frequency.spec.js, exercises/practice/pop-count/package.json
Adding a new exercise ` parallel-letter-frequency`
I also want to write up something about a web worker solution (maybe an approach or an article) but i might need some help with that, maybe in a separate PR or in a follow-up commit to this one. Opinions on that are appreciated.
=> [New Exercise] Parallel letter frequency

config.json, exercises/practice/bottle-song/.docs/instructions.md, exercises/practice/bottle-song/.eslintrc, exercises/practice/bottle-song/.gitignore, exercises/practice/bottle-song/.meta/config.json, exercises/practice/bottle-song/.meta/proof.ci.js, exercises/practice/bottle-song/.meta/tests.toml, exercises/practice/bottle-song/.npmrc, exercises/practice/bottle-song/LICENSE, exercises/practice/bottle-song/babel.config.js, exercises/practice/bottle-song/bottle-song.js, exercises/practice/bottle-song/bottle-song.spec.js, exercises/practice/bottle-song/package.json
I don't know if these should have been two seprate PRs. Tell me if you want me to split the deprecation into it's own PR.
=> [New Exercise] Adding `bottle-count` and depricating `beer-count`

exercises/concept/regular-chatbot/.docs/instructions.md
Discovered here: https://forum.exercism.org/t/link-issue-in-javascrip-track-regular-chatbot-exercise/9732
=> Fix incorrect URL

exercises/concept/pizza-order/pizza-order.js
There is a small spelling error in the base code, this PR corrects it.
=> PizzaOrder:  change prize to price

exercises/concept/pizza-order/.meta/config.json, exercises/concept/pizza-order/pizza-order.js
A quick PR to expose the type definitions for this exercise, as discussed in [this](https://forum.exercism.org/t/improving-pizza-order-exercise/8279/5) forum post.
=> Exposing `global.d.ts` file to the editor

exercises/concept/windowing-system/.docs/introduction.md
* Corrected typo on mileage (was spelt milage).
* Added two grammatical corrections from original concept's introduction section.
=> Update Intro in Windowing System Exercise

exercises/practice/lens-person/lens-person.js, exercises/practice/lens-person/lens-person.spec.js
Corrected typos and amended tests to check immutability as discussed in [the forum post](https://forum.exercism.org/t/possible-issue-in-unit-test-on-lens-person-exercise/12102/5)
=> [Lens Person] Fix typos and immutability tests

.prettierignore, exercises/practice/dnd-character/dnd-character.spec.js
Fixes the usability issue for users of the online editor reported in [this forum post](https://forum.exercism.org/t/please-give-useful-test-feedback/11415) for D&D Character.
=> Improve test output of dnd-character

exercises/concept/coordinate-transformation/.docs/instructions.md
As discussed [here](https://forum.exercism.org/t/really-confused-about-the-coordinate-transformation-exercise-on-the-closures-topic/10289/23), I've updated the docs to include information about the definitions of Translate and Scale in Geometry.
=> [Docs]Update instructions.md

config.json
Following issue https://github.com/exercism/javascript/issues/987 - I'm starting with adding prerequisites and a practice for a single exercise, just to make sure I'm doing it right :)
=> Added prerequisites and a practice for the "darts" exercise

exercises/practice/rectangles/.meta/config.json, exercises/practice/rectangles/.meta/tests.toml, exercises/practice/rectangles/rectangles.spec.js
Added a missing test from problem specification.
=> Sync Rectangles tests with problem spec

config.json, exercises/practice/killer-sudoku-helper/.docs/instructions.md, exercises/practice/killer-sudoku-helper/.eslintrc, exercises/practice/killer-sudoku-helper/.gitignore, exercises/practice/killer-sudoku-helper/.meta/config.json, exercises/practice/killer-sudoku-helper/.meta/proof.ci.js, exercises/practice/killer-sudoku-helper/.meta/tests.toml, exercises/practice/killer-sudoku-helper/.npmrc, exercises/practice/killer-sudoku-helper/LICENSE, exercises/practice/killer-sudoku-helper/babel.config.js, exercises/practice/killer-sudoku-helper/killer-sudoku-helper.js, exercises/practice/killer-sudoku-helper/killer-sudoku-helper.spec.js, exercises/practice/killer-sudoku-helper/package.json
Discussion is [here](https://forum.exercism.org/t/new-exercise-killer-sudoku-helper/13486)
=> [New exercise] Killer sudoku helper

exercises/practice/bowling/.meta/config.json, exercises/practice/bowling/.meta/tests.toml, exercises/practice/bowling/bowling.spec.js
=> Updating tests bowling

exercises/practice/crypto-square/.meta/config.json, exercises/practice/crypto-square/.meta/tests.toml, exercises/practice/crypto-square/crypto-square.spec.js
=> Updating tests crypto-square

exercises/practice/custom-set/.meta/config.json, exercises/practice/custom-set/.meta/tests.toml, exercises/practice/custom-set/custom-set.spec.js
=> Updating tests custom-set

exercises/practice/bob/.meta/config.json, exercises/practice/bob/.meta/tests.toml, exercises/practice/bob/bob.spec.js
=> Updating tests for Bob

exercises/practice/gigasecond/.meta/config.json, exercises/practice/gigasecond/.meta/tests.toml, exercises/practice/gigasecond/gigasecond.spec.js
This pull request updates the test suite for the **Gigasecond** exercise, aligning it with the latest problem specification.
=> Updating tests for gigasecond

exercises/practice/dnd-character/.meta/config.json, exercises/practice/dnd-character/.meta/tests.toml, exercises/practice/dnd-character/dnd-character.spec.js
This pull request updates the test suite for the **DnD-Character** exercise, aligning it with the latest problem specification.
=> Updating tests for dnd-character

exercises/practice/isbn-verifier/.meta/config.json, exercises/practice/isbn-verifier/.meta/tests.toml, exercises/practice/isbn-verifier/isbn-verifier.spec.js
This pull request updates the test suite for the **ISBN-Verifier** exercise, aligning it with the latest problem specification.
=> Updating tests isbn-verifier

exercises/practice/isogram/.meta/config.json, exercises/practice/isogram/.meta/tests.toml, exercises/practice/isogram/isogram.spec.js
This pull request updates the test suite for the **Isogram** exercise, aligning it with the latest problem specification.
=> Adding tests for isogram

exercises/practice/knapsack/.meta/config.json, exercises/practice/knapsack/.meta/tests.toml
This pull request updates the test suite for the **Knapsack** exercise, aligning it with the latest problem specification.
=> Updating tests knapsack

exercises/practice/largest-series-product/.meta/config.json, exercises/practice/largest-series-product/.meta/proof.ci.js, exercises/practice/largest-series-product/.meta/tests.toml, exercises/practice/largest-series-product/largest-series-product.spec.js
This pull request updates the test suite for the **Largest Series Product** exercise, aligning it with the latest problem specification.
=> Updating tests for largest-series-product

exercises/practice/matching-brackets/.meta/config.json, exercises/practice/matching-brackets/.meta/tests.toml, exercises/practice/matching-brackets/matching-brackets.spec.js
This pull request updates the test suite for the *Matching-Brackets** exercise, aligning it with the latest problem specification.
=> Updating tests for matching-brackets

config.json
I have removed the not-yet implemented stuff for now. I am not worried about "having to re-add them".
=> Lint config.json

exercises/practice/crypto-square/.meta/tests.toml, exercises/practice/crypto-square/crypto-square.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and verifies the presence of new tests in the test file.
=> Syncing test.toml and updating the test code for crypto-square

exercises/practice/pangram/.meta/config.json, exercises/practice/pangram/.meta/tests.toml, exercises/practice/pangram/pangram.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and verifies the presence of new tests in the test file.
=> Syncing test.toml and updating the test code for pangram

exercises/practice/pig-latin/.meta/config.json, exercises/practice/pig-latin/.meta/tests.toml, exercises/practice/pig-latin/pig-latin.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and verifies the presence of new tests in the test file.
=> Syncing test.toml and updating the test code for pig-latin

exercises/practice/triangle/.meta/config.json, exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/triangle.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and verifies the presence of new tests in the test file.
=> Syncing test.toml and updating the test code and the proof solutions for triangle

exercises/practice/complex-numbers/.meta/config.json, exercises/practice/complex-numbers/.meta/tests.toml, exercises/practice/complex-numbers/complex-numbers.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and updates the test file.
=> Update tests complex numbers

exercises/practice/prime-factors/.meta/tests.toml
This exercise had its actual test file already up to date, only the `tests.toml` file was unsynced. So you can mark this as a small-sized PR. I'm not even adding myself to the contributors since no real test updates were required.
=> Sync toml file

exercises/practice/phone-number/.meta/config.json, exercises/practice/phone-number/.meta/proof.ci.js, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/phone-number.spec.js
This PR syncs `tests.toml` with the `problem-specifications` repository and updates the test file.
=> Update tests phone number

config.json
This PR adds "randomness" as a practice and "randomness" and "classes" as prerequisites to the D&D Character exercise on the JavaScript track.
=> Add practice and prerequisites to "dnd-character" exercise
