exercism/javascript

anagram/anagram_test.spec.js
I found a submission where the coder was testing for length of arguments to decide what to do... this case wouldn't have worked.
=> Added single string test to javascript anagram tests

Makefile
Allows the example to be tested against all the specs, including the ones that were marked not to be run right away with xit.
Possible solution to Issue #71
I tested this on my Ubuntu machine. I'd want to see if it worked on Travis and in any other environments that need to be supported before being confident of it.
=> Rename xit to it in specs in temp directory before running them

triangle/triangle_test.spec.js
Made change to conform to the style of previous xjavascript specs. Also
having only one test uncommented suggests incremental development.
=> Comment out all triangle tests (except first one)

queen-attack/example.js, queen-attack/queen-attack_test.spec.js
The unit tests and the example implementation test the north-west / south-east diagonal, but are missing the north-east / south-west diagonal.
I just added two test cases and amended the example implementation.
=> queen-attack: added missing test case / fixed implementation

octal/example.js, octal/octal_test.spec.js
There is a unit test, that tests if "carrot" is converted to 0, but there is no unit test for inputs containing invalid digits, e.g. '8'. The example implementation does not validate the input, too.
=> octal: added missing test case / fixed implementation

word-count/example.js, word-count/word-count_test.spec.js
Strings with leading or trailing whitespace should not increment the total word count.
=> Add test case for leading or trailing whitespace.

custom-set/custom-set_test.spec.js, custom-set/example.js
=> custom-set: BUG FIX #65. Define empty sets as disjointed.

leap/leap_test.spec.js
While solving this exercise for exercism.io I thought test specs could be improved (from my point of view, so I might be wrong). This PR tries to clarify the specs and provides some more examples of leap and non-leap years.
Specs haven't changed, but I hope texts describing them are clearer now.
=> Improve test specs on "Leap" exercise

hamming/example.js, hamming/hamming_test.spec.js
For more consistency. 
Most tests (at least the first few) require a function opposed to an object. There is no reason to break with this habit in this particular test.
=> hamming: test requiring a function opposed to an object

leap/leap_test.spec.js, pythagorean-triplet/pythagorean_triplet_test.spec.js
This should not pass:
```javascript
module.exports = function (year) {
return "Foo"
};
```
=> Fix spuriously passing tests.

rna-transcription/example.js, rna-transcription/rna_transcription_test.spec.js
Saw that in the ruby example it consider conversion in both ways, which is not exactly the same and might make programmers consider how to remove the duplicated code.
Hope it helps!
=> Add test cases for rna to dna transcription to enrich example

bracket-push/bracket_push_test.spec.js
This rules out solutions that simply count the number of open/close
brackets without regard for whether they are properly nested.
I submitted a solution (in another language track) that would have
failed this test and did not realize it until looking at others'
solutions. It would be great if I could have known before submitting,
thus I add this test.
Corresponding PR on xgo https://github.com/exercism/xgo/pull/176
=> bracket-push: Add test for proper nesting

circular-buffer/circular-buffer.spec.js, circular-buffer/example.js
Other language tracks have been adding this:
Ruby:
https://github.com/exercism/xruby/commit/5560b7a0e032bdf4bca753d4aba4625340853d1c
Go:
https://github.com/exercism/xgo/commit/6b41d2f925a7b35140701a8290e7d9a6155ac315
Rust:
https://github.com/exercism/xrust/commit/e4990f1b0e8c9d16053012b13aaaeb03ac141383
Seems prudent for Javascript to test it as well. This will see if any
solutions are unconditionally dropping when overwriting (that would drop
elements from non-full buffers)
=> circular-buffer: Test forced writes on non-full buffer

binary/binary.spec.js, binary/example.js
_cf. [x-common issue #95](https://github.com/exercism/x-common/issues/95)._
I've expanded the JS test for the 'binary' exercise to include the same examples as the [Ruby equivalent](https://github.com/exercism/xruby/blob/master/binary/binary_test.rb). The example solution has also been updated so it passes the new tests.
However, I'm not familiar enough with the Exercism progression to know if this is pitched at an appropriate level – that is, if students are expected to do string validation or understand the nuances of `parseInt` at this point. [JavaScript's `parseInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt) is rather more flexible than solutions in other languages, and doesn't make it easy to bail out on invalid input: 
> If `parseInt` …
=> Extra tests for the 'binary' exercise.

gigasecond/gigasecond.spec.js
I have seen submissions which mutate the original date and return that. This works for the current test suite. However, when the `date` method gets called multiple times. That solution adds another gigasecond on a date where one is already applied.
For example. One might implement the date function like this:
```
Gigasecond.prototype.date = function() {
b = new Date(this.birthday.setSeconds(this.birthday.getSeconds() + 1000000000 ));
return new Date(b.getFullYear(), b.getMonth(), b.getDate());
};
```
This is the incorrect behaviour that the new test case will catch:
```
var d = new Gigasecond(new Date(1995, 8, 27))
d.date()
// Sat Jun 05 2027 00:00:00 GMT+0200 (CEST)
d.date()
// Tue Feb 11 2059 00:00:00 GMT+0100 (CET)
```
=> Test immutability of the gigasecond

Makefile, gigasecond/example.js, gigasecond/gigasecond.spec.js
Addresses issue raised on xecmascript: JS track was rounding down dates to midnight, contradicting metadata for exercise.
Also add .idea to IGNOREDIRS.
@kytrinyx I can merge if this looks good.
=> fixed gigasecond to conform to metadata-- don't round dates down

Makefile
OSX implements ```sed -i``` differently than Linux, which was causing the makefile to skip any tests marked ```xit``` rather than ```it```.
=> Modify Makefile sed command for OSX

rna-transcription/rna-transcription.spec.js
Some of the tests were describing the 'toRna' features when they should have been describing the 'toDna' features.
=> rna-transcription: Corrected test descriptions

saddle-points/saddle-points.spec.js
It wasn't supposed to be there and made the whole test fail.
=> Removed space on line 15.

exercises/triangle/triangle.spec.js
A common solution to this exercise involves first sorting the sides of the triangle. This makes both validating input and determining the kind of triangle easier. However, many solutions erroneously sort the sides alphabetically (the default sort for arrays in JS is alphabetical, even if the array elements are numeric). There is already a test case (Triangle(10,10,2)) that correctly fails when determining kind with incorrectly sorted sides. The test case this PR introduces will also fail validation (triangle inequality) with incorrectly sorted sides.
=> Add test to catch non-numeric sorting

docs/ABOUT.md
This fixes a layout bug on http://exercism.io/languages/javascript.
I've also tidied up the punctuation and trailing whitespace.
The Redcarpet Markdown parser requires a blank line before lists ([see this Babelmark](http://johnmacfarlane.net/babelmark2/?text=You+should+learn+JavaScript+because%3A-%0A*+It's+easy+to+learn.%0A*+It's+versatile+in+the+sense+that+it's+multi-paradigm+supporting+procedural%2C+event+based%2C+object+oriented+and+functional+programming.%0A*+It's+Open+Source.%0A*+JavaScript+programming+skills+are+in+high+demand.)), so the lists in this file were being rendered inline rather than as a `<ul>`.
The bug isn't obvious when you view the file on Github because Github's Markdown parser is more flexible about blank lines.
As a side-note, Redcarpet has a `:lax_spacing` option …
=> Fix markdown syntax in ABOUT.md

exercises/triangle/triangle.spec.js
I'm removing this test that i added after the outcome of [a discussion on the Erlang track](https://github.com/exercism/xerlang/issues/85) that concluded we should not allow 'degenerate' triangles, EG sides a,c,b where a+b=c.
=> Remove test which allows degenerate (a+b=c) triangles

.travis.yml
NodeJS is now on version 5.7, so it seems like the thing to do!
=> Update node version

exercises/linked-list/linked-list.spec.js
The README.md states:
> To keep your implementation simple, the tests will not cover error conditions. 
> Specifically: pop or shift will never be called on an empty Deque
I removed the one test which did a pop() on an empty Deque anyway.
=> Removed test which contradicted the README.md

.travis.yml
We don't need to use sudo, and this should (technically) be faster, overall.
=> Use containerized build on travis

exercises/largest-series-product/largest-series-product.spec.js
The digits and slices functions are internal implementation details and
thus the test case for the largest-series-product problem should not be
concerned with testing them. The series tests could potentially be moved
to the series exercise (already implemented by this track).
Their presence may cause students to falsely think that their solution
has to use these two functions, instead of the alternative
implementation of only iterating through the digits once.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the digits and slices tests), then consider
including a hints file and/or directory in the largest-series-product
directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192
Relevant to #169: This will …
=> largest-series-product: Do not test digits/slices

exercises/bob/bob.spec.js
This update will fix the example on the hex characters by telling the reader what each hex character is in normal text format.
=> make hex characters easier to understand

docs/TESTS.md
Closes https://github.com/exercism/xjavascript/issues/176.
Assuming I didn't whiff on this easy PR, I'll take a few of the other tracks.
=> Update links to remove deprecated help.exercism.io

exercises/binary/binary.spec.js
Addresses #181 and adds the missing test: alphabetic characters in the number makes it to be decimal 0.
=> Binary: add missing test

SETUP.md
The github-flavored-markdown section of SETUP using the fenceposts
is completely non-obvious if you aren't familiar with markdown.
I just watched a newbie try to type in the backticks and "bash"
along with the dollar-sign.
This removes some of the clutter.
=> Make the test instructions more beginner-friendly

docs/INSTALLATION.md, docs/TESTS.md
Remove clutter from markdown text to make it simpler for beginners.
This PR complements #191 because there were more occurrences of fenceposts.
=> Remove clutter from documentation

exercises/word-count/word-count.spec.js
As 'prototype' isn't a standard property on an object's prototype,
the test didn't actually check the case of dealing with a collision
The 'constructor' property is a standard
see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object
and: http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.4
It's possible that this will break existing solutions - the reference solution is immune though
=> word-count: use 'constructor' as a reserved word

docs/INSTALLATION.md
Addresses #194.
There are separated and more detailed instructions for Windows, Mac and Linux platforms.
I hope it is clear that Node.js comes with the `npm` tool and that exercism users need to install `jasmine-node` to run tests.
=> Improve instructions for Windows and Mac OS X users

exercises/custom-set/custom-set.spec.js, exercises/custom-set/example.js
fixes #283
Note that I've done this as 2 commits:
Commit 1 does not break existing solutions and does as much as possible to conform to the canonical tests. This also uncovered a bug in the example solution, which this fixes.
Commit 2 will break existing solutions, as it changes #empty to have the meaning from the canonical tests, and renames the existing method to #clear
The non-canonical tests for this track have been left (they are positioned after the canonical tests)
I've stayed with the style of the test suite to keep things consistent
Happy to discuss, squash or change any of this!
=> Update custom set test order

exercises/isogram/isogram.spec.js
éléphant is not an isogram, but some solutions using a
simple regexp replace of non-word characters will fail
at it.
Addresses #287
=> Add new test in the Isogram exercise

exercises/custom-set/custom-set.spec.js
The first test should be enabled, all others should be disabled
This was missed in the re-ordering of the tests that I did a few weeks ago.
=> custom-set: correct initially enabled test

exercises/beer-song/beer-song.spec.js
An isolated test of the 2 bottle case would help highlight that it is a special case. If the 2 bottle case is not called out when 1 and 0 are, the error will not be caught until the final test.
=> beer-song: Add test case for 2 bottles.

exercises/custom-set/custom-set.spec.js, exercises/custom-set/example-gen.js
Fixes #292
The spec for this exercise is now generated from the common exercise metadata.
Due to the metadata test cases being one assertion per case, there are now more tests in the suite.
The existing non-canonical tests have been appended after the new generated tests.
=> custom-set: exercise generator

exercises/word-count/example.js, exercises/word-count/word-count.spec.js
This brings the javascript word-count test in alignment with the x-common, so that all the tests referenced in x-common are now included in the javascript version.  The additional existing tests were maintained.
Addresses Issue #305 so that punctuation is handled the same in javascript as it is described in x-common, i.e., punctuation is not considered part of the word L26, L52, L77.
Also, added the the cramped list, apostrophe, and single quotes test from x-common L21, L41, L46 and clarified the test intent on L11, L16, L61.
Finally, updated the example.js code so that it passed all the new test.  This added two replace commands on L7-8 and I simplified the <code>.forEach( function(word) {</code> by moving the <code>.toLowerCase()</code> function to L7.
=> Align word count with the x-common reference

exercises/bowling/bowling.spec.js
This updates the bowling tests for #303.  The tests were re-ordered or added so that the tests follow the x-common reference test.  The additional unique tests were left in the file.
=> Bowling tests aligned with x-common

exercises/rna-transcription/example.js, exercises/rna-transcription/rna-transcription.spec.js
I've added 2 new test cases to the exercise rna-transcription to handle invalid input DNA nucleotide.
Committing the test cases in 1 commit.
=> Add 2 new test cases to check invalid input

exercises/robot-simulator/example.js, exercises/robot-simulator/robot-simulator.spec.js
The original test passes without any assertions if `robot.orient` doesn't throw an exception
=> Robot-simulator: require throwing exception

config.json
Word Count problem is moved to position 20th, because it introduces
users to a Unicode complex problem.
Bob problem, although likely dealing with Unicode subjects, is kept
because it can be reasonably solved without knowing too much about
Unicode.
Pangram is moved just before Bob.
Topics are configured in `config.json` for all three problems.
Addresses #321
=> Move unicode problems up the list in `config.json`

docs/TESTS.md
This PR improves a little bit the documentation about how to run tests by including a couple of basic commands about how to fetch exercises as it was discussed on https://github.com/exercism/xjavascript/pull/297#issuecomment-237935748
Adds some changes related to #289
=> Include basic commands about how to fetch exercises

exercises/leap/HINT.md, exercises/leap/leap.js
Rewriting the stub was trivial, but this is only the second exercise in the track and writing the class in this way makes complete sense, because we intuitively would want to instantiate a `Year` with a value, but it requires the beginning user to initialize the instance variable in one section of code and the `isLeap` logic in the instance method.  
Perhaps it would be better to leave the stub as it is and rewrite the tests so that `isLeap` takes the year parameter.  Even though this is a counter-intuitive design for the `Year` class, I believe it would be less intimidating for beginning users.  I would be glad to revise the tests if that is what is decided.
=> Edit leap year stub to be consistent with tests

Makefile, SETUP.md, docs/INSTALLATION.md, docs/TESTS.md, exercises/acronym/package.json, exercises/hello-world/HINTS.md, package.json
**Blocked by #344**
--
According to discussions in #341 we'll use Jasmine as a command line tool, globally installed through npm, and the testing command should now look like `jasmine ./test-file.spec.js`.
`❯ grep -lr "jasmine-node" .`
=> Update testing instructions on all exercises

docs/TESTS.md
Made some cleanup of the doc. Few of these cleanups are opinionated, so feel free to discuss.
* Removed the exercise fetching content since it does not belong here and is already present in the [Available exercises section](http://exercism.io/languages/javascript/exercises).
* Also removed the module exporting section coz we have stubs for a few beginning exercises. Kept the link to node module documentation for reference.
* Mentioned about skipped exercises and hence TDD. Closes #334 
* Mentioned that the other two sections - `Visual studio for windows` and `Linting` are optional.
=> Test doc cleanup

config.json, exercises/proverb/example.js, exercises/proverb/proverb.spec.js
Adds the "proverb" exercise from the xcommon track to the xjavascript track.
Adds:
- 1 folder "proverb" containing 2 files
- example.js
- proverb.spec.js
Changes:
- config.json  (not sure where to place this exercise, therefore I put it in the last position)
If I missed something in order for the added exercise to work properly, let me know.
=> Adding proverb exercise

SETUP.md, exercises/hello-world/HINTS.md
This PR refers to #349, which @ronalson reported that instructions to test exercises are just to run `jasmine .`, when it should actually be `jasmine your-exercise-test-file.spec.js`.
=> Updates test instructions on Hello World's HINTS.md

.github/stale.yml
We want to keep these issues open indefinitely for first-timers.
Tell probot to ignore them so that they are never closed
automatically.
`pinned` and `security` are default. I added `good first patch` and
`first-timers only`.
Ref: https://github.com/exercism/xecmascript/pull/293#issuecomment-302931135
=> Add first patch labels to probot exempt

exercises/isogram/isogram.spec.js
Tests a word which includes both upper and lower case of an extended ascii character. See issues [#359](https://github.com/exercism/xjavascript/issues/359) and [#323](https://github.com/exercism/xjavascript/issues/323).
=> Add extended ascii character test for isogram.

exercises/phone-number/example.js, exercises/phone-number/phone-number.spec.js
=> Modified Phone Number tests to fit canonical data

config.json
`Arrays` and `Lists` instead of `data-structures`. I removed the `data-structures` because it's not listed in [`TOPICS.txt`](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt).
=> Replace topics for simple-linked-list

config.json
This PR acomplishes the first two tasks of #382 
- Add a rough estimate of difficulty to each exercise (scale: 1-10) if it hasn't already one
- Add topics to exercises that has no topics yet
Of course, topics might be wrong (almost all exercises are about conditionals and loops, but that's programming), difficulty might be wrong. But we can discuss now that we have some values for them.
Next step: Choose *at most 20 exercises* to be *core* exercises (set `core: true`, and delete the `unlocked_by` key)
=> Add topics and difficulty to all exercises

config.json
1. 18 exercises, sorted by difficulty, has been selected as *core* ones: hello-world, leap, rna-transcription, simple-cipher, pangram, bob, gigasecond, space-age, binary, prime-factors, matrix, linked-list, pascals-triangle, secret-handshake, grade-school, robot-name, wordy and list-ops
2. 4 exercises are non-core ones and they are not unlocked by any exercise: run-length-encoding, roman-numerals, queen-attack and minesweeper
3. The rest of the exercises are non-core and they are unlocked by just one exercise
All this completes the remainning tasks of #382
=> Set core, non-core exercises and unlocking ones

exercises/circular-buffer/circular-buffer.spec.js
I've seen people came up with solution like
`Buffer.buffer = [];
Buffer.read = function() { /* do something with Buffer.buffer */ };
module.exports = Buffer;
`.
While it's not required in the description that multiple circular buffers can be instantiated, I felt that this kind of pattern should be discouraged, and there should be a test to check this.
=> Add a new test to circular buffer exercise

exercises/simple-cipher/simple-cipher.spec.js
The test case was changed in both tracks with unrelated changes. This commit merges the two logically:
#401 
https://github.com/exercism/ecmascript/pull/347
and synchronizes the Regex usage.
The according sync-PR in EcmaScript track:
https://github.com/exercism/ecmascript/pull/348
=> Synchronizing EcmaScript <-> Javascript test for simple-cipher

exercises/two-bucket/example.js, exercises/two-bucket/two-bucket.spec.js
Previously: `npm run lint` would show these errors / warnings for `two-bucket`
```
/Volumes/git/personal/javascript/exercises/two-bucket/example.js
10:25  error    Expected '===' and instead saw '=='                eqeqeq
10:49  error    Expected '===' and instead saw '=='                eqeqeq
11:27  error    Expected '===' and instead saw '=='                eqeqeq
24:5   error    Split 'var' declarations into multiple statements  one-var
25:5   warning  Unexpected constant condition                      no-constant-condition
27:22  error    Expected '===' and instead saw '=='                eqeqeq
27:40  error    Expected '===' and instead saw '=='                eqeqeq
30:20  error    Expected '===' and instead saw '=='                eqeqeq
35:29  error    Expected '===' and instead …
```
=> Refactor two-bucket

docs/TESTS.md
It was http://exercism.io/cli, which resulted in a 404.
=> Fixed link to CLI download page.

exercises/bowling/README.md
There isn't an issue open for this, but when I was porting the bowling exercise to the ECMAScript track for [ecmascript#332](https://github.com/exercism/ecmascript/issues/332), I was asked to make some fixes to the README for that exercise. I figure it makes sense to "backport" those fixes to the original exercise.
Thanks, and let me know if there's anything else you'd like me to change while I'm at it!
=> grammar and readability fixes to exercises/bowling/README.md

exercises/crypto-square/example.js, exercises/largest-series-product/example.js, exercises/sieve/example.js
Part of https://github.com/exercism/javascript/issues/399
Fix `error  Split 'var' declarations into multiple statements  one-var` errors to clean up three examples. These were the only errors on these three examples.
=> Fix crypto square, largest series product, sieve examples

.eslintignore, exercises/diamond/diamond.spec.js, exercises/diamond/example.js, exercises/sum-of-multiples/sum-of-multiples.spec.js
Part of https://github.com/exercism/javascript/issues/399
Fixes lint errors for Diamond and Sum of Multiples examples.
Diamond: 
```
/javascript/exercises/diamond/diamond.spec.js
7:5   error  'result' is not defined  no-undef
8:46  error  'result' is not defined  no-undef
12:5   error  'result' is not defined  no-undef
17:46  error  'result' is not defined  no-undef
21:5   error  'result' is not defined  no-undef
30:46  error  'result' is not defined  no-undef
/javascript/exercises/diamond/example.js
8:14  error  'i' is already defined  no-redeclare
✖ 7 problems (7 errors, 0 warnings)
```
Sum of Multiples:
```
/javascript/exercises/sum-of-multiples/sum-of-multiples.spec.js
5:12  error  A function with a name starting with an uppercase letter should only be used as a constructor  new-cap …
```
=> Fix Diamond and Sum of Multiples

.eslintignore, exercises/acronym/example.js
Fix errors: 
```
/javascript/exercises/acronym/example.js
5:9   error  Return statement should not contain assignment  no-return-assign
5:16  error  Assignment to function parameter 'acronym'      no-param-reassign
✖ 2 problems (2 errors, 0 warnings)
```
=> Fix 2 lint errors on Acronym exercise

.eslintignore, exercises/grains/example.js
I added .eslignore files to the grains exercise directory and project root.   Also deleted the big-integer-spec.js test file as it doesn't make sense to keep a test for a vendor included library.  A user won't be able to get to it anyway without download the project source.
=> fix the grains exercise

.eslintignore, exercises/accumulate/example.js
Fix 1 error: 
```
/javascript/exercises/accumulate/example.js
1:5  error  'accumulate' is assigned a value but never used  no-unused-vars
✖ 1 problem (1 error, 0 warnings)
```
=> Lint fix for Accumulate exercise

.eslintignore
Tested both alphametics.spec.js and example.js .
Found no eslint errors in both files.
Removed these files from .eslintignore.
=> Fixes: Alphametic Lint Fixes

exercises/bowling/bowling.spec.js, exercises/bowling/example.js
#488 
the bowling exercise now strictly matches the canonical [tests](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json)
=> redo the bowling exericse to match the canonical tests and description

.eslintignore, exercises/perfect-numbers/example.js
Fixes #399. 
Fixed the linting errors in perfect-numbers/example.js
7:1  Missing JSDoc @returns for function
7:1  Missing JSDoc for parameter 'number'
13:14  The array literal notation [] is preferrable
34:3  Split 'var' declarations into multiple statements
=> fixes linting errors for perfect numbers exercise

.eslintignore, exercises/nth-prime/example.js
Fixes #399.
Fixed the linting errors in the nth-prime/example.js
9:19  Expected to return a value at the end of method 'generatePrimes'
10:5  Split 'var' declarations into multiple statements          
10:29  'primeCount' is assigned a value but never used
=> fixes linting errors for nth-prime exercise

package-lock.json, package.json
Recently [an issue](https://github.com/exercism/javascript/issues/505) came up related to jasmine v3.0.0. And I noticed that we are using v2.8. Jasmine 3 seems to have some [breaking changes](https://github.com/jasmine/jasmine/blob/master/release_notes/3.0.md) and since many of our new users will be installing recent version of jasmine, I thought it would be better to update it so we run CI using v3.
=> Update jasmine to v3.1.0

config.json
Closes #527.
configlet v3.8.0 requires `unlocked_by` to be core exercise. Make the required changes.
Changed `unlocked_by` in the following way:
```
if A is unlocked_by B(non-core - error) 
and B is unlocked_by C(core) 
now A is unlocked_by C(core)
```
=> Fix errors in config for configlet v3.8.0

.eslintignore
removed custom-set, flatten-array and queen-attack exercises from .eslintignore as they are properly linted. also currently #399 shows grade-school as still needing code fixes, but even that is already fixed. please update the list accordingly.
=> remove linted exercises from lint ignore

exercises/bob/bob.spec.js, exercises/bob/example.js
Closes #492 
@exercism/ecmascripts I would appreciate some eyes on this one!  Thank you in advance ❤️
=> Update Bob to match README

exercises/simple-cipher/simple-cipher.spec.js
_See also: this same PR for the typescript track: https://github.com/exercism/typescript/pull/186_
The README for this exercise describes generating random keys consisting of 100+ lowercase letters, but the only constraint enforced by the tests is that it must contain only lowercase letters. One could pass this constraint by simply defaulting the key to a hard-coded string like `lolnotrandom`.
This PR adds tests to enforce that keys are randomly generated (at least a simple test that if you generate 2 keys back to back, they are not the same key), and that they are at least 100 characters long.
=> Simple Cipher: Add tests for random key generation, 100+ character length

docs/LEARNING.md
Eloquent JavaScript came out with a 3rd edition some time ago. Previously, LEARNING.md mentioned its 2nd edition instead. Now it mentions no edition. The link is thus futureproofed.
Closes #548
=> Removed outdated mention of Eloquent JavaScript’s edition number

exercises/pangram/pangram.spec.js
This PR updates the tests for pangram exercise according to canonical date. 
This will fix #551
=> fix: pangram tests as per canonical data

README.md, config.json
This:
- simplifies the README for clarity
- renames the language to "JavaScript (Legacy)"
- sets `"active": false`
We will merge it after the migration has taken place.
=> Deprecate this track
