word-count/example.js, word-count/word-count_test.spec.js
This adds 2 more tests for word count:
+ A test to see if tabs are recognized to break up words
+ A test to see if multiple spaces are recognized to break up words
Credit to [eKipod](https://github.com/eKipod) for [bringing this up](http://exercism.io/submissions/caaacf6b9bf2498eb0f31eab55e9ade8)
=> Word count tests for tabs and multiple spaces

sum-of-multiples/sum-of-multiples_test.spec.js
Adding test cases to Sum of Multiples as per exercism/exercism.io#2341.
=> Add test cases to Sum of Multiples

circular-buffer/circular-buffer_test.spec.js
Removed trailing whitespace between tests in circular-buffer spec
=> Remove whitespace

queen-attack/example.js, queen-attack/queen-attack_test.spec.js
Use _'s instead of O's for empty spaces
=> Issue 64 Update Queen Attack

rna-transcription/rna-transcription_test.spec.js
=> Rename nucleosides to nucleobases

config.json, hello-world/example.js, hello-world/hello-world.js, hello-world/hello-world_test.spec.js
I decided to copy the skeleton from the Bob exercise. Will Bob still need it in this case?
Completes Javascript for the hello world list: https://github.com/exercism/rossconf/issues/2
=> Add hello-world exercise

crypto-square/crypto-square_test.spec.js, triangle/example.js, triangle/triangle_test.spec.js
Hi,
in fact, a triangle with lets say side length 10,10,20 and angles 0,0,180 are quite wired, but are technically triangles.
the law is:
z <= x + y 
not 
z < x + y
=> [triangle] fixing edgecase of triangle inequality law

binary-search/binary-search_test.spec.js, binary-search/example.js, config.json
Adding the binary search problem to the JS track. Please let me know if there are any changes required!
=> adding binary-search problem

bob/bob_test.spec.js
=> bob-test: COMMENT to clarify umlauts test.

meetup/example.js, meetup/meetup_test.spec.js
=> meetup: CHANGE approach away from metaprogramming RE: #35.

robot-name/robot_name_test.spec.js
A very simple PR, mark all tests but first as ignored. 
It surprised me when I solved this problem for exercism. I had lots of tests failing at the beginning and it was because all tests were *active*.
=> Ignore all tests but first

hello-world/example.js, hello-world/hello_world_test.spec.js
This is how it is in other repositories/languages and it is the format the readme uses.
=> Should be uppercase "World"

anagram/anagram.spec.js, anagram/example.js, beer-song/beer-song.spec.js, beer-song/example.js, etl/etl.spec.js, etl/example.js, food-chain/example.js, food-chain/food-chain.spec.js, hamming/example.js, hamming/hamming.spec.js, leap/example.js, leap/leap.spec.js, word-count/example.js, word-count/word-count.spec.js
As commented on #128, the first exercises require a similar structure to be exported on user's solutions.
=> Make tests require the solution to export a classy function

docs/TESTS.md
=> Fix linter links in docs

sum-of-multiples/sum-of-multiples.spec.js
Per these instructions: https://github.com/exercism/todo/issues/58
=> add missing test to sum-of-multiples exercise

robot-name/robot-name.spec.js
Same as [exercism/xecmascript PR#62](https://github.com/exercism/xecmascript/pull/62):
> This new test tries to guide the user with smaller steps. One can first hardcode the first name. Then, the user needs to generate a different name, but only one more. After that, the next test ask the user to generate 10k different names.
=> Add test to help implement Robot with smaller steps

docs/ABOUT.md
- Added about file for describing JavaScript.
=> Add ABOUT.md file

rna-transcription/example.js, rna-transcription/rna-transcription.spec.js
=> Remove rna to dna logic and tests

acronym/acronym.spec.js, acronym/example.js, acronym/package.json, config.json
Like ECMAScript PR https://github.com/exercism/xecmascript/pull/184
=> Add new exercise acronym

largest-series-product/largest-series-product.spec.js
As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.
=> largest-series-product corner cases

config.json
As described in #154.
@rchavarria is this what we needed?
=> Modify config.json to add test pattern

docs/ABOUT.md
As discussed on #161.
The message is not written in HTML but in Markdown, separating it with a horizontal rule, it is in italics, at the bottom and talk about the ECMAScript track.
Let me know whether the message is ok or not.
=> Write a message trying to make it clear the intention of this track

exercises/triangle/triangle.spec.js
pointed out by @plinto in http://exercism.io/submissions/1a614864d2dc44bdb18e1be9f5f6970e
=> Adding a missing isosceles case

exercises/sum-of-multiples/example.js, exercises/sum-of-multiples/sum-of-multiples.spec.js
=> Remove default multiples

exercises/grade-school/grade-school.spec.js
for those of us with a bit more strict Javascript compilation.
=> fix `sorted is not defined` error.

exercises/scrabble-score/scrabble-score.spec.js
=> Replace "multibillionaire" with "oxyphenbutazone"

exercises/pangram/pangram.spec.js
Addresses [x-common #222](https://github.com/exercism/x-common/issues/222)
=> Update tests for Pangram

exercises/hello-world/hello-world.js
I removed 'only' because it doesn't seem to serve a purpose.
I switched SKELETON to stub because we don't need to shout, and we use the term stub file elsewhere
on the site.
Lastly, I changed the file name to match the actual file name in the exercise.
=> Clarify hello-world stub file comments

exercises/hello-world/HINTS.md
If you've only ever written javascript for the browser, and you've
never done any TDD, then this exercise has a lot of barriers to success.
This tutorial might help get people started.
I'm not sure exactly what needs to go into the tutorial. This is based on watching a code newbie try to figure out how to get started. They've done some tutorials where they write code in the browser, but never any TDD or node.
=> Add a basic tutorial for hello-world

config.json, exercises/isogram/example.js, exercises/isogram/isogram.spec.js
Tests and example for Isogram exercise
=> Isogram: tests and example

exercises/binary-search/binary-search.spec.js
=> binary-search: fix ordering of actual/expected

exercises/clock/clock.spec.js, exercises/clock/example.js
Addresses #184 
Quite similar to PR in [xecmascript#218](https://github.com/exercism/xecmascript/pull/218).
=> Clock: synchronize tests with canonical ones

exercises/palindrome-products/palindrome-products.spec.js
=> palindrome-products: fix ordering of actual/expected

exercises/linked-list/linked-list.spec.js
Fixes #270
This is the same expectation as that on the ecmascript track
=> linked-list: add missing expectation

exercises/trinary/trinary.spec.js
=> trinary: fix ordering of actual/expected

exercises/wordy/wordy.spec.js
=> wordy: fix ordering of actual/expected

config.json, docs/ABOUT.md, exercises/flatten-array/example.js, exercises/flatten-array/flatten-array.spec.js
Hey Katrina, please review my request and let me know what I might be missing if anything
=> adding flatten-array to the list with test

docs/TESTS.md
This PR adds a more detailed explanation about how a user should run the tests for the first time, because some users didn't find it easy to start running them (see #284).
Addresses #289
=> Elaborate a bit more on how to run the tests for the first time

exercises/binary-search/binary-search.spec.js
When doing this exercise I had some troubles getting the indexes correct. I was passing the tests that were provided but my program did not work correctly for entries at the very beginning or end of the array e.g. because of some off-by-one errors.
That's why I am proposing to add two test cases here so people don't have to manually add them like I did.
=> Adding two more test cases for binary-search

config.json, exercises/diamond/diamond.spec.js, exercises/diamond/example.js
Tests and examples for Diamond exercise
=> Add Diamond: tests and examples

exercises/luhn/example.js, exercises/luhn/luhn.spec.js
Canonical specs for Luhn exercise were changed, and tracks implementing that exercise should synchronize wih them.
Closes #316
=>  Synchronize Luhn exercise with canonical specs

exercises/leap/leap.js
=> update skeleton files to match exercise order

exercises/leap/leap.js
Changes reference from 'Bob' to 'Leap' in starter file comment from fix #318
=> Update leap comment

exercises/phone-number/phone-number.spec.js
With the current test suite this submission will pass:
```
var PhoneNumber = function(raw){
this.raw = raw
}
PhoneNumber.prototype.number = function() {
return this.raw[0] === '2' || this.raw.length === 9 
? '0000000000' 
: '1234567890'
}
PhoneNumber.prototype.areaCode = () => '123'
PhoneNumber.prototype.toString = () => '(123) 456-7890'
module.exports = PhoneNumber;
```
I've added some more tests to drive towards a more complete solution.  What does everyone think?
=> add more tests to drive towards complete solution

exercises/hamming/example.js
This bug blocks #342. Please check [my comment on #342](https://github.com/exercism/xjavascript/pull/342#issuecomment-296231899) about this bug for more info.
=> Hamming exercise example refactoring

exercises/robot-simulator/example.js
**Blocks #342**
--
The example for the Robot Simulator exercise [is not passing through unit tests](https://github.com/exercism/xjavascript/pull/342#issuecomment-296450529). The issue was already explained by Matthew [in his comment on #342](https://github.com/exercism/xjavascript/pull/342#issuecomment-296454271). I took the opportunity to make a complete refactoring, using a closure to encapsulate variables that are common to multiple methods or could be kept as singleton instead of an internal variable of an instance method.
The file is now passing all unit tests and nows seems to be easier to read and understand.
=> Robot Simulator example refactoring

README.md
So people don't have to go to stack overflow to get a link to that page like I did. :)
=> Add info about how to install Javascript

docs/TESTS.md
=> TESTS.md: make image links relative

docs/TESTS.md
per @matthewmorgan 's request.
=> requested correction for relative link

docs/TESTS.md
=> TESTS.md: replace angle brackets for better rendering

config.json
Topics where added to these problems
- hello-world
- leap
- rna-transcription
- hamming
- gigasecond
=> Add topics for problems

config.json
Addresses #299
Add topics to
- isogram
- beer-song
- phone-number
- anagram
- food-chain
=> Add topics to exercises

config.json, exercises/alphametics/alphametics.spec.js, exercises/alphametics/example.js
This implements the alphametics exercise. Thanks
=> Add the alphametics exercise

exercises/hello-world/HINTS.md, exercises/hello-world/hello-world.js, exercises/hello-world/hello-world.spec.js
=> Simplified the hello-world exercise

config.json, exercises/simple-linked-list/example.js, exercises/simple-linked-list/simple-linked-list.spec.js
I needed to implement this as a new branch since the work in progress of #311 was in the contributor's fork. This is my first exercise contribution, so please consider that I don't exactly know what I am doing 😂
Suggestions for improvements are more than welcome! 🎉
=> Adds the simple-linked-list exercise (#311)

exercises/bob/bob.spec.js, exercises/bob/example.js
Addresses #376 , bringing Bob up to date with canonical data.  @exercism/ecmascripts would someone like to do this for the ES track as well?
=> Update Bob for canonical tests

config.json, exercises/list-ops/example.js, exercises/list-ops/list-ops.spec.js
I ported list-ops. Currently I have all the canonical test implemented; I could add some more in-depth ones like [some of the other tracks have](https://github.com/exercism/csharp/blob/master/exercises/list-ops/ListOpsTest.cs) if you like.
Let me know if there's anything up with my formatting; couldn't find a style guide for this track.
=> port list-ops exercise

config.json, exercises/sublist/README.md, exercises/sublist/example.js, exercises/sublist/sublist.spec.js
A port of the EcmaScript version.
BTW re-pushed this bc I forgot to update the README for JS testing...
=> Add exercise sublist

config.json
See exercism/problem-specifications#884
=> config: Replace topic 'Control flow' with 'Control-flow'

exercises/simple-linked-list/example.js, exercises/simple-linked-list/simple-linked-list.spec.js
@tejasbubane caught this on exercism/ecmascript#345, while reviewing @apapirovski's ECMAScript version of this exercise
=> Avoid mutations on List#toArray() (simple-linked-list exercise)

exercises/simple-cipher/example.js, exercises/simple-cipher/simple-cipher.spec.js
I just saw an exercise implementation of somebody who did not account for messages longer than the key and I figured this needs to be in the spec.
=> added test case 'can handle messages longer than the key'

config.json, config/maintainers.json
https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#configuring-the-exercise
It is a new formatter to format the config files consistently. 
Because the line movings in the files are quite numerous, I'd suggest to merge this now instead of when the next new exercise does it anyway.
=> ran new configlet fmt as told in the documentation

.gitignore, config.json, exercises/change/README.md, exercises/change/change.spec.js, exercises/change/example.js
I added a 'Change' exercise to the set Javascript exercises.   I based the Jasmine tests upon the set of tests used from the same exercise in the Java project.
=> Add change exercise

docs/TESTS.md
Minor change to link in the docs. Thanks!
=> Fix Broken Link to Install Guide

config.json, exercises/twelve-days/README.md, exercises/twelve-days/example.js, exercises/twelve-days/package.json, exercises/twelve-days/twelve-days.spec.js
@rchavarria , @matthewmorgan  please let me know if all is well in this PR, thanks.
=> ported 12 days exercise, resolves issue #391

docs/ABOUT.md
As requested in issue [#85](https://github.com/exercism/meta/issues/85) in the meta repo - some minor formatting changes, along with a few grammatical/wording fixes.
=> Update ABOUT.md to nextercism format

exercises/hello-world/example.js
=> Fix hello-world code

exercises/diffie-hellman/example.js
This is minor typo fix to getPublicKeyFromPrivateKey exception message.
=> Fix grammar/typo.

exercises/meetup/example.js, exercises/meetup/meetup.spec.js
Correct the 'meetup' exercise for formatting and syntax error as indicated by the linter. #399
=> Fix Meetup code

config.json, exercises/collatz-conjecture/collatz-conjecture.spec.js, exercises/collatz-conjecture/example.js
Hello, This is my first PR to open source community. If any suggestions or changes required please let me know. Thanks. :)
=> Implement exercise collatz conjecture exercise

exercises/change/example.js
fix the change exercise.  #399 
Only the example.js file required changes.  The change.spec.js does not have any errors reported by the linter.
=> fix the change exercise

config/maintainers.json
I'm not very proud of adding myself as a maintainer, but somebody needs to do the job 😉 
Come on @exercism/ecmascripts, let's prepare for Nextercism.
=> Add rchavarria as maintainer

exercises/collatz-conjecture/README.md
This PR completes #413 by adding the missing `README` file to the exercise.
=> Add `README` file to `collatz-conjecture` exercise

exercises/transpose/README.md
This PR completes #416 by adding the missing `README` file to the exercise.
=> Add `README` file for `transpose` exercise

exercises/protein-translation/example.js, exercises/protein-translation/protein-translation.spec.js
Correct the example.js and protein-translation.spec.js files as indicated by the linter.  #399
=> fix the protein-translation exercise

exercises/twelve-days/example.js
Fix the twelve-days exercise as indicated by the linter.  No changes were needed in the twelve-days.spec.js file.  #399
=> fix the twelve-days exercise

exercises/prime-factors/example.js
See #399 
Only needed to update `example.js`, no errors were reported in `prime-factors.spec.js`
=> Fix code style in prime-factors

exercises/difference-of-squares/README.md, exercises/palindrome-products/README.md, exercises/sum-of-multiples/README.md
Prepositions are not normally capitalized in titles or headlines in English.
=> Fix capitalization in headlines of readme files

exercises/beer-song/example.js
Fixed beer-song example as request in Issue #399
- spec doc had no lint errors
=> Lint Fixes for Beer Song Example

config.json, exercises/isbn-verifier/README.md, exercises/isbn-verifier/example.js, exercises/isbn-verifier/isbn-verifier.spec.js
[Problem specification and test data](https://github.com/exercism/problem-specifications/tree/master/exercises/isbn-verifier)
=> Add isbn-verifier exercise

.eslintignore, exercises/wordy/example.js
=> fix the wordy exercise

exercises/alphametics/example.js
=> alphametics: resolve eslint errors

.eslintignore, exercises/say/example.js
=> Fix eslint errors for “say” example

.eslintignore, exercises/trinary/example.js
=> fix the trinary exercise

.eslintignore, exercises/scrabble-score/example.js
=> Eslint fix for scrabble-score

.eslintignore, exercises/anagram/example.js
=> fix anagram exercise

.eslintignore, exercises/pangram/example.js
=> fix pangram exercise

.eslintignore, exercises/octal/example.js
=> fix octal exercise

.eslintignore, exercises/robot-name/robot-name.spec.js
=> fix robot name exerise

package-lock.json
=> Add package-lock.json to the repo

.eslintignore, exercises/clock/example.js
=> fix clock exercise

README.md
=> readme: add gitter badge

config.json
"Twelve Days" is not about polymorphism, nor is it necessarily about regular expressions.
I've removed those those two topics from the config.
=> Correct Twelve Days topics

.eslintignore, exercises/bowling/example.js
=> fix bowling exercise

.eslintignore, exercises/palindrome-products/example.js
=> fix palindrome products exercise

.travis.yml
As suggested in https://github.com/exercism/javascript/issues/462.
=> Use LTS version of node in travis-ci

.eslintignore, exercises/binary-search-tree/example.js, exercises/binary-search/example.js, exercises/bracket-push/example.js, exercises/leap/example.js, exercises/leap/leap.js, exercises/list-ops/example.js, exercises/luhn/example.js, exercises/pythagorean-triplet/example.js, exercises/roman-numerals/example.js
Have tested and corrected the lint error for the following files
- exercises/binary-search
- exercises/binary-search-tree
- exercises/bracket-push
- exercises/leap
- exercises/list-ops
- exercises/luhn
- exercises/pythagorean-triplet
- exercises/roman-numerals
=> Exercise Code Lint fixes

config.json, exercises/rotational-cipher/README.md, exercises/rotational-cipher/example.js, exercises/rotational-cipher/rotational-cipher.spec.js
Hello!
I added Rotational Cipher exercise 🙂
=> Add new exercise Rotational Cipher

.eslintignore, exercises/kindergarten-garden/example.js
fixes #399 
26:7  error  'plants' is already declared in the upper scope  no-shadow
45:3  error  Assignment to function parameter 'students'      no-param-reassign
✖ 2 problems (2 errors, 0 warnings)
=> fixes styling for kindergarten garden

.eslintignore, exercises/grade-school/example.js, package.json
_removed "fixes" language_ -MM
this PR fixes the variable "grade" in exercise grade-school which was previously declared in the upper scope.
=> fixes styling in grade-school

.eslintignore, exercises/simple-linked-list/example.js, exercises/simple-linked-list/simple-linked-list.spec.js
Fix lint errors on simple-linked-list exercise according to Issue #399
=> Fix lint errors on simple-linked-list

.eslintignore, exercises/secret-handshake/example.js, exercises/secret-handshake/secret-handshake.spec.js
Makes necessary changes for eslinter.
=> Issue #399 - Secret-handshake

config.json, exercises/armstrong-numbers/README.md, exercises/armstrong-numbers/armstrong-numbers.spec.js, exercises/armstrong-numbers/example.js
[Problem specification and test data](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers)
=> Add armstrong-numbers exercise

.eslintignore, exercises/minesweeper/example.js
=> fix linting for minesweeper exercise

.eslintignore, exercises/linked-list/example.js
Issue #399. Please let me know if any issues in my PR, this is my first contribution. Thanks !
=> fix linting for linked-list exercise

exercises/bowling/bowling.spec.js
=> implement the two recently addeded tests from the canonical test spec

.eslintignore, exercises/simple-cipher/example.js, exercises/simple-cipher/simple-cipher.spec.js
=> Fix simple cipher

.eslintignore, config.json, config/maintainers.json, docs/LEARNING.md, exercises/bob/bob.spec.js, exercises/bob/example.js, exercises/bowling/bowling.spec.js, exercises/nth-prime/example.js, exercises/nth-prime/nth-prime.spec.js, exercises/pangram/pangram.spec.js, exercises/robot-simulator/example.js, exercises/simple-cipher/example.js, exercises/simple-cipher/simple-cipher.spec.js
The test execute time has gone from `2.975s` with the old example code and the old tests to `3.200s` with the new tests and the new example code.
=> Fix #540 : Added more tests to nth-prime and altered example code
